import { themeScript } from "@repo/design-system/theme";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

/* Poppins is a STATIC font — unlike a variable font, every weight is its own
 * file and `weight: "100 900"` is invalid here. Each weight must be listed
 * explicitly; any weight omitted would silently fall back to the nearest
 * available one, and `font-synthesis: none` (set in page.module.css) blocks
 * the browser from faking it. All nine are loaded so every Tailwind
 * `font-*` utility resolves to a real face. */
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable} suppressHydrationWarning>
      <head>
        {/*
          Runs before first paint so `data-theme` is already on <html> when
          the page renders. Without it the server sends unthemed markup and a
          dark-mode user gets a white flash on every hard load.
          `suppressHydrationWarning` above is what lets the attribute differ
          between server and client.
        */}
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body>{children}</body>
    </html>
  );
}
