\set ON_ERROR_STOP on
begin;
create function pg_temp.check(p_label text,p_ok boolean) returns void language plpgsql as $$
begin if p_ok is distinct from true then raise exception 'FAIL %',p_label; end if; raise notice 'ok %',p_label; end $$;
select pg_temp.check('Endpoint catalogue exists',to_regclass('public.webhook_endpoints') is not null);
select pg_temp.check('Four focused durable tables',to_regclass('public.webhook_endpoint_commands') is not null and to_regclass('public.webhook_deliveries') is not null and to_regclass('public.webhook_delivery_attempts') is not null);
select pg_temp.check('Browser cannot read envelopes',not has_table_privilege('authenticated','public.webhook_endpoints','SELECT'));
select pg_temp.check('Claims service-only',not has_function_privilege('authenticated','public.m1103_claim_webhook_delivery(uuid,text,integer)','EXECUTE'));
select pg_temp.check('Non-forced RLS',(select relrowsecurity and not relforcerowsecurity from pg_class where oid='public.webhook_endpoints'::regclass));
select pg_temp.check('Every webhook helper denies browser execute',not exists(select 1 from pg_proc where proname like 'm1103_%' and (has_function_privilege('anon',oid,'execute') or has_function_privilege('authenticated',oid,'execute'))));
select pg_temp.check('Service role cannot bypass atomic writes',not has_table_privilege('service_role','public.webhook_deliveries','UPDATE') and not has_table_privilege('service_role','public.webhook_endpoints','INSERT'));
select pg_temp.check('Pinned search paths',not exists(select 1 from pg_proc where proname like 'm1103_%' and not ('search_path=public, pg_temp'=any(proconfig))));
select pg_temp.check('Public metadata credential canary guard',public.m1103_metadata_contains_credential('Copied '||encode(decode(repeat('11',32),'hex'),'base64')) and public.m1103_metadata_contains_credential(replace(encode(decode(repeat('11',32),'hex'),'base64'),'=','%253D')) and not public.m1103_metadata_contains_credential('Receiver unreachable; operator reviewed.'));
select pg_temp.check('SQL accepts canonical percent-encoded and tilde paths',public.m1103_valid_webhook_url('https://receiver.example/hooks%20v1/~events'));
select pg_temp.check('SQL query and fragment remain rejected',not public.m1103_valid_webhook_url('https://receiver.example/hook?token=secret') and not public.m1103_valid_webhook_url('https://receiver.example/hook#fragment'));
select pg_temp.check('SQL blocks private/ambiguous literal destinations',not exists(select 1 from unnest(array['https://169.254.169.254/path','https://127.1','https://2130706433','https://0177.0.0.1','https://0x7f.0.0.1','https://metadata.google.internal']) x where public.m1103_valid_webhook_url(x)));
select pg_temp.check('Base uniqueness permits child replay',exists(select 1 from pg_indexes where tablename='webhook_deliveries' and indexname='webhook_deliveries_base_event_key' and indexdef like '%WHERE%'));
do $$
declare o uuid:=gen_random_uuid();u uuid:=gen_random_uuid();le uuid:=gen_random_uuid();p uuid:=gen_random_uuid();r uuid:=gen_random_uuid();f uuid:=gen_random_uuid();a uuid:=gen_random_uuid();ob uuid:=gen_random_uuid();ep uuid:=gen_random_uuid();kid uuid:=gen_random_uuid();epoch bigint;v record;c record;z record;dd uuid;dg integer;key uuid:=gen_random_uuid();ev text;source uuid;cn uuid;run uuid;v_digest text;oldversion integer;cnt integer;secret jsonb;anchor uuid:=gen_random_uuid();freshkid uuid;prevslot jsonb;newenv jsonb;before_version integer;fresh_source uuid;body text;child uuid;grandchild uuid;parentversion integer;urlpreview record;signer record;signer_id uuid;signer_gen integer;signer_body text;ep2 uuid:=gen_random_uuid();
begin
 insert into public.users(id,email) values(u,'m1103-'||u::text||'@cra.test');
 insert into public.organizations(id,name,slug) values(o,'M1103 isolated fixture','m1103-'||o::text);
 insert into public.organization_members(organization_id,user_id,role) values(o,u,'owner');
 select version into epoch from public.organization_permissions_version where organization_id=o;
 insert into public.organization_legal_entities(id,organization_id,identifier,display_name,completion_status,status,created_by,updated_by) values(le,o,'fixture','M1103','needs_completion','inactive',u,u);
 insert into public.products(id,organization_id,legal_entity_id,legal_entity_version,legal_entity_snapshot,name,internal_code,product_type,responsible_owner_id,created_by,updated_by) values(p,o,le,0,'{}','Fixture','M1103','standalone_software',u,u,u);
 insert into public.product_releases(id,organization_id,product_id,legal_entity_id,legal_entity_version,legal_entity_snapshot,label,release_version,created_by,updated_by) values(r,o,p,le,0,'{}','Fixture','1',u,u);
 secret:=jsonb_build_object('keyId',kid,'secretId',kid,'revision',1,'envelope',jsonb_build_object('format','aes-256-gcm-v1','keyId','test-master','ciphertext',encode('cipher'::bytea,'base64'),'nonce',encode(decode(repeat('11',12),'hex'),'base64'),'authTag',encode(decode(repeat('11',16),'hex'),'base64')));
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep,u,'create',null,key,repeat('a',64),'test-master',epoch,jsonb_build_object('displayName','Fixture','url','https://receiver.example.test/events','eventTypes',array['product.release.market_availability_changed','product.release.lifecycle_changed','product.release.placed_on_market_changed','product.relationship.graph_changed','vulnerability.assessment.submitted','vulnerability.assessment.approved','vulnerability.assessment.rejected','vulnerability.assessment.superseded','vulnerability.remediation_anchor.recorded','vulnerability.remediation_anchor.corrected','reporting.deadline.threshold_crossed','reporting.deadline.breached','reporting.filing.recorded','connector.sync_completed','connector.sync_failed'],'productIds',array[p],'secret',secret));
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,gen_random_uuid(),u,'create',null,gen_random_uuid(),repeat('f',64),'test-master',epoch,jsonb_build_object('displayName','Foreign scope','url','https://receiver.example.test/events','eventTypes',array['connector.sync_failed'],'productIds',array[gen_random_uuid()]));
 perform pg_temp.check('Foreign product configuration rejected without effects',v.outcome='invalid_request' and (select count(*)=1 from public.webhook_endpoints where organization_id=o));
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep,u,'create',null,key,repeat('a',64),'test-master',epoch,'{}');
 perform pg_temp.check('Create durable command and disabled endpoint',v.outcome in ('created','replayed') and not (v.endpoint->>'enabled')::boolean and (select count(*)=1 from public.webhook_endpoint_commands where organization_id=o));
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,gen_random_uuid(),u,'create',null,key,repeat('a',64),'test-master',epoch,'{}');
 perform pg_temp.check('Create retry stable endpoint identity',v.outcome='replayed' and (v.endpoint->>'id')::uuid=ep);
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep,u,'create',null,key,repeat('b',64),'test-master',epoch,'{}');
 perform pg_temp.check('Changed idempotency payload conflicts',v.outcome='idempotency_conflict');
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep,u,'enable',1,gen_random_uuid(),repeat('b',64),'test-master',epoch,'{}');
 perform pg_temp.check('Enable increments optimistic version',v.outcome='updated' and (v.endpoint->>'version')::integer=2);
 for ev in select unnest(array['release.market_availability_changed','release.lifecycle_changed','release.placed_on_market_changed','product_relationship.graph_changed']) loop
  source:=gen_random_uuid();insert into public.product_regulatory_outbox_events(id,organization_id,product_id,release_id,event_type,event_key,payload,correlation_id,occurred_at) values(source,o,p,r,ev,source::text,'{"secret_canary":"never_send"}',gen_random_uuid(),clock_timestamp());
 end loop;
 perform pg_temp.check('Four actual product source inserts captured atomically',(select count(*)=4 from public.webhook_deliveries where organization_id=o));
 perform pg_temp.check('Raw source canary absent',(select not bool_or(coalesce(payload_bytes,'') like '%never_send%') from public.webhook_deliveries where organization_id=o));
 insert into public.vulnerability_findings select (jsonb_populate_record(null::public.vulnerability_findings,to_jsonb(x)||jsonb_build_object('id',f,'organization_id',o,'release_id',r,'component_identity','m1103-'||f::text))).* from public.vulnerability_findings x limit 1;
 insert into public.vulnerability_finding_assessments(id,organization_id,finding_id,revision,vex_status,detail,approval_state,approval_required,policy_severity,policy_version,submitted_by,updated_by) values(a,o,f,1,'affected','Fixture','approval_not_required',false,'unknown',0,u,u);
 for ev in select unnest(array['submitted','approved','rejected','superseded']) loop
  insert into public.vulnerability_finding_assessment_history_events(organization_id,assessment_id,event_type,actor_user_id,new_values) values(o,a,ev,u,'{}');
 end loop;
 insert into public.vulnerability_finding_remediation_anchors(id,organization_id,finding_id,revision,remediation_kind,mitigation_description,recorded_by) values(anchor,o,f,1,'mitigation','Fixture',u);
 for ev in select unnest(array['remediation_anchor.recorded','remediation_anchor.corrected']) loop
  source:=gen_random_uuid();insert into public.product_regulatory_outbox_events(id,organization_id,product_id,release_id,finding_id,remediation_anchor_id,event_type,event_key,payload,correlation_id,occurred_at) values(source,o,p,r,f,anchor,ev,source::text,'{}',gen_random_uuid(),clock_timestamp());
 end loop;
 insert into public.reporting_obligations(id,organization_id,obligation_type,source_finding_id,awareness_at,awareness_basis,rule_set_id,rule_set_version,rule_snapshot,created_by_user_id,created_by_display_name) values(ob,o,'actively_exploited_vulnerability',f,date_trunc('second',clock_timestamp()),'Fixture',(select id from public.reporting_rule_sets limit 1),1,'{}',u,'Fixture');
 for ev in select unnest(array['deadline_threshold_crossed','deadline_breached','filing_recorded']) loop
  insert into public.reporting_obligation_events(organization_id,obligation_id,event_kind) values(o,ob,ev);
 end loop;
 select * into v from public.m11_create_connector_atomic(o,u,epoch,gen_random_uuid(),'reference_conformance','M1103','1.0.0','v1','{}','manual');cn:=(v.connector->>'id')::uuid;
 for ev in select unnest(array['completed','failed']) loop
  select * into v from public.m11_begin_sync_run_atomic(o,cn,u,epoch,'incremental',gen_random_uuid(),gen_random_uuid());run:=(v.run->>'id')::uuid;
  insert into public.sync_run_plan_items(organization_id,sync_run_id,external_id,entity_type,proposed_action,field_diffs,issues,cra_product_id) values(o,run,'fixture','product','unchanged','{}','[]',p);
  update public.sync_runs set status='running',started_at=clock_timestamp() where organization_id=o and id=run;
  update public.sync_runs set status=ev,finished_at=clock_timestamp(),committed_at=case when ev='completed' then clock_timestamp() end where organization_id=o and id=run;
 end loop;
 perform pg_temp.check('All fifteen backed source events captured',(select count(distinct event_type)=15 from public.webhook_deliveries where organization_id=o));
 select * into c from public.m1103_claim_webhook_delivery(o,'worker-a',60);dd:=(c.result#>>'{delivery,id}')::uuid;dg:=(c.result->>'leaseGeneration')::integer;
 perform pg_temp.check('Claim opens one durable attempt',c.outcome='claimed' and dg=1 and (select count(*)=1 from public.webhook_delivery_attempts where organization_id=o));
 select * into v from public.m1103_complete_webhook_delivery(o,dd,'worker-a',0,204,1,0);
 perform pg_temp.check('Late generation cannot finish',v.outcome='lease_lost');
 body:=jsonb_build_object('schemaVersion',1,'eventId',c.result#>>'{delivery,eventId}','deliveryId',c.result#>>'{delivery,deliveryId}','eventType',c.result#>>'{delivery,eventType}','occurredAt',c.result#>>'{delivery,occurredAt}','organizationId',o,'resource',c.result#>'{delivery,resource}')::text;
 select * into v from public.m1103_prepare_webhook_delivery(o,dd,'worker-a',dg,u,epoch,body,1);
 perform pg_temp.check('Before-send authorizes and pins exact bytes',v.outcome='prepared');
 select * into v from public.m1103_prepare_webhook_delivery(o,dd,'worker-a',dg,u,epoch,replace(body,o::text,gen_random_uuid()::text),1);
 perform pg_temp.check('Forged tenant envelope rejected',v.outcome='invalid_request');
 select * into v from public.m1103_prepare_webhook_delivery(o,dd,'worker-a',dg,u,epoch,body||' ',1);
 perform pg_temp.check('Retry bytes cannot change',v.outcome='conflict');
 select * into v from public.m1103_fail_webhook_delivery(o,dd,'worker-a',dg,'rate_limit','secret_canary',429,1,0,120);
 perform pg_temp.check('Retry After obeyed and provider code discarded',v.outcome='retrying' and (select next_attempt_at>=clock_timestamp()+interval '119 seconds' and last_failure_code='receiver_rate_limited' from public.webhook_deliveries where id=dd));
 begin update public.webhook_delivery_attempts set worker_id='tampered' where organization_id=o and delivery_row_id=dd;raise exception 'attempt unexpectedly changed';exception when object_not_in_prerequisite_state then null;end;
 perform pg_temp.check('Closed attempt immutable',true);
 update public.webhook_deliveries set next_attempt_at=clock_timestamp()-interval '1 second' where id=dd;
 select * into c from public.m1103_claim_webhook_delivery(o,'worker-b',60);
 -- Another pending source might precede dd; use its claim to exercise restart.
 dd:=(c.result#>>'{delivery,id}')::uuid;dg:=(c.result->>'leaseGeneration')::integer;
 update public.webhook_deliveries set lease_expires_at=clock_timestamp()-interval '1 second',next_attempt_at=clock_timestamp()-interval '2 days',deadline_at=clock_timestamp()+interval '2 minutes' where id=dd;
 select * into c from public.m1103_claim_webhook_delivery(o,'worker-c',60);
 perform pg_temp.check('Expired lease rescheduled with jitter',(select status='retrying' and lease_owner is null and next_attempt_at>clock_timestamp() from public.webhook_deliveries where id=dd));
 update public.webhook_deliveries set next_attempt_at=clock_timestamp()-interval '3 days' where id=dd;
 select * into c from public.m1103_claim_webhook_delivery(o,'worker-c',60);
 perform pg_temp.check('Expired lease recovered fenced',(c.result#>>'{delivery,id}')::uuid=dd and (c.result->>'leaseGeneration')::integer=dg+1);
 perform pg_temp.check('Abandoned attempt interrupted',(select outcome='interrupted' from public.webhook_delivery_attempts where delivery_row_id=dd and lease_generation=dg));
 select * into v from public.m1103_fail_webhook_delivery(o,dd,'worker-c',dg+1,'receiver_rejected','provider_canary',401,1,0,null);
 perform pg_temp.check('Authentication rejection terminal',v.outcome='failed');
 select version into oldversion from public.webhook_deliveries where id=dd;
 select * into z from public.m1103_preview_webhook_replay(o,ep,dd,u,epoch,2,oldversion);
 perform pg_temp.check('Server-computed reviewed replay available',z.outcome='previewed');
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep,u,'replay',2,gen_random_uuid(),repeat('c',64),'test-master',epoch,jsonb_build_object('deliveryId',dd,'expectedDeliveryVersion',oldversion,'previewDigest',z.preview->>'previewDigest'),'Reviewed receiver recovery');
 perform pg_temp.check('Replay child preserves event parent',(v.command->>'deliveryId')::uuid<>dd and exists(select 1 from public.webhook_deliveries n join public.webhook_deliveries parent on parent.id=n.parent_delivery_id where n.parent_delivery_id=dd and n.event_id=parent.event_id and parent.status='failed'));
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep,u,'replay',2,gen_random_uuid(),repeat('f',64),'test-master',epoch,jsonb_build_object('deliveryId',dd,'expectedDeliveryVersion',oldversion,'previewDigest',z.preview->>'previewDigest'),'Duplicate reviewed recovery');
 perform pg_temp.check('Duplicate active replay rejected',v.outcome='conflict');
 select id into child from public.webhook_deliveries where organization_id=o and parent_delivery_id=dd;
 update public.webhook_deliveries set status='failed',completed_at=clock_timestamp() where id=child;
 select * into urlpreview from public.m1103_preview_webhook_replay(o,ep,child,u,epoch,2,1);
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep,u,'replay',2,gen_random_uuid(),repeat('f',64),'test-master',epoch,jsonb_build_object('deliveryId',child,'expectedDeliveryVersion',1,'previewDigest',urlpreview.preview->>'previewDigest'),'Reviewed child recovery');
 grandchild:=(v.command->>'deliveryId')::uuid;
 perform pg_temp.check('Grandchild reviewed replay created',grandchild is not null);
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep,u,'replay',2,gen_random_uuid(),repeat('f',64),'test-master',epoch,jsonb_build_object('deliveryId',dd,'expectedDeliveryVersion',oldversion,'previewDigest',z.preview->>'previewDigest'),'Competing ancestor recovery');
 perform pg_temp.check('Active replay uniqueness spans entire event lineage',v.outcome='conflict');

 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep,u,'disable',1,gen_random_uuid(),repeat('a',64),'test-master',epoch,'{}','Stale operator');
 perform pg_temp.check('Stale endpoint version cannot disable',v.outcome='conflict');
 select * into v from public.m1103_webhook_source_scope(gen_random_uuid(),'product',source,'product.release.lifecycle_changed');
 perform pg_temp.check('Forged source tenant does not resolve',v.outcome='scope_unknown');
 select * into signer from public.m1103_claim_webhook_delivery(o,'rotation-inflight',60);
 signer_id:=(signer.result#>>'{delivery,id}')::uuid;signer_gen:=(signer.result->>'leaseGeneration')::integer;
 signer_body:=jsonb_build_object('schemaVersion',1,'eventId',signer.result#>>'{delivery,eventId}','deliveryId',signer.result#>>'{delivery,deliveryId}','eventType',signer.result#>>'{delivery,eventType}','occurredAt',signer.result#>>'{delivery,occurredAt}','organizationId',o,'resource',signer.result#>'{delivery,resource}')::text;
 freshkid:=gen_random_uuid();secret:=jsonb_set(jsonb_set(jsonb_set(secret,'{keyId}',to_jsonb(freshkid)),'{secretId}',to_jsonb(freshkid)),'{revision}','2');
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep,u,'rotate_secret',2,gen_random_uuid(),repeat('a',64),'test-master',epoch,jsonb_build_object('secret',secret,'overlapSeconds',3600));
 perform pg_temp.check('Signing rotation retains recovery overlap',v.outcome='updated' and (select signing_key_id=freshkid and previous_signing_key_id=kid and previous_secret_expires_at>clock_timestamp()+interval '59 minutes' from public.webhook_endpoints where id=ep));
 select * into v from public.m1103_prepare_webhook_delivery(o,signer_id,'rotation-inflight',signer_gen,u,epoch,signer_body,1);
 perform pg_temp.check('Claimed previous signer works during approved overlap',v.outcome='prepared');
 select * into v from public.m1103_complete_webhook_delivery(o,signer_id,'rotation-inflight',signer_gen,204,1,0);
 perform pg_temp.check('Old signer ack preserved without marking current key healthy',v.outcome='succeeded' and (select last_delivered_at is null from public.webhook_endpoints where id=ep));
 freshkid:=gen_random_uuid();secret:=jsonb_set(jsonb_set(jsonb_set(secret,'{keyId}',to_jsonb(freshkid)),'{secretId}',to_jsonb(freshkid)),'{revision}','3');
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep,u,'rotate_secret',3,gen_random_uuid(),repeat('a',64),'test-master',epoch,jsonb_build_object('secret',secret,'overlapSeconds',3600));
 perform pg_temp.check('Overlapping rotation rejected without state change',v.outcome='invalid_request' and (select version=3 and secret_revision=2 from public.webhook_endpoints where id=ep));
 select public.m1103_webhook_slot_json(e,true)->'envelope' into prevslot from public.webhook_endpoints e where e.id=ep;
 newenv:=jsonb_set(prevslot,'{keyId}','"recovery-master"');
 select * into v from public.m1103_rewrap_webhook_secret_atomic(o,ep,kid,1,prevslot,newenv);
 perform pg_temp.check('Previous key maintenance preserves semantic versions',v.outcome='rewrapped' and (select version=3 and secret_revision=2 and previous_secret_revision=1 from public.webhook_endpoints where id=ep));
 select * into v from public.m1103_rewrap_webhook_secret_atomic(o,ep,kid,1,prevslot,newenv);
 perform pg_temp.check('Interrupted maintenance CAS conflict',v.outcome='conflict');
 select public.m1103_webhook_slot_json(e,true)->'envelope' into prevslot from public.webhook_endpoints e where e.id=ep;
 select * into v from public.m1103_rewrap_webhook_secret_atomic(o,ep,kid,1,prevslot,jsonb_set(prevslot,'{nonce}','"not base64!"'));
 perform pg_temp.check('Malformed rewrap envelope returns safe outcome',v.outcome='invalid_request');
 perform pg_temp.check('Recovery key references cover both slots and commands',public.m1103_webhook_key_references(o)#>>'{envelopeKeyReferences,recovery-master}'='1' and (public.m1103_webhook_key_references(o)#>>'{commandKeyReferences,test-master}')::integer>0);
 select * into c from public.m1103_claim_webhook_delivery(o,'long-retry',60);
 select * into v from public.m1103_prepare_webhook_delivery(o,(c.result#>>'{delivery,id}')::uuid,'long-retry',(c.result->>'leaseGeneration')::integer,u,epoch,'{}',1);
 perform pg_temp.check('Rotation fences stale signer revision',v.outcome='forbidden');
 select * into v from public.m1103_fail_webhook_delivery(o,(c.result#>>'{delivery,id}')::uuid,'long-retry',(c.result->>'leaseGeneration')::integer,'rate_limit','unsafe',429,0,0,9999999999::bigint);
 perform pg_temp.check('Huge valid Retry After finishes without overflow',v.outcome='failed');
 -- A second connector source with no known product scope must be withheld.
 select * into v from public.m11_create_connector_atomic(o,u,epoch,gen_random_uuid(),'reference_conformance','M1103 unknown','1.0.0','v1','{}','manual');cn:=(v.connector->>'id')::uuid;
 select * into v from public.m11_begin_sync_run_atomic(o,cn,u,epoch,'incremental',gen_random_uuid(),gen_random_uuid());run:=(v.run->>'id')::uuid;
 update public.sync_runs set status='failed',finished_at=clock_timestamp() where organization_id=o and id=run;
 perform pg_temp.check('Unknown sync scope withheld',(select status='canceled' and last_failure_category='scope_unknown' from public.webhook_deliveries where organization_id=o and source_id=run));
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep,u,'update',3,gen_random_uuid(),repeat('c',64),'test-master',epoch,jsonb_build_object('displayName','Fixture','url','https://changed-receiver.example.test/events','eventTypes',(select to_jsonb(event_types) from public.webhook_endpoints where id=ep),'productIds',array[p]));
 perform pg_temp.check('URL replacement atomically cancels old receiver work',v.outcome='updated' and (select destination_revision=2 from public.webhook_endpoints where id=ep) and not exists(select 1 from public.webhook_deliveries where organization_id=o and status in ('pending','retrying','delivering')));
 select * into urlpreview from public.m1103_preview_webhook_replay(o,ep,dd,u,epoch,4,oldversion);
 perform pg_temp.check('Changed receiver requires fresh preview',urlpreview.outcome='previewed' and (urlpreview.preview->>'receiverChanged')::boolean);
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep,u,'replay',4,gen_random_uuid(),repeat('e',64),'test-master',epoch,jsonb_build_object('deliveryId',dd,'expectedDeliveryVersion',oldversion,'previewDigest',urlpreview.preview->>'previewDigest'),'Review new receiver');
 perform pg_temp.check('Changed receiver replay blocked without explicit confirmation',v.outcome='conflict');
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep,u,'replay',4,gen_random_uuid(),repeat('e',64),'test-master',epoch,jsonb_build_object('deliveryId',dd,'expectedDeliveryVersion',oldversion,'previewDigest',urlpreview.preview->>'previewDigest','confirmDestinationChange',true),'Review new receiver');
 perform pg_temp.check('Confirmed replay has fresh projection, no historical body copy',v.outcome='updated' and (select endpoint_url='https://changed-receiver.example.test/events' and payload_bytes is null from public.webhook_deliveries where id=(v.command->>'deliveryId')::uuid));
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep,u,'disable',4,gen_random_uuid(),repeat('d',64),'test-master',epoch,'{}','Pause receiver');
 perform pg_temp.check('Disable cancels all pending and leased work',v.outcome='updated' and not exists(select 1 from public.webhook_deliveries where organization_id=o and status in ('pending','retrying','delivering')));
 perform pg_temp.check('Export redacts payload',not public.m1_export_business_record_jsonb('webhook_deliveries','{"payload_bytes":"CANARY","lease_generation":4,"id":"safe"}')?'payload_bytes');
 perform pg_temp.check('Export redacts key slots',not public.m1_export_business_record_jsonb('webhook_endpoints','{"secret_ciphertext":"CANARY","display_name":"safe"}')?'secret_ciphertext');
 -- A no-overlap rotation must never authorize a previously claimed old key.
 kid:=gen_random_uuid();secret:=jsonb_set(jsonb_set(jsonb_set(secret,'{keyId}',to_jsonb(kid)),'{secretId}',to_jsonb(kid)),'{revision}','1');
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep2,u,'create',null,gen_random_uuid(),repeat('e',64),'test-master',epoch,jsonb_build_object('displayName','Zero overlap','url','https://receiver.example.test/events','eventTypes',array['connector.sync_completed'],'productIds',array[p],'secret',secret));
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep2,u,'test',1,gen_random_uuid(),repeat('e',64),'test-master',epoch,'{}');
 select * into signer from public.m1103_claim_webhook_delivery(o,'zero-overlap',60);signer_id:=(signer.result#>>'{delivery,id}')::uuid;signer_gen:=(signer.result->>'leaseGeneration')::integer;
 signer_body:=jsonb_build_object('schemaVersion',1,'eventId',signer.result#>>'{delivery,eventId}','deliveryId',signer.result#>>'{delivery,deliveryId}','eventType',signer.result#>>'{delivery,eventType}','occurredAt',signer.result#>>'{delivery,occurredAt}','organizationId',o,'resource',signer.result#>'{delivery,resource}')::text;
 freshkid:=gen_random_uuid();secret:=jsonb_set(jsonb_set(jsonb_set(secret,'{keyId}',to_jsonb(freshkid)),'{secretId}',to_jsonb(freshkid)),'{revision}','2');
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep2,u,'rotate_secret',1,gen_random_uuid(),repeat('e',64),'test-master',epoch,jsonb_build_object('secret',secret,'overlapSeconds',0));
 select * into v from public.m1103_prepare_webhook_delivery(o,signer_id,'zero-overlap',signer_gen,u,epoch,signer_body,1);
 perform pg_temp.check('Zero overlap rejects old claimed signer',v.outcome='forbidden');
 update public.webhook_deliveries set lease_expires_at=clock_timestamp()-interval '1 second',deadline_at=clock_timestamp()-interval '1 second' where id=signer_id;
 select * into v from public.m1103_claim_webhook_delivery(o,'expired-deadline',60);
 perform pg_temp.check('Elapsed deadline closes abandoned attempt without fresh claim',(select status='failed' and lease_owner is null and lease_generation=signer_gen from public.webhook_deliveries where id=signer_id));
 update public.organization_permissions_version set version=version+1 where organization_id=o;
 select * into v from public.m1103_execute_webhook_endpoint_command_atomic(o,ep,u,'create',null,key,repeat('a',64),'test-master',epoch,'{}');
 perform pg_temp.check('Permission epoch revocation checked before idempotent replay',v.outcome='forbidden');
 perform pg_temp.check('No source raw canary in command audit',(select not coalesce(bool_or(changes::text like '%never_send%' or changes::text like '%cipher%'),false) from public.audit_logs where organization_id=o and action like 'webhook.%'));
end $$;

rollback;
