begin;
create function pg_temp.check(p_name text,p_ok boolean) returns void language plpgsql as $$ begin if not coalesce(p_ok,false) then raise exception 'check failed: %',p_name; end if; end $$;
select pg_temp.check('three SIEM tables',to_regclass('public.siem_destinations') is not null and to_regclass('public.siem_deliveries') is not null and to_regclass('public.siem_delivery_attempts') is not null);
select pg_temp.check('private nonforced tables',not exists(select 1 from pg_class where relnamespace='public'::regnamespace and relname in ('siem_destinations','siem_deliveries','siem_delivery_attempts') and (not relrowsecurity or relforcerowsecurity or has_table_privilege('authenticated',oid,'SELECT') or has_table_privilege('anon',oid,'SELECT'))));
select pg_temp.check('source dependency parity',not exists(select 1 from jsonb_each_text(public.m13_04_dependency_fingerprints()) expected where md5(pg_get_functiondef(('public.'||expected.key)::regprocedure))<>expected.value));
select pg_temp.check('private RPC grants',not exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname like 'm13_05_%' and (has_function_privilege('authenticated',oid,'EXECUTE') or has_function_privilege('anon',oid,'EXECUTE'))));
select pg_temp.check('pinned paths',not exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname like 'm13_05_%' and not coalesce(proconfig @> array['search_path=pg_catalog, public'],false)));
savepoint siem_owned_fixture;
do $$ declare o uuid:=gen_random_uuid();u uuid:=gen_random_uuid();d uuid:=gen_random_uuid();r uuid:=gen_random_uuid();j jsonb;v integer;page jsonb;preview jsonb;begin
 insert into public.organizations(id,name,slug) values(o,'SIEM rollback fixture','siem-'||o);
 insert into public.users(id,email) values(u,'siem-'||u||'@cra.test');
 insert into public.organization_members(organization_id,user_id,role) values(o,u,'owner');
 j:=public.m13_05_siem_command(o,u,'create',r,null,d,jsonb_build_object('name','SIEM','transport','https','format','json','endpoint','https://collector.example.test','eventClasses',jsonb_build_array('organization'),'productIds','[]'::jsonb,'operationDigest',repeat('a',64),'keyId','key1'));
 perform pg_temp.check('draft created',j->>'state'='draft');
 perform pg_temp.check('same command replay',public.m13_05_siem_command(o,u,'create',r,null,d,jsonb_build_object('operationDigest',repeat('a',64)))=j);
 begin perform public.m13_05_siem_command(o,u,'create',r,null,d,jsonb_build_object('operationDigest',repeat('b',64)));raise exception 'changed command accepted';exception when unique_violation then null;end;
 insert into public.base_role_permission_overrides(organization_id,base_role,permissions) values(o,'owner','{"can_export_audit":false}');
 begin perform public.m13_05_siem_command(o,u,'create',r,null,d,jsonb_build_object('operationDigest',repeat('a',64)));raise exception 'revoked cached mutation accepted';exception when insufficient_privilege then null;end;
 delete from public.base_role_permission_overrides where organization_id=o and base_role='owner';
 perform pg_temp.check('key ID replay lookup',public.m13_05_siem_command(o,u,'fingerprint_key',r,null,d,'{}')->>'keyId'='key1');
 begin perform public.m13_05_siem_command(gen_random_uuid(),u,'read',gen_random_uuid(),null,d,'{}');raise exception 'tenant forgery accepted';exception when insufficient_privilege then null;end;
 j:=public.m13_05_siem_command(o,u,'credentials',gen_random_uuid(),1,d,jsonb_build_object('encryptedCredential',jsonb_build_object('format','aes-256-gcm-v1','keyId','key1','ciphertext','encrypted','nonce','nonce','authTag','tag'),'credentialId',gen_random_uuid(),'credentialRevision',2));
 perform pg_temp.check('vault inventory',(public.m13_05_siem_vault(o,'references','{}')->'envelopeKeyReferences'->>'key1')::integer=1);
 perform pg_temp.check('vault list bounded',jsonb_array_length(public.m13_05_siem_vault(o,'list','{"limit":1}'))=1);
 perform pg_temp.check('vault mismatch safe',public.m13_05_siem_vault(o,'replace',jsonb_build_object('destinationId',d,'secretId',gen_random_uuid(),'credentialRevision',2,'expectedEnvelope','{}'::jsonb,'nextEnvelope',jsonb_build_object('format','aes-256-gcm-v1','keyId','key2','ciphertext','ciphertext','nonce','nonce','authTag','tag')))->>'outcome'='conflict');
 perform pg_temp.check('credentials revision',j->>'credentialState'='active' and (select credential_revision=2 from public.siem_destinations where id=d));
 r:=gen_random_uuid();j:=public.m13_05_siem_command(o,u,'test_prepare',r,2,d,jsonb_build_object('operationDigest',repeat('c',64),'keyId','key1'));
 perform pg_temp.check('test intent durable',exists(select 1 from public.audit_logs where action='audit.siem.test_prepare' and correlation_id=r));
 j:=public.m13_05_siem_command(o,u,'test',r,2,d,jsonb_build_object('state','accepted','operationDigest',repeat('c',64),'keyId','key1'));
 perform pg_temp.check('cached test does not resend',public.m13_05_siem_command(o,u,'test_prepare',r,2,d,jsonb_build_object('operationDigest',repeat('c',64)))->>'completed'='true');
 j:=public.m13_05_siem_command(o,u,'enable',gen_random_uuid(),3,d,'{}');
 perform pg_temp.check('enabled',j->>'state'='enabled');
 insert into public.audit_logs(organization_id,action) values(o,'test.legacy.null_entity');
 perform pg_temp.check('legacy NULL entity remains supported',exists(select 1 from public.audit_logs where organization_id=o and action='test.legacy.null_entity' and entity_type is null));
 insert into public.audit_logs(organization_id,action,entity_type,entity_id) values(o,'organization.created','organization',o::text);
 set constraints m13_02_finalize_audit_chain immediate;
 update public.siem_destinations set scheduled_at='-infinity' where id=d;
 j:=public.m13_05_siem_stage('siem-test');
 perform pg_temp.check('future staged',(j->>'staged')::int=1);
 perform pg_temp.check('no private content',(select payload ? 'schemaVersion' and not payload ? 'changes' from public.siem_deliveries where destination_id=d));
 update public.siem_deliveries set next_attempt_at='-infinity' where destination_id=d;
 update public.siem_destinations set scheduled_at='-infinity' where id=d;
 j:=public.m13_05_siem_claim('siem-test');
 perform pg_temp.check('claim tenant',(j->>'organizationId')::uuid=o);
 perform pg_temp.check('pre send authorized',public.m13_05_siem_authorize_delivery(o,(j->>'deliveryId')::uuid,'siem-test',(j->>'leaseToken')::uuid,(j->>'version')::integer) is not null);
 perform public.m13_05_siem_complete(o,(j->>'deliveryId')::uuid,'siem-test',(j->>'leaseToken')::uuid,(j->>'version')::integer,jsonb_build_object('state','retry','code','network_error','durationMs',1));
 perform pg_temp.check('retry retained',(select state='queued' and attempt_count=1 from public.siem_deliveries where destination_id=d));
 begin perform public.m13_05_siem_complete(o,(j->>'deliveryId')::uuid,'siem-test',(j->>'leaseToken')::uuid,(j->>'version')::integer,jsonb_build_object('state','accepted','code','delivered','durationMs',1));raise exception 'stale lease accepted';exception when unique_violation then null;end;
 begin update public.siem_delivery_attempts set code='rewritten' where delivery_id=(j->>'deliveryId')::uuid;raise exception 'attempt modified';exception when insufficient_privilege then null;end;
 insert into public.audit_logs(organization_id,action,entity_type,entity_id,changes) values(o,'organization.secret_canary','organization',o::text,'{"secret":"DO_NOT_FORWARD"}');
 insert into public.audit_logs(organization_id,action,entity_type,entity_id) select o,'organization.created','organization',o::text from generate_series(1,3);
 set constraints m13_02_finalize_audit_chain immediate;update public.siem_destinations set scheduled_at='-infinity' where id=d;
 perform public.m13_05_siem_stage('siem-test');
 perform pg_temp.check('unknown pair excluded',(select count(*)=4 from public.siem_deliveries where destination_id=d));
 page:=public.m13_05_siem_command(o,u,'deliveries',gen_random_uuid(),null,d,jsonb_build_object('limit',2));
 perform pg_temp.check('bounded first page',jsonb_array_length(page->'items')=2 and page->>'nextCursor' is not null);
 page:=public.m13_05_siem_command(o,u,'deliveries',gen_random_uuid(),null,d,jsonb_build_object('limit',2,'cursor',page->>'nextCursor'));
 perform pg_temp.check('bounded next page',jsonb_array_length(page->'items')=2 and page->>'nextCursor' is null);
 begin perform public.m13_05_siem_command(o,u,'deliveries',gen_random_uuid(),null,d,jsonb_build_object('limit',2,'cursor',gen_random_uuid()));raise exception 'foreign cursor accepted';exception when invalid_parameter_value then null;end;
 update public.siem_deliveries set state='failed' where destination_id=d;
 select id into r from public.siem_deliveries where destination_id=d limit 1;
 preview:=public.m13_05_siem_command(o,u,'replay_preview',gen_random_uuid(),null,d,jsonb_build_object('deliveryId',r));
 j:=public.m13_05_siem_command(o,u,'replay',gen_random_uuid(),4,d,jsonb_build_object('deliveryId',r,'previewDigest',preview->>'previewDigest','confirmRecipient',true));
 perform pg_temp.check('replay keeps event identity',j->>'eventId'=preview->'event'->>'eventId' and j->>'parentDeliveryId'=r::text);
 begin perform public.m13_05_siem_command(o,u,'replay',gen_random_uuid(),4,d,jsonb_build_object('deliveryId',r,'previewDigest',repeat('f',64),'confirmRecipient',true));raise exception 'forged preview accepted';exception when unique_violation then null;end;
 update public.users set is_active=false where id=u;
 update public.siem_destinations set scheduled_at='-infinity' where id=d;
 perform pg_temp.check('revoked authority blocks staging',public.m13_05_siem_stage('siem-test')->>'staged'='0');
 perform pg_temp.check('authority paused',(select state='paused' from public.siem_destinations where id=d));
 perform pg_temp.check('security receipt org null',exists(select 1 from public.audit_logs where entity_type='audit_siem' and entity_id=d::text and organization_id is null and chain_sequence is null));
end $$;
rollback to siem_owned_fixture;
savepoint siem_owned_fixture;
do $$ declare o uuid:=gen_random_uuid();u uuid:=gen_random_uuid();l uuid:=gen_random_uuid();p uuid:=gen_random_uuid();d uuid:=gen_random_uuid();e public.audit_logs;j jsonb;begin
 insert into public.organizations(id,name,slug) values(o,'SIEM product rollback fixture','siem-product-'||o);
 insert into public.users(id,email) values(u,'siem-product-'||u||'@cra.test');
 insert into public.organization_members(organization_id,user_id,role) values(o,u,'owner');
 insert into public.organization_legal_entities(id,organization_id,identifier,display_name,legal_name,registered_address_line_1,registered_address_locality,registered_address_postal_code,registered_address_country,main_establishment_country,manufacturer_contact_name,manufacturer_contact_email,created_by,updated_by) values(l,o,'siem-product-'||l,'SIEM entity','SIEM entity','Fixture road','Fixture city','12345','IN','IN','Fixture owner','fixture@cra.test',u,u);
 insert into public.products(id,organization_id,legal_entity_id,legal_entity_version,legal_entity_snapshot,name,internal_code,product_type,responsible_owner_id,created_by,updated_by) values(p,o,l,0,'{}','SIEM synthetic','SIEM-'||p,'standalone_software',u,u,u);
 insert into public.audit_logs(organization_id,action,entity_type,entity_id) values(o,'product.created','product',p::text) returning * into e;
 set constraints m13_02_finalize_audit_chain immediate;
 select * into e from public.audit_logs where id=e.id;
 perform pg_temp.check('selected trusted product',public.m13_05_event_selected(o,u,e,array[p]));
 perform pg_temp.check('unselected trusted product excluded',not public.m13_05_event_selected(o,u,e,array[gen_random_uuid()]));
 j:=public.m13_05_siem_command(o,u,'create',gen_random_uuid(),null,d,jsonb_build_object('name','Product SIEM','transport','https','format','json','endpoint','https://collector.example.test','eventClasses',jsonb_build_array('products'),'productIds',jsonb_build_array(p)));
 begin perform public.m13_05_siem_command(o,u,'create',gen_random_uuid(),null,gen_random_uuid(),jsonb_build_object('name','Forged product','transport','https','format','json','endpoint','https://collector.example.test','eventClasses',jsonb_build_array('products'),'productIds',jsonb_build_array(gen_random_uuid())));raise exception 'forged product stored';exception when insufficient_privilege then null;end;
 insert into public.base_role_permission_overrides(organization_id,base_role,permissions) values(o,'owner','{"can_view_products":false}');
 begin perform public.m13_05_siem_command(o,u,'read',gen_random_uuid(),null,d,'{}');raise exception 'hidden config exposed';exception when no_data_found then null;end;
 perform pg_temp.check('hidden configuration list',jsonb_array_length(public.m13_05_siem_command(o,u,'list',gen_random_uuid(),null,null,'{}')->'items')=0);
 delete from public.base_role_permission_overrides where organization_id=o and base_role='owner';
 perform pg_temp.check('foreign tenant excluded',not public.m13_05_event_selected(gen_random_uuid(),u,e,array[p]));
 e.entity_id:=gen_random_uuid()::text;
 perform pg_temp.check('missing source fails closed',not public.m13_05_event_selected(o,u,e,array[p]));
end $$;
rollback;
