begin;
create temporary table m14_test_scope(org uuid,actor uuid,product uuid,release uuid,finding uuid);
create or replace function pg_temp.check(name text,truth boolean)returns void language plpgsql as $$begin if not coalesce(truth,false)then raise exception 'M14-02 check failed: %',name;end if;raise notice 'M14-02 verified: %',name;end$$;
do $$
declare org uuid:='00000000-0000-4000-8000-0000000000ca'; actor uuid; finding uuid:='00000000-0000-4000-8000-0000000014ff'; a uuid:=gen_random_uuid(); f public.vulnerability_findings; product uuid:=gen_random_uuid();release uuid:=gen_random_uuid(); vulnerability uuid:=gen_random_uuid();run uuid:=gen_random_uuid();source uuid:=gen_random_uuid();source_version uuid:=gen_random_uuid();affected uuid:=gen_random_uuid(); j jsonb; before_state jsonb; after_state jsonb;
begin
 select id into actor from public.users where email='owner@cra.test';
 perform pg_temp.check('seed owner exists',actor is not null);
 insert into public.products(id,organization_id,legal_entity_id,legal_entity_version,legal_entity_snapshot,name,internal_code,product_type,responsible_owner_id,created_by,updated_by)
 select product,org,legal_entity_id,legal_entity_version,legal_entity_snapshot,'M14 synthetic product','m14-'||product,product_type,actor,actor,actor from public.products where organization_id=org limit 1;
 perform pg_temp.check('own synthetic product exists',exists(select 1 from public.products where id=product));
 insert into public.product_releases(id,organization_id,product_id,legal_entity_id,legal_entity_version,legal_entity_snapshot,label,release_version,lifecycle,placed_on_market_at,created_by,updated_by)
 select release,org,product,legal_entity_id,legal_entity_version,legal_entity_snapshot,'M14 release','m14-'||release,'end_of_support',statement_timestamp(),actor,actor from public.products where id=product;
 insert into m14_test_scope values(org,actor,product,release,finding);
 insert into public.vulnerabilities(id,canonical_id,title)values(vulnerability,'CVE-M14-'||vulnerability,'Synthetic M14 source');
 insert into public.vulnerability_feed_sync_runs(id,feed_key,run_kind,correlation_id)values(run,'osv','manual',gen_random_uuid());
 insert into public.vulnerability_source_records(id,feed_key,source_record_key,vulnerability_id)values(source,'osv','m14-'||source,vulnerability);
 insert into public.vulnerability_source_record_versions(id,source_record_id,run_id,record_sha256,record_state,raw_payload,normalized_payload)values(source_version,source,run,repeat('a',64),'active','{}','{}');
 insert into public.vulnerability_affected_ranges(id,vulnerability_id,source_record_version_id,range_value)values(affected,vulnerability,source_version,'{}');
 insert into public.vulnerability_findings(id,organization_id,release_id,component_identity,canonical_advisory_id,vulnerability_id,source_feed_key,source_record_id,source_record_version_id,affected_range_id,match_method,comparator_name,comparator_version,evaluated_component_value,affected_range,event_sequence,confidence,confidence_table_version,confidence_explanation)values(finding,org,release,'m14-test-'||finding,'CVE-M14-'||vulnerability,vulnerability,'osv',source,source_version,affected,'purl_osv','m14-test','1','1','{}','[]',.9,'m14-test','Synthetic rollback-only test');

 set constraints all immediate;
 perform pg_temp.check('new finding captured once',(select count(*)=1 from public.vulnerability_finding_lifecycle_facts where finding_id=finding));
 set constraints all deferred;
 insert into public.vulnerability_finding_assessments(id,organization_id,finding_id,revision,is_current,vex_status,detail,approval_state,approval_required,policy_severity,policy_version,submitted_at,submitted_by,updated_by)values(a,org,finding,1,true,'fixed','Resolved synthetic finding','approval_not_required',false,'unknown',1,statement_timestamp(),actor,actor);
 update public.vulnerability_findings set reevaluation_state='review_required'where id=finding;
 set constraints all immediate;
 perform pg_temp.check('final state capture does not invent transient closure',(select count(*)=2 from public.vulnerability_finding_lifecycle_facts where finding_id=finding));
 perform pg_temp.check('first triage retained',(select payload->>'triagedAt' is not null from public.vulnerability_finding_lifecycle_facts where finding_id=finding order by sequence desc limit 1));
 perform pg_temp.check('fixed assessment retained despite reopening',(select payload->>'fixedAt' is not null and payload->>'open'='true' from public.vulnerability_finding_lifecycle_facts where finding_id=finding order by sequence desc limit 1));
 set constraints all deferred;
 update public.vulnerability_findings set last_evaluated_at=clock_timestamp()where id=finding;
 set constraints all immediate;
 perform pg_temp.check('irrelevant reevaluation deduplicates',(select count(*)=2 from public.vulnerability_finding_lifecycle_facts where finding_id=finding));
 set constraints all deferred;
 update public.vulnerability_findings set reevaluation_state='unchanged'where id=finding;
 set constraints all immediate;
 perform pg_temp.check('effective closure captured',(select payload->>'open'='false'from public.vulnerability_finding_lifecycle_facts where finding_id=finding order by sequence desc limit 1));
 set constraints all deferred;
 update public.vulnerability_findings set reevaluation_state='review_required'where id=finding;
 set constraints all immediate;
 perform pg_temp.check('reopening captured',(select count(*)=4 from public.vulnerability_finding_lifecycle_facts where finding_id=finding));
 begin update public.vulnerability_finding_lifecycle_facts set effective_at=clock_timestamp()where finding_id=finding;raise exception 'Expected immutable failure';exception when raise_exception then perform pg_temp.check('facts reject correction by mutation',sqlerrm='source trend facts are immutable');end;
 perform pg_temp.check('finding facts contain top level xid',(select bool_and(recorded_transaction_id=pg_current_xact_id())from public.vulnerability_finding_lifecycle_facts where finding_id=finding));
 perform pg_temp.check('coverage final state captured',(select count(*)=1 from public.sbom_release_coverage_facts where release_id=release));
 set constraints all deferred;
 update public.product_releases set lifecycle='withdrawn'where id=release;
 set constraints all immediate;
 perform pg_temp.check('coverage denominator exit preserved',(select payload->>'eligible'='false'from public.sbom_release_coverage_facts where release_id=release order by sequence desc limit 1));
 set constraints all deferred;
 update public.product_releases set updated_at=clock_timestamp()where id=release;
 update public.product_releases set lifecycle='withdrawn'where id=release;
 set constraints all immediate;
 perform pg_temp.check('coverage unchanged final state deduplicates',(select count(*)=2 from public.sbom_release_coverage_facts where release_id=release));
end$$;
do $$
declare scope record;admin uuid;finding uuid:=gen_random_uuid();bulk_finding uuid:=gen_random_uuid();r record;assessment uuid;v integer;policy_version integer;fixed_at text;triage_at text;operation uuid;digest text;pin jsonb;filters jsonb;before_dataset jsonb;after_dataset jsonb;page jsonb;
begin
 select *into scope from m14_test_scope;select id into admin from public.users where email='admin@cra.test';
 insert into public.vulnerability_findings select(jsonb_populate_record(null::public.vulnerability_findings,to_jsonb(f)||jsonb_build_object('id',finding,'component_identity','m14-real-decisions-'||finding,'closed_at',null,'closure_reason',null,'superseded_at',null,'reevaluation_state','unchanged'))).*from public.vulnerability_findings f where id=scope.finding;
 set constraints all immediate;set constraints all deferred;
 select coalesce(max(version),0)into policy_version from public.vulnerability_assessment_approval_policies where organization_id=scope.org and severity='unknown';
 select *into r from public.set_vulnerability_assessment_approval_policy_atomic(scope.org,scope.actor,'unknown',true,policy_version,gen_random_uuid(),repeat('a',64));
 select *into r from public.submit_vulnerability_finding_vex_assessment_atomic(scope.org,scope.actor,finding,'fixed',null,'Actual rollback-only fixed decision.','[]','M14 source proof',0,gen_random_uuid(),repeat('b',64));
 perform pg_temp.check('actual fixed submission waits for approval',r.outcome='submitted'and r.result#>>'{assessment,approvalState}'='awaiting_approval');
 assessment:=(r.result#>>'{assessment,id}')::uuid;v:=(r.result#>>'{assessment,version}')::int;
 set constraints all immediate;set constraints all deferred;
 select payload->>'triagedAt'into triage_at from public.vulnerability_finding_lifecycle_facts where finding_id=finding order by sequence desc limit 1;
 perform pg_temp.check('pending fixed triages but never remediates',(select payload->>'fixedAt'is null and payload->>'triagedAt'is not null from public.vulnerability_finding_lifecycle_facts where finding_id=finding order by sequence desc limit 1));
 select *into r from public.reject_vulnerability_finding_vex_assessment_atomic(scope.org,admin,finding,assessment,v,'Rejected rollback-only decision.',gen_random_uuid(),repeat('c',64));
 perform pg_temp.check('actual pending decision rejected',r.outcome='rejected');
 set constraints all immediate;set constraints all deferred;
 perform pg_temp.check('rejection keeps first triage and excludes remediation',(select payload->>'fixedAt'is null and payload->>'triagedAt'=triage_at from public.vulnerability_finding_lifecycle_facts where finding_id=finding order by sequence desc limit 1));
 select version into v from public.vulnerability_finding_assessments where id=assessment;
 select *into r from public.submit_vulnerability_finding_vex_assessment_atomic(scope.org,scope.actor,finding,'fixed',null,'Approved rollback-only remediation.','[]','M14 source proof',v,gen_random_uuid(),repeat('d',64));
 assessment:=(r.result#>>'{assessment,id}')::uuid;v:=(r.result#>>'{assessment,version}')::int;
 select *into r from public.approve_vulnerability_finding_vex_assessment_atomic(scope.org,admin,finding,assessment,v,'Approved source proof.',gen_random_uuid(),repeat('e',64));
 perform pg_temp.check('actual fixed assessment approved',r.outcome='approved');
 set constraints all immediate;set constraints all deferred;
 select payload->>'fixedAt'into fixed_at from public.vulnerability_finding_lifecycle_facts where finding_id=finding order by sequence desc limit 1;
 perform pg_temp.check('approved remediation is measured',fixed_at is not null);
 select version into v from public.vulnerability_finding_assessments where id=assessment;
 select *into r from public.submit_vulnerability_finding_vex_assessment_atomic(scope.org,scope.actor,finding,'affected',null,'Ordinary human reopening.','[]','M14 source proof',v,gen_random_uuid(),repeat('f',64));
 perform pg_temp.check('actual new affected assessment supersedes revision',r.outcome='submitted');
 set constraints all immediate;set constraints all deferred;
 perform pg_temp.check('ordinary supersession retains genuinely applied remediation',(select payload->>'fixedAt'=fixed_at and payload->>'triagedAt'=triage_at from public.vulnerability_finding_lifecycle_facts where finding_id=finding order by sequence desc limit 1));
 select version into policy_version from public.vulnerability_assessment_approval_policies where organization_id=scope.org and severity='unknown';
 select *into r from public.set_vulnerability_assessment_approval_policy_atomic(scope.org,scope.actor,'unknown',false,policy_version,gen_random_uuid(),repeat('a',64));
 insert into public.vulnerability_findings select(jsonb_populate_record(null::public.vulnerability_findings,to_jsonb(f)||jsonb_build_object('id',bulk_finding,'component_identity','m14-real-bulk-'||bulk_finding,'closed_at',null,'closure_reason',null,'superseded_at',null,'reevaluation_state','unchanged'))).*from public.vulnerability_findings f where id=scope.finding;
 set constraints all immediate;set constraints all deferred;
 select *into r from public.create_vulnerability_assessment_bulk_preview_atomic(scope.org,scope.actor,'bulk','selected_rows',jsonb_build_array(bulk_finding),'{}',null,null,null,'{"status":"fixed","detail":"Bulk remediation source proof.","changeReason":"M14 rollback-only proof","evidenceLinks":[]}',gen_random_uuid(),repeat('b',64));
 perform pg_temp.check('actual bulk remediation preview succeeds',r.outcome='previewed');
 operation:=(r.result#>>'{operation,id}')::uuid;v:=(r.result#>>'{operation,version}')::int;digest:=r.result#>>'{operation,snapshotDigest}';
 select *into r from public.execute_vulnerability_assessment_bulk_operation_atomic(scope.org,scope.actor,operation,v,digest,false,gen_random_uuid(),repeat('c',64));
 perform pg_temp.check('actual bulk remediation executes',r.outcome='executed');
 set constraints all immediate;set constraints all deferred;
 perform pg_temp.check('bulk effective fix records remediation and closure',(select payload->>'fixedAt'is not null and jsonb_array_length(payload->'closedEpisodes')=1 from public.vulnerability_finding_lifecycle_facts where finding_id=bulk_finding order by sequence desc limit 1));
 filters:=jsonb_build_object('from',current_date-1,'to',current_date,'timezone','UTC','bucket','day','productId',scope.product);
 before_dataset:=public.get_dashboard_trends(scope.org,scope.actor,filters,null);pin:=before_dataset->'snapshot';
 pin:=pin||jsonb_build_object('cutoffAt',public.m7_snapshot_timestamp_utc(clock_timestamp()+interval'1 second'),'snapshot',(pg_current_xact_id()::text::bigint+1)||':'||(pg_current_xact_id()::text::bigint+1)||':');
 before_dataset:=public.get_dashboard_trends(scope.org,scope.actor,filters,pin);
 select version into v from public.vulnerability_finding_assessment_bulk_operations where id=operation;
 select *into r from public.undo_vulnerability_assessment_bulk_operation_atomic(scope.org,scope.actor,operation,v,gen_random_uuid(),repeat('d',64));
 perform pg_temp.check('actual bulk undo succeeds',r.outcome='undone');
 set constraints all immediate;set constraints all deferred;
 perform pg_temp.check('explicit bulk reversal excludes remediation but preserves triage',(select payload->>'fixedAt'is null and payload->>'triagedAt'is not null from public.vulnerability_finding_lifecycle_facts where finding_id=bulk_finding order by sequence desc limit 1));
 perform pg_temp.check('explicit bulk reversal invalidates its closure episode',(select jsonb_array_length(payload->'closedEpisodes')=0 from public.vulnerability_finding_lifecycle_facts where finding_id=bulk_finding order by sequence desc limit 1));
 perform pg_temp.check('old pin preserves pre-reversal applied decisions',public.get_dashboard_trends(scope.org,scope.actor,filters,pin)=before_dataset);
 pin:=pin||jsonb_build_object('maxFindingSequence',(select max(sequence)::text from public.vulnerability_finding_lifecycle_facts where organization_id=scope.org));
 after_dataset:=public.get_dashboard_trends(scope.org,scope.actor,filters,pin);
 perform pg_temp.check('corrected closure cohort excludes exactly reversed decision',(select sum((b->>'closed')::int)from jsonb_array_elements(after_dataset#>'{result,series,activity,buckets}')b)=(select sum((b->>'closed')::int)-1 from jsonb_array_elements(before_dataset#>'{result,series,activity,buckets}')b));
 page:=public.get_dashboard_trend_sources(scope.org,scope.actor,filters||'{"metric":"activity","offset":0,"limit":100}',pin);
 perform pg_temp.check('corrected closure table source parity',(select count(*)from jsonb_array_elements(page#>'{result,items}')i where i->>'factKind'like'closed:%')=(select sum((b->>'closed')::int)from jsonb_array_elements(after_dataset#>'{result,series,activity,buckets}')b));
end$$;
rollback;
