-- Deterministic source capture lock ordering and independently authorized pinned source pages.
create or replace function public.m14_02_capture_trigger()returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
declare row_data jsonb:=coalesce(to_jsonb(new),to_jsonb(old)); org uuid:=(row_data->>'organization_id')::uuid; rid uuid; fid uuid;
begin
 insert into public.vulnerability_finding_lifecycle_facts(organization_id,fact_kind,payload,provenance)values(org,'baseline',jsonb_build_object('epoch',gen_random_uuid()),'capture_started')on conflict(organization_id)where finding_id is null do nothing;
 insert into public.sbom_release_coverage_facts(organization_id,fact_kind,payload,provenance)values(org,'baseline',jsonb_build_object('epoch',gen_random_uuid()),'capture_started')on conflict(organization_id)where release_id is null do nothing;
 if tg_table_name='vulnerability_findings'then fid:=(row_data->>'id')::uuid;
 elsif tg_table_name in ('vulnerability_finding_assessments','vulnerability_finding_assessment_bulk_operation_targets')then fid:=(row_data->>'finding_id')::uuid;
 elsif tg_table_name='vulnerability_finding_assessment_history_events'then select finding_id into fid from public.vulnerability_finding_assessments where organization_id=org and id=(row_data->>'assessment_id')::uuid;end if;
 if fid is not null then perform public.m14_02_capture_finding(org,fid);return null;end if;
 if tg_table_name='products'then for rid in select id from public.product_releases where organization_id=org and product_id=(row_data->>'id')::uuid order by id loop perform public.m14_02_capture_release(org,rid);end loop;
 elsif tg_table_name='sbom_documents'then for rid in select distinct release_id from public.sbom_document_sources where organization_id=org and document_id=(row_data->>'id')::uuid order by release_id loop perform public.m14_02_capture_release(org,rid);end loop;
 else rid:=case when tg_table_name='product_releases'then(row_data->>'id')::uuid else(row_data->>'release_id')::uuid end;if rid is not null then perform public.m14_02_capture_release(org,rid);end if;end if;return null;
end$$;
create or replace function public.get_dashboard_trend_sources(p_organization_id uuid,p_actor_user_id uuid,p_filters jsonb,p_snapshot jsonb default null)returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$
declare baseline timestamptz; expected_revision text:=p_filters->>'datasetRevision';access jsonb:=p_filters->'sourceAccess';base_filters jsonb:=p_filters-array['metric','offset','limit','datasetRevision'];dataset jsonb;pin jsonb;metric text:=p_filters->>'metric';product uuid:=(p_filters->>'productId')::uuid;off integer:=coalesce((p_filters->>'offset')::integer,0);lim integer:=coalesce((p_filters->>'limit')::integer,50);rows jsonb;n integer;from_at timestamptz:=(p_filters->>'from')::date::timestamp at time zone(p_filters->>'timezone');to_at timestamptz:=((p_filters->>'to')::date+1)::timestamp at time zone(p_filters->>'timezone');
begin
 if metric not in('activity','triage','remediation','sbomCoverage','readiness')or off<0 or lim not between 1 and 100 then return jsonb_build_object('outcome','invalid_request');end if;
 if expected_revision is not null and p_snapshot is not null then
 -- Revision comes only from the API's authenticated encrypted dataset position.
 -- Authorize source visibility independently before any source rows are read.
 if access->>'products'='false'or not public.m14_actor_can(p_organization_id,p_actor_user_id,'can_view_dashboards')or not public.m14_actor_can(p_organization_id,p_actor_user_id,'can_view_products')then return jsonb_build_object('outcome','not_found');end if;
 if product is not null and not exists(select 1 from public.products where organization_id=p_organization_id and id=product)then return jsonb_build_object('outcome','not_found');end if;
 if (access->>(case when metric in('activity','triage','remediation')then'findings'else metric end))='false'or metric in('activity','triage','remediation')and not public.m14_actor_can(p_organization_id,p_actor_user_id,'can_view_findings')or metric='sbomCoverage'and not public.m14_actor_can(p_organization_id,p_actor_user_id,'can_view_sboms')or metric='readiness'and not public.m14_actor_can(p_organization_id,p_actor_user_id,'can_view_technical_files')then return jsonb_build_object('outcome','forbidden');end if;
 if metric in('triage','remediation','readiness')and product is null then return jsonb_build_object('outcome','forbidden');end if;
 if p_snapshot->>'epoch'is distinct from(select payload->>'epoch'from public.vulnerability_finding_lifecycle_facts where organization_id=p_organization_id and finding_id is null)then return jsonb_build_object('outcome','conflict');end if;
 if jsonb_typeof(base_filters)<>'object'or (base_filters->>'to')::date<(base_filters->>'from')::date or (base_filters->>'to')::date-(base_filters->>'from')::date>365 or base_filters->>'bucket'not in('day','week','month')or not exists(select 1 from pg_timezone_names where name=base_filters->>'timezone')or (base_filters->>'to')::date>(statement_timestamp()at time zone(base_filters->>'timezone'))::date then return jsonb_build_object('outcome','invalid_request');end if;
 select effective_at into baseline from public.vulnerability_finding_lifecycle_facts where organization_id=p_organization_id and finding_id is null and sequence<=(p_snapshot->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(recorded_transaction_id,(p_snapshot->>'snapshot')::pg_snapshot);
 if metric<>'readiness'and baseline is null then return jsonb_build_object('outcome','forbidden');end if;
 if metric='readiness'and exists(select 1 from public.technical_file_snapshots s where s.organization_id=p_organization_id and s.product_id=product and s.trend_sequence<=(p_snapshot->>'maxSnapshotSequence')::bigint and pg_visible_in_snapshot(s.recorded_transaction_id,(p_snapshot->>'snapshot')::pg_snapshot)and s.created_at>=from_at and s.created_at<least(to_at,(p_snapshot->>'cutoffAt')::timestamptz)and not public.m14_02_snapshot_can(p_organization_id,p_actor_user_id,s.id))then return jsonb_build_object('outcome','forbidden');end if;
 dataset:=jsonb_build_object('snapshot',p_snapshot,'result',jsonb_build_object('datasetRevision',expected_revision,'baselineAt',public.m7_snapshot_timestamp_utc(baseline)));
 else
 dataset:=public.get_dashboard_trends(p_organization_id,p_actor_user_id,base_filters,p_snapshot);if dataset->>'outcome'<>'found'then return dataset;end if;
 if dataset#>>array['result','series',metric,'state']<>'available'then return jsonb_build_object('outcome','forbidden');end if;
 end if;pin:=dataset->'snapshot';to_at:=least(to_at,(pin->>'cutoffAt')::timestamptz);
 with finding_facts as materialized(select f.*,p.payload previous from public.vulnerability_finding_lifecycle_facts f left join public.vulnerability_finding_lifecycle_facts p on p.organization_id=p_organization_id and p.sequence=f.previous_sequence where f.organization_id=p_organization_id and f.finding_id is not null and(product is null or f.product_id=product)and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)),
 finding_latest as(select distinct on(finding_id)*from finding_facts order by finding_id,sequence desc),
 finding_sources as(select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,case when metric='triage'then(f.payload->>'triagedAt')::timestamptz when metric='remediation'then(f.payload->>'fixedAt')::timestamptz else f.effective_at end effective_at,case when metric='triage'then'first_triage'when metric='remediation'then'applied_remediation'else'observation'end kind from finding_latest f where metric in('triage','remediation')and extract(epoch from(case metric when'triage'then(f.payload->>'triagedAt')::timestamptz else(f.payload->>'fixedAt')::timestamptz end-(f.payload->>'firstDetectedAt')::timestamptz))>=0
 union all select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,(l.payload->>'firstDetectedAt')::timestamptz,'opened'from finding_facts f join finding_latest l using(finding_id)where metric='activity'and f.fact_kind='observation'and f.previous_sequence is null
 union all select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,f.effective_at,'reopened'from finding_facts f where metric='activity'and f.fact_kind='observation'and f.previous->>'open'='false'and f.payload->>'open'='true'
 union all select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,(e->>'at')::timestamptz,'closed:'||(e->>'key')from finding_latest f cross join lateral jsonb_array_elements(coalesce(f.payload->'closedEpisodes','[]'))e where metric='activity' ),
 all_sources as(select 'finding-'||f.sequence||'-'||f.kind id,f.product_id,f.finding_id::text source_id,'finding'::text source_type,f.kind,f.effective_at,f.recorded_at,f.provenance,'/findings?productId='||f.product_id href from finding_sources f where f.effective_at>=greatest(from_at,(dataset#>>'{result,baselineAt}')::timestamptz)and f.effective_at<to_at
 union all select 'coverage-'||f.sequence,f.product_id,f.release_id::text,'release','coverage_observation',f.effective_at,f.recorded_at,f.provenance,'/products/'||f.product_id from public.sbom_release_coverage_facts f where metric='sbomCoverage'and f.organization_id=p_organization_id and f.release_id is not null and(product is null or f.product_id=product)and f.sequence<=(pin->>'maxCoverageSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)and f.effective_at<to_at
 union all select 'snapshot-'||s.id,s.product_id,s.id::text,'technical_file_snapshot','readiness_at_snapshot',s.created_at,s.created_at,'immutable_snapshot:'||s.payload_sha256,'/products/'||s.product_id||'/technical-file'from public.technical_file_snapshots s where metric='readiness'and s.organization_id=p_organization_id and s.product_id=product and s.trend_sequence<=(pin->>'maxSnapshotSequence')::bigint and pg_visible_in_snapshot(s.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)and s.created_at>=from_at and s.created_at<to_at),
 page as(select *from all_sources order by effective_at,id offset off limit(lim+1)),
 numbered as(select *,row_number()over(order by effective_at,id)ord from page)
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'productId',product_id,'sourceId',source_id,'sourceType',source_type,'factKind',kind,'effectiveAt',public.m7_snapshot_timestamp_utc(effective_at),'recordedAt',public.m7_snapshot_timestamp_utc(recorded_at),'provenance',provenance,'href',href)order by ord)filter(where ord<=lim),'[]'),count(*)into rows,n from numbered;
 return jsonb_build_object('outcome','found','snapshot',pin,'result',jsonb_build_object('items',rows,'nextOffset',case when n>lim then off+lim end,'datasetRevision',dataset#>>'{result,datasetRevision}'));
end$$;
notify pgrst,'reload schema';
