-- Preserve NULL and unknown legacy entity attribution outside the SIEM receipt projector.
create or replace function public.m13_05_guard_receipt() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
declare v jsonb:=new.changes; begin
 if new.entity_type is distinct from 'audit_siem' then return new; end if;
 if new.organization_id is not null or new.event_scope<>'security' or new.action not in ('audit.siem.create','audit.siem.update','audit.siem.credentials','audit.siem.revoke_credentials','audit.siem.test','audit.siem.test_prepare','audit.siem.enable','audit.siem.disable','audit.siem.list','audit.siem.read','audit.siem.deliveries','audit.siem.delivery','audit.siem.replay_preview','audit.siem.replay','audit.siem.catalogue','audit.siem.denial','audit.siem.paused','audit.siem.staged','audit.siem.lease_expired','audit.siem.scope_unavailable','audit.siem.retry_exhausted','audit.siem.claimed','audit.siem.completed','audit.siem.key_rewrapped') or v->>'organizationId' is null or v->>'organizationId' !~* '^[a-f0-9-]{36}$' or v->>'operationDigest' is null or v->>'operationDigest' !~ '^[a-f0-9]{64}$' then raise exception 'invalid SIEM receipt' using errcode='22023'; end if;
 new.after_redacted:=jsonb_build_object('organizationId',v->>'organizationId','operationDigest',v->>'operationDigest');
 if v ? 'result' then
  if jsonb_typeof(v->'result')<>'object' or exists(select 1 from jsonb_object_keys(v->'result') k where k not in ('id','version','status','deliveryId','previewDigest','destinationVersion','recipientChanged','credentialRevision','cursorDate','cursorId','previewExpiresAt','testState','safeFailureCode')) then raise exception 'invalid SIEM result receipt' using errcode='22023'; end if;
  if v->'result' ? 'previewDigest' and v->'result'->>'previewDigest' !~ '^[a-f0-9]{64}$' or v->'result' ? 'cursorId' and v->'result'->>'cursorId' !~* '^[a-f0-9-]{36}$' or v->'result' ? 'testState' and v->'result'->>'testState' not in ('accepted','sent_unacknowledged','failed') or v->'result' ? 'safeFailureCode' and v->'result'->>'safeFailureCode' !~ '^[a-z][a-z0-9_]{0,79}$' then raise exception 'invalid SIEM receipt values' using errcode='22023'; end if;
  if v->'result' ? 'cursorDate' and not isfinite((v->'result'->>'cursorDate')::timestamptz) or v->'result' ? 'previewExpiresAt' and not isfinite((v->'result'->>'previewExpiresAt')::timestamptz) or v->'result' ? 'destinationVersion' and v->'result'->>'destinationVersion' !~ '^[0-9]{1,9}$' or v->'result' ? 'credentialRevision' and v->'result'->>'credentialRevision' !~ '^[0-9]{1,9}$' or v->'result' ? 'recipientChanged' and jsonb_typeof(v->'result'->'recipientChanged')<>'boolean' then raise exception 'invalid SIEM receipt types' using errcode='22023';end if;
  if (v->'result' ? 'id' and v->'result'->>'id' !~* '^[a-f0-9-]{36}$') or (v->'result' ? 'deliveryId' and v->'result'->>'deliveryId' !~* '^[a-f0-9-]{36}$') or (v->'result' ? 'version' and v->'result'->>'version' !~ '^[0-9]{1,9}$') or (v->'result' ? 'status' and v->'result'->>'status' not in ('draft','enabled','disabled','paused')) or pg_column_size(v->'result')>1024 then raise exception 'invalid SIEM receipt values' using errcode='22023'; end if;
  new.after_redacted:=new.after_redacted||jsonb_build_object('result',v->'result');
 end if;
 if v->>'keyId' is not null then if v->>'keyId' !~ '^[A-Za-z0-9_.-]{1,80}$' then raise exception 'invalid key id' using errcode='22023'; end if; new.after_redacted:=new.after_redacted||jsonb_build_object('keyId',v->>'keyId'); end if;
 new.before_redacted:=null;new.reason:=null;new.changes:=null; return new;
end $$;
