-- Reduce authorized facts once per source/cohort, before joining bounded calendar buckets.
create or replace function public.get_dashboard_trends(p_organization_id uuid,p_actor_user_id uuid,p_filters jsonb,p_snapshot jsonb default null)returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$
declare org uuid:=p_organization_id;actor uuid:=p_actor_user_id;product uuid:=(p_filters->>'productId')::uuid;from_date date:=(p_filters->>'from')::date;to_date date:=(p_filters->>'to')::date;zone text:=p_filters->>'timezone';bucket text:=p_filters->>'bucket';pin jsonb;baseline timestamptz;snap pg_snapshot;fm bigint;cm bigint;sm bigint;metric text;series jsonb:='{}'::jsonb;points jsonb;state text;reason text;unit text;revision text;access jsonb:=p_filters->'sourceAccess';now_at timestamptz:=statement_timestamp();
begin
 p_filters:=p_filters-'sourceAccess';
 if access->>'products'='false'or not public.m14_actor_can(org,actor,'can_view_dashboards')or not public.m14_actor_can(org,actor,'can_view_products')then return jsonb_build_object('outcome','not_found');end if;
 if product is not null and not exists(select 1 from public.products where organization_id=org and id=product)then return jsonb_build_object('outcome','not_found');end if;
 if from_date is null or to_date is null or to_date<from_date or to_date-from_date>365 or bucket not in ('day','week','month')or not exists(select 1 from pg_timezone_names where name=zone)then return jsonb_build_object('outcome','invalid_request');end if;
 if to_date>(now_at at time zone zone)::date then return jsonb_build_object('outcome','invalid_request');end if;
 if p_snapshot is null then
 pin:=jsonb_build_object('cutoffAt',public.m7_snapshot_timestamp_utc(now_at),'snapshot',pg_current_snapshot()::text,'maxFindingSequence',coalesce((select max(sequence)from public.vulnerability_finding_lifecycle_facts where organization_id=org),0)::text,'maxCoverageSequence',coalesce((select max(sequence)from public.sbom_release_coverage_facts where organization_id=org),0)::text,'maxSnapshotSequence',coalesce((select max(trend_sequence)from public.technical_file_snapshots where organization_id=org),0)::text,'epoch',(select payload->>'epoch'from public.vulnerability_finding_lifecycle_facts where organization_id=org and finding_id is null));
 else pin:=p_snapshot;if pin->>'epoch' is distinct from(select payload->>'epoch'from public.vulnerability_finding_lifecycle_facts where organization_id=org and finding_id is null)then return jsonb_build_object('outcome','conflict');end if;end if;
 now_at:=(pin->>'cutoffAt')::timestamptz;
 snap:=(pin->>'snapshot')::pg_snapshot;fm:=(pin->>'maxFindingSequence')::bigint;cm:=(pin->>'maxCoverageSequence')::bigint;sm:=(pin->>'maxSnapshotSequence')::bigint;
 select effective_at into baseline from public.vulnerability_finding_lifecycle_facts where organization_id=org and finding_id is null and sequence<=fm and pg_visible_in_snapshot(recorded_transaction_id,snap);

 foreach metric in array array['activity','triage','remediation','sbomCoverage','readiness']loop
 state:='available';reason:=null;unit:=case metric when'activity'then'count'when'triage'then'hours'when'remediation'then'days'else'percent'end;
 if (access->>(case when metric in('activity','triage','remediation')then'findings'else metric end))='false'or metric in ('activity','triage','remediation')and not public.m14_actor_can(org,actor,'can_view_findings')or metric='sbomCoverage'and not public.m14_actor_can(org,actor,'can_view_sboms')or metric='readiness'and not public.m14_actor_can(org,actor,'can_view_technical_files')then state:='restricted';reason:='source_permission_required';
 elsif metric in ('triage','remediation','readiness')and product is null then state:='unavailable';reason:='select_product';
 elsif metric<>'readiness'and baseline is null then state:='unavailable';reason:='history_unavailable';
 elsif metric='readiness'and exists(select 1 from public.technical_file_snapshots s where metric='readiness'and s.organization_id=org and s.product_id=product and s.trend_sequence<=sm and pg_visible_in_snapshot(s.recorded_transaction_id,snap)and s.created_at>=from_date::timestamp at time zone zone and s.created_at<(to_date+1)::timestamp at time zone zone and not public.m14_02_snapshot_can(org,actor,s.id))then state:='restricted';reason:='snapshot_source_permission_required';end if;
 if state<>'available'then points:='[]';else
 with calendar_boundaries as(select greatest(from_date::timestamp,d)::timestamp at time zone zone calendar_starts,least((to_date+1)::timestamp,d+case bucket when'day'then interval'1 day'when'week'then interval'1 week'else interval'1 month'end)::timestamp at time zone zone calendar_ends from generate_series(date_trunc(bucket,from_date::timestamp),to_date::timestamp,case bucket when'day'then interval'1 day'when'week'then interval'1 week'else interval'1 month'end)d),
 boundaries as(select case when metric in('activity','sbomCoverage')and calendar_ends>baseline then greatest(calendar_starts,baseline)else calendar_starts end starts,least(calendar_ends,now_at)ends,calendar_starts,calendar_ends from calendar_boundaries where calendar_starts<now_at),
 facts as materialized(select f.*,prev.payload previous from public.vulnerability_finding_lifecycle_facts f left join public.vulnerability_finding_lifecycle_facts prev on prev.organization_id=org and prev.sequence=f.previous_sequence where metric in('activity','triage','remediation')and f.organization_id=org and f.finding_id is not null and(product is null or f.product_id=product)and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)),
 latest as(select distinct on(finding_id)*from facts order by finding_id,sequence desc),
 events as(select f.finding_id,'opened'kind,(l.payload->>'firstDetectedAt')::timestamptz at from facts f join latest l using(finding_id)where f.previous_sequence is null and f.fact_kind='observation'
 union all select l.finding_id,'closed',(e->>'at')::timestamptz from latest l cross join lateral jsonb_array_elements(coalesce(l.payload->'closedEpisodes','[]'))e
 union all select finding_id,'reopened',effective_at from facts where fact_kind='observation'and previous->>'open'='false'and payload->>'open'='true'),
 durations as(select finding_id,case metric when'triage'then(payload->>'triagedAt')::timestamptz else(payload->>'fixedAt')::timestamptz end at,extract(epoch from(case metric when'triage'then(payload->>'triagedAt')::timestamptz else(payload->>'fixedAt')::timestamptz end-(payload->>'firstDetectedAt')::timestamptz))/case metric when'triage'then 3600.0 else 86400.0 end value from latest),
 event_totals as(select date_trunc(bucket,e.at at time zone zone)bucket_key,count(*)filter(where kind='opened')opened,count(*)filter(where kind='closed')closed,count(*)filter(where kind='reopened')reopened from events e where metric='activity'and e.at>=greatest(from_date::timestamp at time zone zone,baseline)and e.at<now_at group by 1),
 duration_totals as(select date_trunc(bucket,d.at at time zone zone)bucket_key,avg(value)filter(where value>=0 and d.at>=baseline)duration_mean,count(*)filter(where value>=0 and d.at>=baseline)sample_count,count(*)filter(where value<0)excluded_count from durations d where metric in('triage','remediation')and d.at>=from_date::timestamp at time zone zone and d.at<now_at group by 1),
 coverage_deltas as materialized(select f.effective_at,(f.payload->>'eligible')::boolean::int-coalesce((prev.payload->>'eligible')::boolean::int,0)eligible_delta,((f.payload->>'eligible')::boolean and(f.payload->>'covered')::boolean)::int-coalesce(((prev.payload->>'eligible')::boolean and(prev.payload->>'covered')::boolean)::int,0)covered_delta from public.sbom_release_coverage_facts f left join public.sbom_release_coverage_facts prev on prev.organization_id=org and prev.sequence=f.previous_sequence where metric='sbomCoverage'and f.organization_id=org and f.release_id is not null and(product is null or f.product_id=product)and f.sequence<=cm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)and f.effective_at<now_at),
 coverage_totals as(select date_trunc(bucket,effective_at at time zone zone)bucket_key,sum(eligible_delta)eligible_delta,sum(covered_delta)covered_delta from coverage_deltas group by 1),
 bucket_values as(select b.*,
 coalesce(et.opened,0)opened,coalesce(et.closed,0)closed,coalesce(et.reopened,0)reopened,
 dt.duration_mean,coalesce(dt.sample_count,0)sample_count,coalesce(dt.excluded_count,0)excluded_count,
 coalesce((select sum(covered_delta)from coverage_totals ct where ct.bucket_key<=date_trunc(bucket,b.starts at time zone zone)),0)covered,
 coalesce((select sum(eligible_delta)from coverage_totals ct where ct.bucket_key<=date_trunc(bucket,b.starts at time zone zone)),0)eligible,
 (select s.payload from public.technical_file_snapshots s where metric='readiness'and s.organization_id=org and s.product_id=product and s.trend_sequence<=sm and pg_visible_in_snapshot(s.recorded_transaction_id,snap)and s.created_at>=b.starts and s.created_at<b.ends order by s.created_at desc,s.trend_sequence desc limit 1)readiness_payload,
 (select count(*)from public.technical_file_snapshots s where metric='readiness'and s.organization_id=org and s.product_id=product and s.trend_sequence<=sm and pg_visible_in_snapshot(s.recorded_transaction_id,snap)and s.created_at>=b.starts and s.created_at<b.ends)snapshot_count
 from boundaries b left join event_totals et on et.bucket_key=date_trunc(bucket,b.starts at time zone zone)left join duration_totals dt on dt.bucket_key=date_trunc(bucket,b.starts at time zone zone)),
 readiness_values as(select v.*,(select count(*)from jsonb_array_elements(coalesce(v.readiness_payload#>'{technicalFile,sections}','[]'))s where s->>'applicability'='applicable')applicable,
 (select count(*)from jsonb_array_elements(coalesce(v.readiness_payload#>'{technicalFile,sections}','[]'))s join jsonb_array_elements(coalesce(v.readiness_payload#>'{readiness,sections}','[]'))r on r->>'sectionKey'=s->>'key'where s->>'applicability'='applicable'and r->>'status'='complete')complete from bucket_values v)
 select coalesce(jsonb_agg(jsonb_build_object('partial',starts<>calendar_starts or ends<>calendar_ends or date_trunc(bucket,calendar_starts at time zone zone)<>calendar_starts at time zone zone,'start',public.m7_snapshot_timestamp_utc(starts),'end',public.m7_snapshot_timestamp_utc(ends),'opened',case when metric='activity'and starts>=baseline then opened end,'closed',case when metric='activity'and starts>=baseline then closed end,'reopened',case when metric='activity'and starts>=baseline then reopened end,'value',case when metric in('triage','remediation')and ends>baseline then duration_mean when metric='sbomCoverage'and starts>=baseline and eligible>0 then round(100.0*covered/eligible,2)when metric='readiness'and applicable>0 then round(100.0*complete/applicable,2)end,'sampleCount',case when metric in('triage','remediation')then sample_count when metric='readiness'then snapshot_count else 0 end,'excludedCount',case when metric in('triage','remediation')then excluded_count else 0 end,'numerator',case when metric='sbomCoverage'and starts>=baseline then covered when metric='readiness'and readiness_payload is not null then complete end,'denominator',case when metric='sbomCoverage'and starts>=baseline then eligible when metric='readiness'and readiness_payload is not null then applicable end,'sourceCount',case when metric='activity'and starts>=baseline then opened+closed+reopened when metric in('triage','remediation')then sample_count+excluded_count when metric='sbomCoverage'and starts>=baseline then eligible when metric='readiness'then snapshot_count else 0 end)order by starts),'[]')into points from readiness_values;
 end if;
 series:=series||jsonb_build_object(metric,jsonb_build_object('state',state,'reason',reason,'unit',unit,'baselineAt',case when metric<>'readiness'then public.m7_snapshot_timestamp_utc(baseline)end,'buckets',points));
 end loop;
 revision:=encode(extensions.digest(jsonb_build_object('series',series,'filters',p_filters,'policyVersion','m14-02-v1')::text,'sha256'),'hex');
 return jsonb_build_object('outcome','found','snapshot',pin,'result',jsonb_build_object('organizationId',org,'filters',p_filters,'policyVersion','m14-02-v1','datasetRevision',revision,'generatedAt',public.m7_snapshot_timestamp_utc(now_at),'baselineAt',public.m7_snapshot_timestamp_utc(baseline),'series',series));
end$$;
notify pgrst,'reload schema';
