-- M8-02: append-only evidence replacements and application-mediated delivery.
-- Object storage remains private.  The opaque bearer token is generated by the
-- API and only its SHA-256 digest is persisted here.

update storage.buckets
set public = false,
    file_size_limit = 52428800,
    allowed_mime_types = array[
      'application/pdf',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'text/csv', 'text/plain', 'image/jpeg', 'image/png', 'image/webp'
    ]
where id = 'evidence-documents';

alter table public.evidence_document_versions
  drop constraint evidence_document_versions_detected_media_type_check;
alter table public.evidence_document_versions
  add constraint evidence_document_versions_detected_media_type_check
  check (detected_media_type is null or detected_media_type in (
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'text/csv', 'text/plain', 'image/jpeg', 'image/png', 'image/webp'
  ));

create or replace function public.finalize_evidence_document_upload_atomic(
  p_organization_id uuid,p_actor_user_id uuid,p_version_id uuid,
  p_actual_size_bytes bigint,p_detected_media_type text,p_original_sha256 text,
  p_idempotency_key uuid,p_request_digest text
) returns table(outcome text,result jsonb)
language plpgsql security definer set search_path=public,pg_temp as $$
declare v public.evidence_document_versions%rowtype;
begin
 if p_idempotency_key is null or p_request_digest !~ '^[a-f0-9]{64}$'
   or not public.m8_evidence_actor_active(p_organization_id,p_actor_user_id) then
   return query select 'invalid_request',null::jsonb; return;
 end if;
 select * into v from public.evidence_document_versions
 where organization_id=p_organization_id and id=p_version_id for update;
 if not found or v.uploader_user_id<>p_actor_user_id then
   return query select 'not_found',null::jsonb; return;
 end if;
 if v.finalize_idempotency_key is not null then
   return query select case when v.finalize_idempotency_key=p_idempotency_key
     and v.finalize_request_digest=p_request_digest then 'replayed' else 'idempotency_conflict' end,
     jsonb_build_object('versionId',v.id,'state',v.processing_state); return;
 end if;
 if v.processing_state<>'uploading' or v.upload_expires_at<clock_timestamp()
   or p_actual_size_bytes is null or p_detected_media_type is null or p_original_sha256 is null
   or p_actual_size_bytes not between 1 and 52428800 or p_actual_size_bytes<>v.declared_size_bytes
   or p_detected_media_type not in (
     'application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document',
     'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
     'application/vnd.openxmlformats-officedocument.presentationml.presentation',
     'text/csv','text/plain','image/jpeg','image/png','image/webp'
   ) or p_original_sha256 !~ '^[a-f0-9]{64}$' then
   update public.evidence_document_versions set processing_state='failed',
     failure_code=case when v.upload_expires_at<clock_timestamp() then 'upload_expired' else 'integrity_mismatch' end,
     finalize_idempotency_key=p_idempotency_key,finalize_request_digest=p_request_digest,
     actual_size_bytes=coalesce(p_actual_size_bytes,1),detected_media_type=coalesce(p_detected_media_type,'text/plain'),
     original_sha256=coalesce(p_original_sha256,repeat('0',64)),finalized_at=clock_timestamp()
   where organization_id=p_organization_id and id=v.id;
   return query select 'failed',jsonb_build_object('versionId',v.id,'state','failed'); return;
 end if;
 update public.evidence_document_versions set processing_state='scan_pending',actual_size_bytes=p_actual_size_bytes,
   detected_media_type=p_detected_media_type,original_sha256=p_original_sha256,finalized_at=clock_timestamp(),
   finalize_idempotency_key=p_idempotency_key,finalize_request_digest=p_request_digest
 where organization_id=p_organization_id and id=v.id;
 insert into public.evidence_document_scan_jobs(organization_id,version_id) values(p_organization_id,v.id);
 insert into public.audit_logs(organization_id,user_id,action,entity_type,entity_id,changes)
 values(p_organization_id,p_actor_user_id,'evidence.upload_completed','evidence_document_version',v.id::text,
   jsonb_build_object('idempotencyKey',p_idempotency_key,'sha256',p_original_sha256));
 return query select 'scan_pending',jsonb_build_object('versionId',v.id,'state','scan_pending');
end $$;

alter table public.evidence_document_notification_outbox
  drop constraint evidence_document_notification_outbox_event_type_check;
alter table public.evidence_document_notification_outbox
  add constraint evidence_document_notification_outbox_event_type_check
  check (event_type in ('evidence_quarantined', 'evidence_integrity_failure'));

create table public.evidence_document_access_grants (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  actor_user_id uuid not null references public.users(id) on delete restrict,
  document_id uuid not null,
  version_id uuid not null,
  product_id uuid not null,
  access_mode text not null check (access_mode in ('preview', 'download', 'export')),
  purpose text check (purpose is null or (purpose = btrim(purpose) and char_length(purpose) between 1 and 500 and purpose !~ '[[:cntrl:]]')),
  token_sha256 text not null check (token_sha256 ~ '^[a-f0-9]{64}$'),
  request_correlation_id uuid not null,
  issued_at timestamptz not null default clock_timestamp(),
  expires_at timestamptz not null,
  first_redeemed_at timestamptz,
  last_redeemed_at timestamptz,
  redemption_count integer not null default 0 check (redemption_count >= 0),
  first_range_start bigint,
  first_range_end bigint,
  last_range_start bigint,
  last_range_end bigint,
  terminal_outcome text check (terminal_outcome is null or terminal_outcome in ('delivered', 'expired', 'integrity_failed')),
  unique (organization_id, id),
  unique (token_sha256),
  foreign key (organization_id, document_id) references public.evidence_documents(organization_id, id) on delete restrict,
  foreign key (organization_id, version_id) references public.evidence_document_versions(organization_id, id) on delete restrict,
  foreign key (organization_id, product_id) references public.products(organization_id, id) on delete restrict,
  check (expires_at > issued_at),
  check ((first_range_start is null and first_range_end is null) or (first_range_start >= 0 and first_range_end >= first_range_start)),
  check ((last_range_start is null and last_range_end is null) or (last_range_start >= 0 and last_range_end >= last_range_start))
);

create index evidence_access_grants_redeem_idx
  on public.evidence_document_access_grants(organization_id, actor_user_id, expires_at, id);
create index evidence_access_grants_version_idx
  on public.evidence_document_access_grants(organization_id, version_id, issued_at desc);

create or replace function public.list_evidence_document_versions(
  p_organization_id uuid, p_actor_user_id uuid, p_document_id uuid
) returns jsonb
language sql stable security definer set search_path=public,pg_temp as $$
  select case when not public.m8_evidence_actor_active(p_organization_id, p_actor_user_id)
    or not exists (select 1 from public.evidence_documents d where d.organization_id = p_organization_id and d.id = p_document_id)
    then null
    else jsonb_build_object('documentId', p_document_id, 'items', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', v.id, 'documentId', v.document_id, 'organizationId', v.organization_id,
        'versionNumber', v.version_number, 'title', v.title, 'documentClass', v.document_class,
        'ownerUserId', v.owner_user_id, 'productIds', coalesce((
          select jsonb_agg(vp.product_id order by vp.product_id)
          from public.evidence_document_version_products vp
          where vp.organization_id = v.organization_id and vp.version_id = v.id
        ), '[]'::jsonb),
        'validFrom', case when v.validity_starts_on is null then null else to_char(v.validity_starts_on::timestamp at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') end,
        'validUntil', case when v.validity_ends_on is null then null else to_char(v.validity_ends_on::timestamp at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') end,
        'fileName', v.original_filename, 'mediaType', v.detected_media_type,
        'byteSize', v.actual_size_bytes, 'sha256', v.original_sha256,
        'status', v.processing_state, 'failureCode', v.failure_code,
        'uploadExpiresAt', case when v.processing_state = 'uploading' then to_char(v.upload_expires_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') end,
        'uploadedByUserId', v.uploader_user_id,
        'completedAt', case when v.finalized_at is null then null else to_char(v.finalized_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') end,
        'createdAt', to_char(v.created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
      ) order by v.version_number desc, v.id desc)
      from public.evidence_document_versions v
      where v.organization_id = p_organization_id and v.document_id = p_document_id
    ), '[]'::jsonb))
  end
$$;

create or replace function public.reserve_evidence_document_replacement_atomic(
  p_organization_id uuid, p_actor_user_id uuid, p_document_id uuid,
  p_expected_current_version_id uuid, p_title text, p_document_class text,
  p_owner_user_id uuid, p_product_ids uuid[], p_validity_starts_on date,
  p_validity_ends_on date, p_original_filename text, p_declared_size_bytes bigint,
  p_object_key text, p_upload_expires_at timestamptz, p_idempotency_key uuid,
  p_request_digest text
) returns table(outcome text, result jsonb)
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_existing public.evidence_document_versions%rowtype;
declare v_document public.evidence_documents%rowtype;
declare v_version_id uuid;
declare v_version_number integer;
begin
  if p_idempotency_key is null or p_request_digest !~ '^[a-f0-9]{64}$'
    or not public.m8_evidence_actor_active(p_organization_id, p_actor_user_id)
    or not public.m8_evidence_actor_active(p_organization_id, p_owner_user_id)
    or p_document_id is null or p_expected_current_version_id is null
    or p_document_class is null or public.m8_evidence_retention_class(p_document_class) is null
    or p_title is null or p_title <> btrim(p_title) or char_length(p_title) not between 1 and 500
    or p_original_filename is null or p_original_filename <> btrim(p_original_filename)
    or char_length(p_original_filename) not between 1 and 255 or p_original_filename ~ '[[:cntrl:]/\\]'
    or p_declared_size_bytes not between 1 and 52428800
    or p_object_key is null or p_object_key <> btrim(p_object_key) or char_length(p_object_key) not between 1 and 1000
    or p_object_key ~ '[[:cntrl:] ]'
    or p_upload_expires_at is null or p_upload_expires_at not between clock_timestamp() + interval '1 minute' and clock_timestamp() + interval '30 minutes'
    or cardinality(p_product_ids) < 1
    or (p_validity_ends_on is not null and p_validity_starts_on is not null and p_validity_ends_on < p_validity_starts_on)
  then
    return query select 'invalid_request'::text, null::jsonb;
    return;
  end if;

  select * into v_existing from public.evidence_document_versions
  where organization_id = p_organization_id and uploader_user_id = p_actor_user_id
    and initialize_idempotency_key = p_idempotency_key;
  if found then
    return query select case when v_existing.initialize_request_digest = p_request_digest then 'replayed' else 'idempotency_conflict' end,
      jsonb_build_object('documentId', v_existing.document_id, 'versionId', v_existing.id,
        'versionNumber', v_existing.version_number, 'objectKey', v_existing.object_key,
        'uploadExpiresAt', v_existing.upload_expires_at, 'state', v_existing.processing_state);
    return;
  end if;

  if exists (select 1 from unnest(p_product_ids) x group by x having count(*) > 1)
    or exists (
      select 1 from unnest(p_product_ids) x left join public.products p
        on p.organization_id = p_organization_id and p.id = x
      where p.id is null or p.archived_at is not null
    )
  then
    return query select 'invalid_request'::text, null::jsonb;
    return;
  end if;

  select * into v_document from public.evidence_documents
  where organization_id = p_organization_id and id = p_document_id for update;
  if not found then
    return query select 'not_found'::text, null::jsonb;
    return;
  end if;
  if v_document.current_version_id <> p_expected_current_version_id then
    return query select 'conflict'::text,
      jsonb_build_object('documentId', v_document.id, 'currentVersionId', v_document.current_version_id);
    return;
  end if;

  select coalesce(max(version_number), 0) + 1 into v_version_number
  from public.evidence_document_versions
  where organization_id = p_organization_id and document_id = p_document_id;

  insert into public.evidence_document_versions(
    organization_id, document_id, version_number, title, document_class,
    retention_evidence_class, owner_user_id, uploader_user_id, validity_starts_on,
    validity_ends_on, object_key, original_filename, declared_size_bytes,
    upload_expires_at, initialize_idempotency_key, initialize_request_digest
  ) values (
    p_organization_id, p_document_id, v_version_number, p_title, p_document_class,
    public.m8_evidence_retention_class(p_document_class), p_owner_user_id, p_actor_user_id,
    p_validity_starts_on, p_validity_ends_on, p_object_key, p_original_filename,
    p_declared_size_bytes, p_upload_expires_at, p_idempotency_key, p_request_digest
  ) returning id into v_version_id;

  insert into public.evidence_document_version_products(organization_id, version_id, product_id)
  select p_organization_id, v_version_id, x from unnest(p_product_ids) x;
  update public.evidence_documents set current_version_id = v_version_id, updated_at = clock_timestamp()
  where organization_id = p_organization_id and id = p_document_id;
  insert into public.audit_logs(organization_id, user_id, action, entity_type, entity_id, changes)
  values (p_organization_id, p_actor_user_id, 'evidence.replacement_reserved',
    'evidence_document_version', v_version_id::text,
    jsonb_build_object('documentId', p_document_id, 'versionNumber', v_version_number,
      'expectedCurrentVersionId', p_expected_current_version_id, 'idempotencyKey', p_idempotency_key));
  return query select 'reserved'::text,
    jsonb_build_object('documentId', p_document_id, 'versionId', v_version_id,
      'versionNumber', v_version_number, 'objectKey', p_object_key,
      'uploadExpiresAt', p_upload_expires_at, 'state', 'uploading');
end $$;

create or replace function public.authorize_evidence_document_access_atomic(
  p_organization_id uuid, p_actor_user_id uuid, p_product_id uuid, p_document_id uuid,
  p_version_id uuid, p_access_mode text, p_purpose text, p_request_correlation_id uuid,
  p_token_sha256 text, p_expires_at timestamptz
) returns table(outcome text, result jsonb)
language plpgsql security definer set search_path=public,pg_temp as $$
declare v public.evidence_document_versions%rowtype;
declare v_grant_id uuid;
begin
  if p_product_id is null or p_document_id is null or p_version_id is null
    or p_access_mode not in ('preview', 'download', 'export')
    or p_request_correlation_id is null or p_token_sha256 is null or p_token_sha256 !~ '^[a-f0-9]{64}$'
    or p_expires_at is null or p_expires_at not between clock_timestamp() + interval '1 second' and clock_timestamp() + interval '5 minutes'
    or (p_purpose is not null and (p_purpose <> btrim(p_purpose) or char_length(p_purpose) not between 1 and 500 or p_purpose ~ '[[:cntrl:]]'))
    or not public.m8_evidence_actor_active(p_organization_id, p_actor_user_id)
  then
    return query select 'forbidden'::text, null::jsonb;
    return;
  end if;
  select * into v from public.evidence_document_versions
  where organization_id = p_organization_id and id = p_version_id and document_id = p_document_id;
  if not found then return query select 'not_found'::text, null::jsonb; return; end if;
  if not exists (select 1 from public.products p where p.organization_id = p_organization_id and p.id = p_product_id and p.archived_at is null)
    or not exists (select 1 from public.evidence_document_version_products vp where vp.organization_id = p_organization_id and vp.version_id = v.id and vp.product_id = p_product_id)
  then return query select 'forbidden'::text, null::jsonb; return; end if;
  if v.processing_state <> 'clean' then
    return query select 'unavailable'::text, jsonb_build_object('state', v.processing_state);
    return;
  end if;
  if v.validity_ends_on is not null and v.validity_ends_on < current_date then
    return query select 'unavailable'::text, jsonb_build_object('state', 'expired');
    return;
  end if;
  insert into public.evidence_document_access_grants(
    organization_id, actor_user_id, document_id, version_id, product_id, access_mode,
    purpose, token_sha256, request_correlation_id, expires_at
  ) values (
    p_organization_id, p_actor_user_id, p_document_id, p_version_id, p_product_id,
    p_access_mode, nullif(p_purpose, ''), p_token_sha256, p_request_correlation_id, p_expires_at
  ) returning id into v_grant_id;
  insert into public.audit_logs(organization_id, user_id, action, entity_type, entity_id, changes)
  values (p_organization_id, p_actor_user_id, 'evidence.access_authorized', 'evidence_document_version', v.id::text,
    jsonb_build_object('grantId', v_grant_id, 'documentId', p_document_id, 'productId', p_product_id,
      'mode', p_access_mode, 'purpose', nullif(p_purpose, ''), 'correlationId', p_request_correlation_id,
      'expiresAt', p_expires_at));
  return query select 'authorized'::text,
    jsonb_build_object('grantId', v_grant_id, 'documentId', p_document_id, 'versionId', v.id,
      'productId', p_product_id, 'objectBucket', v.object_bucket, 'objectKey', v.object_key,
      'filename', v.original_filename, 'mediaType', v.detected_media_type,
      'byteSize', v.actual_size_bytes, 'sha256', v.original_sha256, 'expiresAt', p_expires_at,
      'mode', p_access_mode);
exception when unique_violation then
  return query select 'conflict'::text, null::jsonb;
end $$;

create or replace function public.redeem_evidence_document_access_atomic(
  p_organization_id uuid, p_actor_user_id uuid, p_token_sha256 text,
  p_request_correlation_id uuid, p_range_start bigint default null,
  p_range_end bigint default null
) returns table(outcome text, result jsonb)
language plpgsql security definer set search_path=public,pg_temp as $$
declare g public.evidence_document_access_grants%rowtype;
declare v public.evidence_document_versions%rowtype;
begin
  if p_token_sha256 is null or p_token_sha256 !~ '^[a-f0-9]{64}$' or p_request_correlation_id is null
    or ((p_range_start is null) <> (p_range_end is null))
    or (p_range_start is not null and (p_range_start < 0 or p_range_end < p_range_start))
    or not public.m8_evidence_actor_active(p_organization_id, p_actor_user_id)
  then return query select 'forbidden'::text, null::jsonb; return; end if;
  select * into g from public.evidence_document_access_grants
  where organization_id = p_organization_id and token_sha256 = p_token_sha256 for update;
  if not found or g.actor_user_id <> p_actor_user_id then return query select 'forbidden'::text, null::jsonb; return; end if;
  if g.expires_at < clock_timestamp() then
    update public.evidence_document_access_grants set terminal_outcome = 'expired' where id = g.id;
    insert into public.audit_logs(organization_id, user_id, action, entity_type, entity_id, changes)
    values (p_organization_id, p_actor_user_id, 'evidence.access_expired', 'evidence_document_version', g.version_id::text,
      jsonb_build_object('grantId', g.id, 'correlationId', p_request_correlation_id));
    return query select 'expired'::text, null::jsonb; return;
  end if;
  select * into v from public.evidence_document_versions
  where organization_id = p_organization_id and id = g.version_id and document_id = g.document_id;
  if not found or v.processing_state <> 'clean' or (v.validity_ends_on is not null and v.validity_ends_on < current_date)
    or not exists (select 1 from public.products p where p.organization_id = p_organization_id and p.id = g.product_id and p.archived_at is null)
    or not exists (select 1 from public.evidence_document_version_products vp where vp.organization_id = p_organization_id and vp.version_id = g.version_id and vp.product_id = g.product_id)
  then return query select 'unavailable'::text, null::jsonb; return; end if;
  if p_range_start is not null and p_range_end >= v.actual_size_bytes then
    return query select 'invalid_range'::text, null::jsonb; return;
  end if;
  update public.evidence_document_access_grants set
    first_redeemed_at = coalesce(first_redeemed_at, clock_timestamp()), last_redeemed_at = clock_timestamp(),
    redemption_count = redemption_count + 1,
    first_range_start = coalesce(first_range_start, p_range_start), first_range_end = coalesce(first_range_end, p_range_end),
    last_range_start = p_range_start, last_range_end = p_range_end, terminal_outcome = 'delivered'
  where id = g.id;
  insert into public.audit_logs(organization_id, user_id, action, entity_type, entity_id, changes)
  values (p_organization_id, p_actor_user_id, 'evidence.byte_delivery_started', 'evidence_document_version', v.id::text,
    jsonb_build_object('grantId', g.id, 'documentId', g.document_id, 'mode', g.access_mode,
      'purpose', g.purpose, 'correlationId', p_request_correlation_id,
      'rangeStart', p_range_start, 'rangeEnd', p_range_end));
  return query select 'redeemed'::text,
    jsonb_build_object('grantId', g.id, 'documentId', g.document_id, 'versionId', v.id,
      'objectBucket', v.object_bucket, 'objectKey', v.object_key, 'filename', v.original_filename,
      'mediaType', v.detected_media_type, 'byteSize', v.actual_size_bytes, 'sha256', v.original_sha256,
      'mode', g.access_mode, 'expiresAt', g.expires_at);
end $$;

create or replace function public.record_evidence_document_integrity_failure_atomic(
  p_organization_id uuid, p_actor_user_id uuid, p_version_id uuid,
  p_observed_size_bytes bigint, p_observed_media_type text, p_observed_sha256 text,
  p_request_correlation_id uuid
) returns text
language plpgsql security definer set search_path=public,pg_temp as $$
declare v public.evidence_document_versions%rowtype;
begin
  if p_actor_user_id is null or p_request_correlation_id is null
    or not public.m8_evidence_actor_active(p_organization_id, p_actor_user_id)
  then return 'forbidden'; end if;
  select * into v from public.evidence_document_versions
  where organization_id = p_organization_id and id = p_version_id for update;
  if not found then return 'not_found'; end if;
  if v.processing_state = 'failed' and v.failure_code = 'integrity_mismatch' then return 'replayed'; end if;
  if v.processing_state <> 'clean' then return 'unavailable'; end if;
  update public.evidence_document_versions
  set processing_state = 'failed', failure_code = 'integrity_mismatch'
  where organization_id = p_organization_id and id = v.id;
  insert into public.evidence_document_notification_outbox(organization_id, version_id, owner_user_id, event_type)
  values (p_organization_id, v.id, v.owner_user_id, 'evidence_integrity_failure') on conflict do nothing;
  insert into public.audit_logs(organization_id, user_id, action, entity_type, entity_id, changes)
  values (p_organization_id, p_actor_user_id, 'evidence.integrity_failure', 'evidence_document_version', v.id::text,
    jsonb_build_object('correlationId', p_request_correlation_id, 'expectedSha256', v.original_sha256,
      'observedSha256', nullif(p_observed_sha256, ''), 'expectedByteSize', v.actual_size_bytes,
      'observedByteSize', p_observed_size_bytes, 'expectedMediaType', v.detected_media_type,
      'observedMediaType', nullif(p_observed_media_type, '')));
  return 'recorded';
end $$;

alter table public.evidence_document_access_grants enable row level security;
revoke all on table public.evidence_document_access_grants from public, anon, authenticated;
grant all on table public.evidence_document_access_grants to service_role;
revoke all on function
  public.reserve_evidence_document_replacement_atomic(uuid,uuid,uuid,uuid,text,text,uuid,uuid[],date,date,text,bigint,text,timestamptz,uuid,text),
  public.list_evidence_document_versions(uuid,uuid,uuid),
  public.authorize_evidence_document_access_atomic(uuid,uuid,uuid,uuid,uuid,text,text,uuid,text,timestamptz),
  public.redeem_evidence_document_access_atomic(uuid,uuid,text,uuid,bigint,bigint),
  public.record_evidence_document_integrity_failure_atomic(uuid,uuid,uuid,bigint,text,text,uuid)
from public, anon, authenticated;
grant execute on function
  public.reserve_evidence_document_replacement_atomic(uuid,uuid,uuid,uuid,text,text,uuid,uuid[],date,date,text,bigint,text,timestamptz,uuid,text),
  public.list_evidence_document_versions(uuid,uuid,uuid),
  public.authorize_evidence_document_access_atomic(uuid,uuid,uuid,uuid,uuid,text,text,uuid,text,timestamptz),
  public.redeem_evidence_document_access_atomic(uuid,uuid,text,uuid,bigint,bigint),
  public.record_evidence_document_integrity_failure_atomic(uuid,uuid,uuid,bigint,text,text,uuid)
to service_role;
notify pgrst, 'reload schema';
