-- Filter immutable source events before loading historical payloads. Opening dates
-- still come from the pinned latest correction; closure episodes are unchanged.
create index m5_trend_first_observation on public.vulnerability_finding_lifecycle_facts(organization_id,product_id,finding_id,sequence)include(recorded_transaction_id)where finding_id is not null and previous_sequence is null and fact_kind='observation';
create index m5_trend_reopening_candidates on public.vulnerability_finding_lifecycle_facts(organization_id,effective_at,sequence)include(product_id,finding_id,previous_sequence,recorded_transaction_id)where finding_id is not null and previous_sequence is not null and payload->>'open'='true';
do $migration$
declare definition text;changed text;
begin
 definition:=pg_get_functiondef('public.get_dashboard_trends(uuid,uuid,jsonb,jsonb)'::regprocedure);
 changed:=definition;
 if position($anchor$facts as materialized(select f.*,prev.payload previous from public.vulnerability_finding_lifecycle_facts f left join public.vulnerability_finding_lifecycle_facts prev on prev.organization_id=org and prev.sequence=f.previous_sequence where metric='activity'and f.organization_id=org and f.finding_id is not null and(product is null or f.product_id=product)and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)),
 $anchor$in changed)=0 then raise exception 'M14-02 activity stream anchor missing for get_dashboard_trends';end if;
 changed:=replace(changed,$anchor$facts as materialized(select f.*,prev.payload previous from public.vulnerability_finding_lifecycle_facts f left join public.vulnerability_finding_lifecycle_facts prev on prev.organization_id=org and prev.sequence=f.previous_sequence where metric='activity'and f.organization_id=org and f.finding_id is not null and(product is null or f.product_id=product)and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)),
 $anchor$,$replacement$opening_facts as materialized(select f.finding_id from public.vulnerability_finding_lifecycle_facts f where metric='activity'and f.organization_id=org and f.finding_id is not null and f.previous_sequence is null and f.fact_kind='observation'and(product is null or f.product_id=product)and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)),
 facts as materialized(select f.*,prev.payload previous from public.vulnerability_finding_lifecycle_facts f join public.vulnerability_finding_lifecycle_facts prev on prev.organization_id=org and prev.sequence=f.previous_sequence where metric='activity'and f.organization_id=org and f.finding_id is not null and f.previous_sequence is not null and f.payload->>'open'='true'and(product is null or f.product_id=product)and f.effective_at>=greatest(from_date::timestamp at time zone zone,baseline)and f.effective_at<least((to_date+1)::timestamp at time zone zone,now_at)and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)),
 $replacement$);
 if position($anchor$from facts f join latest l using(finding_id)where f.previous_sequence is null and f.fact_kind='observation'$anchor$in changed)=0 then raise exception 'M14-02 activity stream anchor missing for get_dashboard_trends';end if;
 changed:=replace(changed,$anchor$from facts f join latest l using(finding_id)where f.previous_sequence is null and f.fact_kind='observation'$anchor$,$replacement$from opening_facts f join latest l using(finding_id)$replacement$);
 execute changed;
 definition:=pg_get_functiondef('public.get_dashboard_trend_sources(uuid,uuid,jsonb,jsonb)'::regprocedure);
 changed:=definition;
 if position($anchor$finding_facts as materialized(select f.*,p.payload previous from public.vulnerability_finding_lifecycle_facts f left join public.vulnerability_finding_lifecycle_facts p on p.organization_id=p_organization_id and p.sequence=f.previous_sequence where metric='activity'and f.organization_id=p_organization_id and f.finding_id is not null and(product is null or f.product_id=product)and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)),
 $anchor$in changed)=0 then raise exception 'M14-02 activity stream anchor missing for get_dashboard_trend_sources';end if;
 changed:=replace(changed,$anchor$finding_facts as materialized(select f.*,p.payload previous from public.vulnerability_finding_lifecycle_facts f left join public.vulnerability_finding_lifecycle_facts p on p.organization_id=p_organization_id and p.sequence=f.previous_sequence where metric='activity'and f.organization_id=p_organization_id and f.finding_id is not null and(product is null or f.product_id=product)and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)),
 $anchor$,$replacement$opening_facts as materialized(select f.*from public.vulnerability_finding_lifecycle_facts f where metric='activity'and f.organization_id=p_organization_id and f.finding_id is not null and f.previous_sequence is null and f.fact_kind='observation'and(product is null or f.product_id=product)and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)),
 finding_facts as materialized(select f.*,p.payload previous from public.vulnerability_finding_lifecycle_facts f join public.vulnerability_finding_lifecycle_facts p on p.organization_id=p_organization_id and p.sequence=f.previous_sequence where metric='activity'and f.organization_id=p_organization_id and f.finding_id is not null and f.previous_sequence is not null and f.payload->>'open'='true'and(product is null or f.product_id=product)and f.effective_at>=greatest(from_at,(dataset#>>'{result,baselineAt}')::timestamptz)and f.effective_at<to_at and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)),
 $replacement$);
 if position($anchor$from finding_facts f join finding_latest l using(finding_id)where metric='activity'and f.fact_kind='observation'and f.previous_sequence is null$anchor$in changed)=0 then raise exception 'M14-02 activity stream anchor missing for get_dashboard_trend_sources';end if;
 changed:=replace(changed,$anchor$from finding_facts f join finding_latest l using(finding_id)where metric='activity'and f.fact_kind='observation'and f.previous_sequence is null$anchor$,$replacement$from opening_facts f join finding_latest l using(finding_id)where metric='activity'$replacement$);
 execute changed;
end $migration$;
