-- M13-05 visibility-filtered health and honest collector acknowledgement.
create or replace function public.m13_05_public_destination(p_dest public.siem_destinations,p_actor uuid default null) returns jsonb language sql stable security definer set search_path=pg_catalog,public as $$
 select jsonb_build_object('id',p_dest.id,'name',p_dest.display_name,'transport',p_dest.transport,'format',p_dest.format,'endpoint',p_dest.endpoint,'eventClasses',p_dest.event_classes,'productIds',p_dest.product_ids,'state',p_dest.state,'version',p_dest.version,'credentialState',case when p_dest.credentials is not null then 'active' when p_dest.credential_revision>0 then 'revoked' else 'missing' end,'authorityUserId',p_dest.authority_user_id,'createdAt',p_dest.created_at,'updatedAt',p_dest.updated_at,'health',jsonb_build_object('pendingCount',count(*) filter(where d.state in ('queued','processing')),'failedCount',count(*) filter(where d.state='failed'),'oldestPendingAt',min(d.created_at) filter(where d.state in ('queued','processing')),'lastAcceptedAt',max(d.updated_at) filter(where d.state='accepted'),'safeFailureCode',p_dest.failure_code)) from public.siem_deliveries d join public.audit_logs a on a.id=d.event_id where d.organization_id=p_dest.organization_id and d.destination_id=p_dest.id and public.m13_03_event_visible(p_dest.organization_id,coalesce(p_actor,p_dest.authority_user_id),a)
$$;

create or replace function public.m13_05_receipt(p_org uuid,p_actor uuid,p_request uuid,p_operation text,p_entity uuid,p_digest text,p_result jsonb default '{}'::jsonb,p_key_id text default null) returns void language plpgsql security definer set search_path=pg_catalog,public as $$ begin
 if p_request is null or p_operation !~ '^[a-z_]{1,40}$' or p_digest !~ '^[0-9a-f]{64}$' then raise exception 'invalid SIEM receipt' using errcode='22023'; end if;
 insert into public.audit_logs(organization_id,user_id,action,entity_type,entity_id,schema_version,event_scope,event_key,actor_type,actor_id,outcome,correlation_id,changes,redaction_version)
 values(null,p_actor,'audit.siem.'||p_operation,'audit_siem',p_entity::text,2,'security',case when p_operation='test_prepare' then 'audit.siem.prepare:' else 'audit.siem:' end||p_org||':'||coalesce(p_actor::text,'system')||':'||p_request,case when p_actor is null then 'system' else 'user' end,coalesce(p_actor::text,'system'),case when p_operation='denial' then 'denied' else 'completed' end,p_request,jsonb_build_object('organizationId',p_org,'operationDigest',p_digest,'result',p_result,'keyId',p_key_id),1);
end $$;

create or replace function public.m13_05_siem_complete(p_organization_id uuid,p_delivery_id uuid,p_worker_id text,p_lease_token uuid,p_version integer,p_outcome jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_delivery public.siem_deliveries;v_state text:=p_outcome->>'state';v_delay integer;begin
 select * into v_delivery from public.siem_deliveries where organization_id=p_organization_id and id=p_delivery_id and state='processing' and worker_id=p_worker_id and lease_token=p_lease_token and version=p_version and lease_expires_at>clock_timestamp() for update;
 if not found then raise exception 'siem_lease_conflict' using errcode='23505'; end if;
 if v_state not in ('accepted','sent_unacknowledged','retry','failed') or coalesce(p_outcome->>'code','delivered') !~ '^[a-z][a-z0-9_]{0,79}$' then raise exception 'invalid delivery outcome' using errcode='22023'; end if;
 insert into public.siem_delivery_attempts(organization_id,delivery_id,lease_token,attempt_number,state,code,http_status,duration_ms) values(p_organization_id,v_delivery.id,p_lease_token,v_delivery.attempt_count,v_state,coalesce(p_outcome->>'code','delivered'),(p_outcome->>'status')::integer,(p_outcome->>'durationMs')::integer);
 v_delay:=least(86400,greatest(coalesce((p_outcome->>'retryAfterSeconds')::integer,0),greatest(5,least(300,(5*power(2,v_delivery.attempt_count-1)*(0.5+random()*0.5))::integer))));
 update public.siem_deliveries set state=case when v_state='retry' and attempt_count<6 and first_attempt_at>clock_timestamp()-interval '24 hours' then 'queued' when v_state='retry' then 'failed' else v_state end,version=version+1,failure_code=case when v_state in ('accepted','sent_unacknowledged') then null else p_outcome->>'code' end,next_attempt_at=clock_timestamp()+make_interval(secs=>v_delay),lease_token=null,lease_expires_at=null,worker_id=null,updated_at=clock_timestamp() where id=v_delivery.id returning * into v_delivery;
 if v_state='accepted' then update public.siem_destinations set last_accepted_at=clock_timestamp(),failure_code=null where id=v_delivery.destination_id and organization_id=p_organization_id; end if;
 perform public.m13_05_receipt(p_organization_id,null,gen_random_uuid(),'completed',v_delivery.destination_id,repeat('0',64));
 return jsonb_build_object('ok',true);
end $$;