-- Page source metadata through explicit tenant/product statements. New typed
-- reopening facts no longer load previous JSON payloads; old facts keep fallback.
create index m5_trend_reopening_source_product on public.vulnerability_finding_lifecycle_facts(organization_id,product_id,effective_at,('finding-'||sequence||'-reopened'))include(sequence,finding_id,recorded_at,provenance,recorded_transaction_id,fact_kind)where is_reopening=true;
create index m5_trend_reopening_source_org on public.vulnerability_finding_lifecycle_facts(organization_id,effective_at,('finding-'||sequence||'-reopened'))include(sequence,product_id,finding_id,recorded_at,provenance,recorded_transaction_id,fact_kind)where is_reopening=true;
do $migration$
declare definition text;changed text;query_start integer;query_end integer;body text;org_body text;product_body text;
begin
 definition:=pg_get_functiondef('public.get_dashboard_trend_sources(uuid,uuid,jsonb,jsonb)'::regprocedure);changed:=definition;
 if position($anchor$finding_facts as materialized(select f.*,p.payload previous from public.vulnerability_finding_lifecycle_facts f join public.vulnerability_finding_lifecycle_facts p on p.organization_id=p_organization_id and p.sequence=f.previous_sequence where metric='activity'and f.organization_id=p_organization_id and f.finding_id is not null and f.previous_sequence is not null and f.payload->>'open'='true'and(product is null or f.product_id=product)and f.effective_at>=greatest(from_at,(dataset#>>'{result,baselineAt}')::timestamptz)and f.effective_at<to_at and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot))$anchor$in changed)=0 then raise exception 'M14-02 source stream anchor missing';end if;
 changed:=replace(changed,$anchor$finding_facts as materialized(select f.*,p.payload previous from public.vulnerability_finding_lifecycle_facts f join public.vulnerability_finding_lifecycle_facts p on p.organization_id=p_organization_id and p.sequence=f.previous_sequence where metric='activity'and f.organization_id=p_organization_id and f.finding_id is not null and f.previous_sequence is not null and f.payload->>'open'='true'and(product is null or f.product_id=product)and f.effective_at>=greatest(from_at,(dataset#>>'{result,baselineAt}')::timestamptz)and f.effective_at<to_at and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot))$anchor$,$replacement$finding_facts as materialized((select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,f.effective_at,f.fact_kind,true is_reopening from public.vulnerability_finding_lifecycle_facts f where metric='activity'and f.fact_kind='observation'and f.organization_id=p_organization_id and(product is null or f.product_id=product)and f.effective_at>=greatest(from_at,(dataset#>>'{result,baselineAt}')::timestamptz)and f.effective_at<to_at and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot) and f.is_reopening=true order by f.effective_at,('finding-'||f.sequence||'-reopened')limit(off+lim+1))union all (select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,f.effective_at,f.fact_kind,p.payload->>'open'='false'and coalesce(p.payload->>'superseded','false')='false'and f.payload->>'open'='true' is_reopening from public.vulnerability_finding_lifecycle_facts f join public.vulnerability_finding_lifecycle_facts p on p.organization_id=p_organization_id and p.sequence=f.previous_sequence where metric='activity'and f.fact_kind='observation'and f.organization_id=p_organization_id and(product is null or f.product_id=product)and f.effective_at>=greatest(from_at,(dataset#>>'{result,baselineAt}')::timestamptz)and f.effective_at<to_at and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot) and f.is_reopening is null and f.finding_id is not null and f.previous_sequence is not null and f.payload->>'open'='true'and p.payload->>'open'='false'and coalesce(p.payload->>'superseded','false')='false'order by f.effective_at,('finding-'||f.sequence||'-reopened')limit(off+lim+1)))$replacement$);
 if position($anchor$and f.previous->>'open'='false'and coalesce(f.previous->>'superseded','false')='false'and f.payload->>'open'='true'$anchor$in changed)=0 then raise exception 'M14-02 source stream anchor missing';end if;
 changed:=replace(changed,$anchor$and f.previous->>'open'='false'and coalesce(f.previous->>'superseded','false')='false'and f.payload->>'open'='true'$anchor$,$replacement$and f.is_reopening$replacement$);
 query_start:=position(' with recursive opening_facts as'in changed);query_end:=position(' return jsonb_build_object'in substring(changed from query_start))+query_start-1;
 if query_start=0 or query_end<query_start then raise exception 'M14-02 source query branch anchor missing';end if;
 body:=substring(changed from query_start for query_end-query_start);
 org_body:=replace(replace(body,'and(product is null or f.product_id=product)',''),'and(product is null or product_id=product)','');
 product_body:=replace(replace(body,'(product is null or f.product_id=product)','(f.product_id=product)'),'(product is null or product_id=product)','(product_id=product)');
 changed:=substring(changed from 1 for query_start-1)||' if product is null then '||org_body||' else '||product_body||' end if; '||substring(changed from query_end);
 execute changed;
end $migration$;
notify pgrst,'reload schema';
