-- M7-03: durable replay is kept in the existing audit ledger. A key is scoped
-- to actor and organization and may only be reused for the identical command.
create or replace function public.m7_evidence_review_json(p_organization_id uuid,p_review_id uuid)
returns jsonb language sql stable security definer set search_path=public,pg_temp as $$
 select jsonb_build_object('id',r.id,'sourceId',r.source_id,'decision',r.decision,'rationale',r.rationale,'previousObservedRevision',r.linked_revision,'previousFingerprint',r.linked_fingerprint,'reviewedObservedRevision',r.reviewed_against_revision,'reviewedFingerprint',r.reviewed_against_fingerprint,'reviewedByUserId',r.created_by,'createdAt',to_char(r.created_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS"Z"')) from public.technical_file_section_source_reviews r where r.organization_id=p_organization_id and r.id=p_review_id
$$;

create or replace function public.mark_technical_file_section_source_material_change_atomic(p_organization_id uuid,p_actor_user_id uuid,p_product_id uuid,p_section_key text,p_source_id uuid,p_expected_version integer,p_reason text,p_current_observed_revision text,p_current_fingerprint text,p_idempotency_key uuid)
returns table(outcome text,result jsonb) language plpgsql security definer set search_path=public,pg_temp as $$
declare s public.technical_file_sections%rowtype; d text; prior record;
begin
 d:=encode(extensions.digest(jsonb_build_object('operation','material_change','productId',p_product_id,'sectionKey',p_section_key,'sourceId',p_source_id,'expectedVersion',p_expected_version,'reason',p_reason,'currentObservedRevision',p_current_observed_revision,'currentFingerprint',p_current_fingerprint)::text,'sha256'),'hex');
 if p_reason not in('product_facts_changed','release_changed','support_basis_changed','risk_register_changed','sbom_revision_changed','source_validity_changed','source_quarantined','standard_edition_changed','document_version_changed')or char_length(btrim(coalesce(p_current_fingerprint,'')))not between 1 and 200 or p_idempotency_key is null or not public.m7_technical_file_actor_can(p_organization_id,p_actor_user_id,'can_edit_technical_files')then return query select'invalid_request',null::jsonb;return;end if;
 select a.* into prior from public.audit_logs a where a.organization_id=p_organization_id and a.user_id=p_actor_user_id and a.changes->>'idempotencyKey'=p_idempotency_key::text order by a.created_at desc,a.id desc limit 1;
 if found then if prior.action='technical_file.source_marked_stale' and prior.changes->>'payloadDigest'=d then return query select'replayed',jsonb_build_object('source',public.m7_evidence_link_json(p_organization_id,p_product_id,p_source_id)); else return query select'idempotency_conflict',null::jsonb;end if;return;end if;
 select q.* into s from public.technical_file_sections q join public.technical_files f on f.organization_id=q.organization_id and f.id=q.technical_file_id where q.organization_id=p_organization_id and f.product_id=p_product_id and f.status='active'and q.section_key=p_section_key for update;
 if not found then return query select'not_found',null::jsonb;return;end if;if s.version<>p_expected_version then return query select'conflict',jsonb_build_object('currentVersion',s.version);return;end if;
 update public.technical_file_section_sources set stale_at=coalesce(stale_at,clock_timestamp()),stale_reason=p_reason,stale_current_revision=p_current_observed_revision,stale_current_fingerprint=p_current_fingerprint,link_version=link_version+1 where organization_id=p_organization_id and section_id=s.id and id=p_source_id;if not found then return query select'not_found',null::jsonb;return;end if;
 update public.technical_file_sections set version=version+1,updated_at=clock_timestamp(),updated_by=p_actor_user_id where organization_id=p_organization_id and id=s.id;
 insert into public.audit_logs(organization_id,user_id,action,entity_type,entity_id,changes)values(p_organization_id,p_actor_user_id,'technical_file.source_marked_stale','technical_file_section_source',p_source_id::text,jsonb_build_object('idempotencyKey',p_idempotency_key,'payloadDigest',d));
 return query select'marked_stale',jsonb_build_object('source',public.m7_evidence_link_json(p_organization_id,p_product_id,p_source_id));
end $$;

create or replace function public.review_technical_file_section_source_atomic(p_organization_id uuid,p_actor_user_id uuid,p_product_id uuid,p_section_key text,p_source_id uuid,p_expected_version integer,p_decision text,p_rationale text,p_idempotency_key uuid)
returns table(outcome text,result jsonb) language plpgsql security definer set search_path=public,pg_temp as $$
declare s public.technical_file_sections%rowtype;x public.technical_file_section_sources%rowtype;snap record;rid uuid;d text;prior record;
begin
 d:=encode(extensions.digest(jsonb_build_object('operation','review_source','productId',p_product_id,'sectionKey',p_section_key,'sourceId',p_source_id,'expectedVersion',p_expected_version,'decision',p_decision,'rationale',p_rationale)::text,'sha256'),'hex');
 if p_decision not in('retain','update')or char_length(btrim(coalesce(p_rationale,'')))not between 1 and 4000 or p_idempotency_key is null or not public.m7_technical_file_actor_can(p_organization_id,p_actor_user_id,'can_edit_technical_files')then return query select'invalid_request',null::jsonb;return;end if;
 select a.* into prior from public.audit_logs a where a.organization_id=p_organization_id and a.user_id=p_actor_user_id and a.changes->>'idempotencyKey'=p_idempotency_key::text order by a.created_at desc,a.id desc limit 1;
 if found then if prior.action='technical_file.source_reviewed'and prior.changes->>'payloadDigest'=d then return query select'replayed',jsonb_build_object('source',public.m7_evidence_link_json(p_organization_id,p_product_id,p_source_id),'review',public.m7_evidence_review_json(p_organization_id,(prior.changes->>'reviewId')::uuid));else return query select'idempotency_conflict',null::jsonb;end if;return;end if;
 select q.* into s from public.technical_file_sections q join public.technical_files f on f.organization_id=q.organization_id and f.id=q.technical_file_id where q.organization_id=p_organization_id and f.product_id=p_product_id and f.status='active'and q.section_key=p_section_key for update;if not found then return query select'not_found',null::jsonb;return;end if;if s.version<>p_expected_version then return query select'conflict',jsonb_build_object('currentVersion',s.version);return;end if;
 select * into x from public.technical_file_section_sources where organization_id=p_organization_id and section_id=s.id and id=p_source_id for update;if not found or x.stale_at is null then return query select'invalid_request',null::jsonb;return;end if;
 if x.source_kind<>'manual_reference'then select * into snap from public.m7_evidence_source_snapshot(p_organization_id,p_product_id,x.source_kind,x.record_id);if p_decision='update'and(not found or not snap.is_current)then return query select'invalid_request',null::jsonb;return;end if;end if;
 insert into public.technical_file_section_source_reviews(organization_id,source_id,decision,rationale,linked_revision,linked_fingerprint,reviewed_against_revision,reviewed_against_fingerprint,created_by)values(p_organization_id,p_source_id,p_decision,btrim(p_rationale),x.observed_revision,x.source_fingerprint,coalesce(snap.revision,x.stale_current_revision),coalesce(snap.fingerprint,x.stale_current_fingerprint),p_actor_user_id)returning id into rid;
 update public.technical_file_section_sources set observed_revision=case when p_decision='update'then snap.revision else observed_revision end,source_fingerprint=case when p_decision='update'then snap.fingerprint else source_fingerprint end,stale_at=null,stale_reason=null,stale_current_revision=null,stale_current_fingerprint=null,reviewed_at=clock_timestamp(),reviewed_by=p_actor_user_id,reviewed_revision=coalesce(snap.revision,stale_current_revision),reviewed_fingerprint=coalesce(snap.fingerprint,stale_current_fingerprint),link_version=link_version+1 where organization_id=p_organization_id and id=p_source_id;
 update public.technical_file_sections set version=version+1,updated_at=clock_timestamp(),updated_by=p_actor_user_id where organization_id=p_organization_id and id=s.id;
 insert into public.audit_logs(organization_id,user_id,action,entity_type,entity_id,changes)values(p_organization_id,p_actor_user_id,'technical_file.source_reviewed','technical_file_section_source',p_source_id::text,jsonb_build_object('idempotencyKey',p_idempotency_key,'payloadDigest',d,'reviewId',rid));
 return query select'reviewed',jsonb_build_object('source',public.m7_evidence_link_json(p_organization_id,p_product_id,p_source_id),'review',public.m7_evidence_review_json(p_organization_id,rid));
end $$;

revoke all on function public.m7_evidence_review_json(uuid,uuid),public.mark_technical_file_section_source_material_change_atomic(uuid,uuid,uuid,text,uuid,integer,text,text,text,uuid),public.review_technical_file_section_source_atomic(uuid,uuid,uuid,text,uuid,integer,text,text,uuid) from public,anon,authenticated;
alter function public.m7_evidence_review_json(uuid,uuid) owner to postgres;alter function public.mark_technical_file_section_source_material_change_atomic(uuid,uuid,uuid,text,uuid,integer,text,text,text,uuid) owner to postgres;alter function public.review_technical_file_section_source_atomic(uuid,uuid,uuid,text,uuid,integer,text,text,uuid) owner to postgres;
grant execute on function public.mark_technical_file_section_source_material_change_atomic(uuid,uuid,uuid,text,uuid,integer,text,text,text,uuid),public.review_technical_file_section_source_atomic(uuid,uuid,uuid,text,uuid,integer,text,text,uuid) to service_role;
notify pgrst, 'reload schema';
