-- Preserve exact pinned observations while removing repeated legacy payload
-- joins. Current source identities enumerate organization cohorts only; the
-- validated restrictive tenant-composite FK retains every historical parent.
-- Current source state, release membership and timestamps never supply metrics.
-- Product identity enumeration remains historical. No cache or fact rewrite.
do $guard$
begin
 if md5(pg_get_functiondef('public.get_dashboard_trends(uuid,uuid,jsonb,jsonb)'::regprocedure))<>'fb4cf81ee600caaed93cc429715534a3'
 or md5(pg_get_functiondef('public.get_dashboard_trend_sources(uuid,uuid,jsonb,jsonb)'::regprocedure))<>'dc97695ebdd6d37e4d8ae1bc57cd5cd2'then
  raise exception'M14-02 unrecognized projection baseline; preserve and review function drift before applying';
 end if;
 if not exists(select 1 from pg_constraint where conrelid='public.vulnerability_finding_lifecycle_facts'::regclass and conname='vulnerability_finding_lifecycle_organization_id_finding_id_fkey'and convalidated and not condeferrable and confdeltype='a'and confupdtype='a')then
  raise exception'M14-02 organization identity enumeration requires validated restrictive tenant/source FK';
 end if;
end $guard$;
create index m5_trend_predecessor_effective_closed on public.vulnerability_finding_lifecycle_facts(organization_id,sequence)where payload->>'open'='false'and coalesce(payload->>'superseded','false')='false';
create index m5_trend_reopening_legacy_org on public.vulnerability_finding_lifecycle_facts(organization_id,effective_at,sequence)include(finding_id,previous_sequence,recorded_transaction_id,fact_kind)where is_reopening is null and finding_id is not null and previous_sequence is not null and payload->>'open'='true';
CREATE OR REPLACE FUNCTION public.get_dashboard_trends(p_organization_id uuid, p_actor_user_id uuid, p_filters jsonb, p_snapshot jsonb DEFAULT NULL::jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
 SET jit TO 'off'
 SET plan_cache_mode TO 'force_custom_plan'
AS $function$
declare org uuid:=p_organization_id;actor uuid:=p_actor_user_id;product uuid:=(p_filters->>'productId')::uuid;from_date date:=(p_filters->>'from')::date;to_date date:=(p_filters->>'to')::date;zone text:=p_filters->>'timezone';bucket text:=p_filters->>'bucket';pin jsonb;baseline timestamptz;snap pg_snapshot;fm bigint;cm bigint;sm bigint;metric text;series jsonb:='{}'::jsonb;points jsonb;state text;reason text;unit text;revision text;access jsonb:=p_filters->'sourceAccess';now_at timestamptz:=statement_timestamp();
begin
 p_filters:=p_filters-'sourceAccess';
 if access->>'products'='false'or not public.m14_actor_can(org,actor,'can_view_dashboards')or not public.m14_actor_can(org,actor,'can_view_products')then return jsonb_build_object('outcome','not_found');end if;
 if product is not null and not exists(select 1 from public.products where organization_id=org and id=product)then return jsonb_build_object('outcome','not_found');end if;
 if from_date is null or to_date is null or to_date<from_date or to_date-from_date>365 or bucket not in ('day','week','month')or not exists(select 1 from pg_timezone_names where name=zone)then return jsonb_build_object('outcome','invalid_request');end if;
 if to_date>(now_at at time zone zone)::date then return jsonb_build_object('outcome','invalid_request');end if;
 if p_snapshot is null then
 pin:=jsonb_build_object('cutoffAt',public.m7_snapshot_timestamp_utc(now_at),'snapshot',pg_current_snapshot()::text,'maxFindingSequence',coalesce((select max(sequence)from public.vulnerability_finding_lifecycle_facts where organization_id=org),0)::text,'maxCoverageSequence',coalesce((select max(sequence)from public.sbom_release_coverage_facts where organization_id=org),0)::text,'maxSnapshotSequence',coalesce((select max(trend_sequence)from public.technical_file_snapshots where organization_id=org),0)::text,'epoch',(select extensions.uuid_generate_v5('4d15a924-d2b2-4cd1-a1b1-ff4c3d81e392'::uuid,payload->>'epoch')::text from public.vulnerability_finding_lifecycle_facts where organization_id=org and finding_id is null));
 else pin:=p_snapshot;if pin->>'epoch' is distinct from(select extensions.uuid_generate_v5('4d15a924-d2b2-4cd1-a1b1-ff4c3d81e392'::uuid,payload->>'epoch')::text from public.vulnerability_finding_lifecycle_facts where organization_id=org and finding_id is null)then return jsonb_build_object('outcome','conflict');end if;end if;
 now_at:=(pin->>'cutoffAt')::timestamptz;
 snap:=(pin->>'snapshot')::pg_snapshot;fm:=(pin->>'maxFindingSequence')::bigint;cm:=(pin->>'maxCoverageSequence')::bigint;sm:=(pin->>'maxSnapshotSequence')::bigint;
 select effective_at into baseline from public.vulnerability_finding_lifecycle_facts where organization_id=org and finding_id is null and sequence<=fm and pg_visible_in_snapshot(recorded_transaction_id,snap);

 foreach metric in array array['activity','triage','remediation','sbomCoverage','readiness']loop
 state:='available';reason:=null;unit:=case metric when'activity'then'count'when'triage'then'hours'when'remediation'then'days'else'percent'end;
 if (access->>(case when metric in('activity','triage','remediation')then'findings'else metric end))='false'or metric in ('activity','triage','remediation')and not public.m14_actor_can(org,actor,'can_view_findings')or metric='sbomCoverage'and not public.m14_actor_can(org,actor,'can_view_sboms')or metric='readiness'and not public.m14_actor_can(org,actor,'can_view_technical_files')then state:='restricted';reason:='source_permission_required';
 elsif metric in ('triage','remediation','readiness')and product is null then state:='unavailable';reason:='select_product';
 elsif metric<>'readiness'and baseline is null then state:='unavailable';reason:='history_unavailable';
 elsif metric='readiness'and exists(select 1 from public.technical_file_snapshots s where metric='readiness'and s.organization_id=org and s.product_id=product and s.trend_sequence<=sm and pg_visible_in_snapshot(s.recorded_transaction_id,snap)and s.created_at>=from_date::timestamp at time zone zone and s.created_at<(to_date+1)::timestamp at time zone zone and not public.m14_02_snapshot_can(org,actor,s.id))then state:='restricted';reason:='snapshot_source_permission_required';end if;
 if state<>'available'then points:='[]';else
 if product is null then  with recursive calendar_boundaries as(select greatest(from_date::timestamp,d)::timestamp at time zone zone calendar_starts,least((to_date+1)::timestamp,d+case bucket when'day'then interval'1 day'when'week'then interval'1 week'else interval'1 month'end)::timestamp at time zone zone calendar_ends from generate_series(date_trunc(bucket,from_date::timestamp),to_date::timestamp,case bucket when'day'then interval'1 day'when'week'then interval'1 week'else interval'1 month'end)d),
 boundaries as(select case when metric in('activity','sbomCoverage')and calendar_ends>baseline then greatest(calendar_starts,baseline)else calendar_starts end starts,least(calendar_ends,now_at)ends,calendar_starts,calendar_ends from calendar_boundaries where calendar_starts<now_at),
 opening_facts as materialized(select f.finding_id from public.vulnerability_finding_lifecycle_facts f where metric='activity'and f.organization_id=org and f.finding_id is not null and f.previous_sequence is null and f.fact_kind='observation'and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)),
 legacy_reopening_totals as materialized(select date_trunc(bucket,f.effective_at at time zone zone)bucket_key,count(*)reopened from(select f.finding_id,f.fact_kind,f.effective_at,true is_reopening from public.vulnerability_finding_lifecycle_facts f join lateral(select prev.sequence from public.vulnerability_finding_lifecycle_facts prev where prev.organization_id=org and prev.sequence=f.previous_sequence and prev.payload->>'open'='false'and coalesce(prev.payload->>'superseded','false')='false'limit 1)previous_state on true where metric='activity'and f.organization_id=org and f.effective_at>=greatest(from_date::timestamp at time zone zone,baseline)and f.effective_at<least((to_date+1)::timestamp at time zone zone,now_at)and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap) and f.is_reopening is null and f.finding_id is not null and f.previous_sequence is not null and f.payload->>'open'='true'and(select probe.sequence from public.vulnerability_finding_lifecycle_facts probe where metric='activity'and probe.organization_id=org and probe.effective_at>=greatest(from_date::timestamp at time zone zone,baseline)and probe.effective_at<least((to_date+1)::timestamp at time zone zone,now_at)and probe.sequence<=fm and pg_visible_in_snapshot(probe.recorded_transaction_id,snap) and probe.is_reopening is null and probe.finding_id is not null and probe.previous_sequence is not null and probe.payload->>'open'='true' order by probe.product_id,probe.effective_at,probe.sequence limit 1)is not null)f where f.fact_kind='observation'group by 1),
 identities as materialized(select id finding_id from public.vulnerability_findings where metric in('activity','triage','remediation')and organization_id=org),
 latest as(select revision.finding_id,revision.first_detected_at,revision.triaged_at,revision.fixed_at,revision.closed_episodes from identities i cross join lateral(select f.finding_id,f.payload->>'firstDetectedAt'first_detected_at,f.payload->>'triagedAt'triaged_at,f.payload->>'fixedAt'fixed_at,f.payload->'closedEpisodes'closed_episodes from public.vulnerability_finding_lifecycle_facts f where f.organization_id=org and f.finding_id=i.finding_id and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)order by f.sequence desc limit 1)revision),
 events as(select f.finding_id,'opened'kind,l.first_detected_at::timestamptz at from opening_facts f join latest l using(finding_id)
 union all select l.finding_id,'closed',(e->>'at')::timestamptz from latest l cross join lateral jsonb_array_elements(coalesce(l.closed_episodes,'[]'))e),
 durations as(select finding_id,case metric when'triage'then triaged_at ::timestamptz else fixed_at ::timestamptz end at,extract(epoch from(case metric when'triage'then triaged_at ::timestamptz else fixed_at ::timestamptz end- first_detected_at ::timestamptz))/case metric when'triage'then 3600.0 else 86400.0 end value from latest),
 event_totals as(select date_trunc(bucket,e.at at time zone zone)bucket_key,count(*)filter(where kind='opened')opened,count(*)filter(where kind='closed')closed,count(*)filter(where kind='reopened')reopened from events e where metric='activity'and e.at>=greatest(from_date::timestamp at time zone zone,baseline)and e.at<least(now_at,(to_date+1)::timestamp at time zone zone)group by 1),
 duration_totals as(select date_trunc(bucket,d.at at time zone zone)bucket_key,avg(value)filter(where value>=0 and d.at>=baseline)duration_mean,count(*)filter(where value>=0 and d.at>=baseline)sample_count,count(*)filter(where value<0 and d.at>=baseline)excluded_count from durations d where metric in('triage','remediation')and d.at>=from_date::timestamp at time zone zone and d.at<least(now_at,(to_date+1)::timestamp at time zone zone)group by 1),
 coverage_deltas as not materialized(select f.effective_at,f.eligible_delta,f.covered_delta from public.sbom_release_coverage_facts f where metric='sbomCoverage'and f.organization_id=org and f.release_id is not null and f.sequence<=cm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)and f.effective_at<least(now_at,(to_date+1)::timestamp at time zone zone)and f.eligible_delta is not null and f.covered_delta is not null union all select f.effective_at,(f.payload->>'eligible')::boolean::int-coalesce((prev.payload->>'eligible')::boolean::int,0),((f.payload->>'eligible')::boolean and(f.payload->>'covered')::boolean)::int-coalesce(((prev.payload->>'eligible')::boolean and(prev.payload->>'covered')::boolean)::int,0)from public.sbom_release_coverage_facts f left join public.sbom_release_coverage_facts prev on prev.organization_id=org and prev.sequence=f.previous_sequence where metric='sbomCoverage'and f.organization_id=org and f.release_id is not null and f.sequence<=cm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)and f.effective_at<least(now_at,(to_date+1)::timestamp at time zone zone)and(f.eligible_delta is null or f.covered_delta is null)and(select probe.sequence from public.sbom_release_coverage_facts probe where metric='sbomCoverage'and probe.organization_id=org and probe.release_id is not null and probe.sequence<=cm and pg_visible_in_snapshot(probe.recorded_transaction_id,snap)and probe.effective_at<least(now_at,(to_date+1)::timestamp at time zone zone)and(probe.eligible_delta is null or probe.covered_delta is null) order by probe.product_id,probe.effective_at,probe.sequence limit 1)is not null),
 coverage_totals as(select date_trunc(bucket,effective_at at time zone zone)bucket_key,sum(eligible_delta)eligible_delta,sum(covered_delta)covered_delta from coverage_deltas group by 1),
 reopening_totals as materialized(select b.starts,(select count(*)from public.vulnerability_finding_lifecycle_facts f where metric='activity'and f.organization_id=org and f.is_reopening=true and f.fact_kind='observation'and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)and f.effective_at>=greatest(b.starts,baseline,from_date::timestamp at time zone zone)and f.effective_at<least(b.ends,now_at,(to_date+1)::timestamp at time zone zone))+coalesce(lt.reopened,0)reopened from boundaries b left join legacy_reopening_totals lt on lt.bucket_key=date_trunc(bucket,b.starts at time zone zone)where metric='activity'),
 bucket_values as(select b.*,
 coalesce(et.opened,0)opened,coalesce(et.closed,0)closed,coalesce(rt.reopened,0)reopened,
 dt.duration_mean,coalesce(dt.sample_count,0)sample_count,coalesce(dt.excluded_count,0)excluded_count,
 (select count(*)from public.sbom_release_coverage_facts f where metric='sbomCoverage'and f.organization_id=org and f.release_id is not null and f.sequence<=cm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)and f.effective_at>=greatest(b.starts,baseline)and f.effective_at<b.ends)coverage_source_count,
 coalesce((select sum(covered_delta)from coverage_totals ct where ct.bucket_key<=date_trunc(bucket,b.starts at time zone zone)),0)covered,
 coalesce((select sum(eligible_delta)from coverage_totals ct where ct.bucket_key<=date_trunc(bucket,b.starts at time zone zone)),0)eligible,
 (select s.payload from public.technical_file_snapshots s where metric='readiness'and s.organization_id=org and s.product_id=product and s.trend_sequence<=sm and pg_visible_in_snapshot(s.recorded_transaction_id,snap)and s.created_at>=b.starts and s.created_at<b.ends order by s.created_at desc,s.trend_sequence desc limit 1)readiness_payload,
 (select count(*)from public.technical_file_snapshots s where metric='readiness'and s.organization_id=org and s.product_id=product and s.trend_sequence<=sm and pg_visible_in_snapshot(s.recorded_transaction_id,snap)and s.created_at>=b.starts and s.created_at<b.ends)snapshot_count
 from boundaries b left join reopening_totals rt on rt.starts=b.starts left join event_totals et on et.bucket_key=date_trunc(bucket,b.starts at time zone zone)left join duration_totals dt on dt.bucket_key=date_trunc(bucket,b.starts at time zone zone)),
 readiness_values as(select v.*,(select count(*)from jsonb_array_elements(coalesce(v.readiness_payload#>'{technicalFile,sections}','[]'))s where s->>'applicability'='applicable')applicable,
 (select count(*)from jsonb_array_elements(coalesce(v.readiness_payload#>'{technicalFile,sections}','[]'))s join jsonb_array_elements(coalesce(v.readiness_payload#>'{readiness,sections}','[]'))r on r->>'sectionKey'=s->>'key'where s->>'applicability'='applicable'and r->>'status'='complete')complete from bucket_values v)
 select coalesce(jsonb_agg(jsonb_build_object('partial',starts<>calendar_starts or ends<>calendar_ends or date_trunc(bucket,calendar_starts at time zone zone)<>calendar_starts at time zone zone,'start',public.m7_snapshot_timestamp_utc(starts),'end',public.m7_snapshot_timestamp_utc(ends),'opened',case when metric='activity'and starts>=baseline then opened end,'closed',case when metric='activity'and starts>=baseline then closed end,'reopened',case when metric='activity'and starts>=baseline then reopened end,'value',case when metric in('triage','remediation')and ends>baseline then duration_mean when metric='sbomCoverage'and starts>=baseline and eligible>0 then round(100.0*covered/eligible,2)when metric='readiness'and applicable>0 then round(100.0*complete/applicable,2)end,'sampleCount',case when metric in('triage','remediation')then sample_count when metric='readiness'then snapshot_count else 0 end,'excludedCount',case when metric in('triage','remediation')then excluded_count else 0 end,'numerator',case when metric='sbomCoverage'and starts>=baseline then covered when metric='readiness'and readiness_payload is not null then complete end,'denominator',case when metric='sbomCoverage'and starts>=baseline then eligible when metric='readiness'and readiness_payload is not null then applicable end,'sourceCount',case when metric='activity'and starts>=baseline then opened+closed+reopened when metric in('triage','remediation')then sample_count+excluded_count when metric='sbomCoverage'and starts>=baseline then coverage_source_count when metric='readiness'then snapshot_count else 0 end)order by starts),'[]')into points from readiness_values;
 else  with recursive calendar_boundaries as(select greatest(from_date::timestamp,d)::timestamp at time zone zone calendar_starts,least((to_date+1)::timestamp,d+case bucket when'day'then interval'1 day'when'week'then interval'1 week'else interval'1 month'end)::timestamp at time zone zone calendar_ends from generate_series(date_trunc(bucket,from_date::timestamp),to_date::timestamp,case bucket when'day'then interval'1 day'when'week'then interval'1 week'else interval'1 month'end)d),
 boundaries as(select case when metric in('activity','sbomCoverage')and calendar_ends>baseline then greatest(calendar_starts,baseline)else calendar_starts end starts,least(calendar_ends,now_at)ends,calendar_starts,calendar_ends from calendar_boundaries where calendar_starts<now_at),
 opening_facts as materialized(select f.finding_id from public.vulnerability_finding_lifecycle_facts f where metric='activity'and f.organization_id=org and f.finding_id is not null and f.previous_sequence is null and f.fact_kind='observation'and(f.product_id=product)and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)),
 legacy_reopening_totals as materialized(select date_trunc(bucket,f.effective_at at time zone zone)bucket_key,count(*)reopened from(select f.finding_id,f.fact_kind,f.effective_at,true is_reopening from public.vulnerability_finding_lifecycle_facts f join lateral(select prev.sequence from public.vulnerability_finding_lifecycle_facts prev where prev.organization_id=org and prev.sequence=f.previous_sequence and prev.payload->>'open'='false'and coalesce(prev.payload->>'superseded','false')='false'limit 1)previous_state on true where metric='activity'and f.organization_id=org and(f.product_id=product)and f.effective_at>=greatest(from_date::timestamp at time zone zone,baseline)and f.effective_at<least((to_date+1)::timestamp at time zone zone,now_at)and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap) and f.is_reopening is null and f.finding_id is not null and f.previous_sequence is not null and f.payload->>'open'='true'and(select probe.sequence from public.vulnerability_finding_lifecycle_facts probe where metric='activity'and probe.organization_id=org and(probe.product_id=product)and probe.effective_at>=greatest(from_date::timestamp at time zone zone,baseline)and probe.effective_at<least((to_date+1)::timestamp at time zone zone,now_at)and probe.sequence<=fm and pg_visible_in_snapshot(probe.recorded_transaction_id,snap) and probe.is_reopening is null and probe.finding_id is not null and probe.previous_sequence is not null and probe.payload->>'open'='true' order by probe.product_id,probe.effective_at,probe.sequence limit 1)is not null)f where f.fact_kind='observation'group by 1),
 identities as materialized((select f.finding_id from public.vulnerability_finding_lifecycle_facts f where metric in('activity','triage','remediation')and f.organization_id=org and f.finding_id is not null and(f.product_id=product)and f.sequence<=fm order by f.finding_id limit 1)
 union all select next_id.finding_id from identities prior cross join lateral(select f.finding_id from public.vulnerability_finding_lifecycle_facts f where f.organization_id=org and f.finding_id>prior.finding_id and(f.product_id=product)and f.sequence<=fm order by f.finding_id limit 1)next_id),
 latest as(select revision.finding_id,revision.first_detected_at,revision.triaged_at,revision.fixed_at,revision.closed_episodes from identities i cross join lateral(select f.finding_id,f.payload->>'firstDetectedAt'first_detected_at,f.payload->>'triagedAt'triaged_at,f.payload->>'fixedAt'fixed_at,f.payload->'closedEpisodes'closed_episodes from public.vulnerability_finding_lifecycle_facts f where f.organization_id=org and f.finding_id=i.finding_id and(f.product_id=product)and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)order by f.sequence desc limit 1)revision),
 events as(select f.finding_id,'opened'kind,l.first_detected_at::timestamptz at from opening_facts f join latest l using(finding_id)
 union all select l.finding_id,'closed',(e->>'at')::timestamptz from latest l cross join lateral jsonb_array_elements(coalesce(l.closed_episodes,'[]'))e),
 durations as(select finding_id,case metric when'triage'then triaged_at ::timestamptz else fixed_at ::timestamptz end at,extract(epoch from(case metric when'triage'then triaged_at ::timestamptz else fixed_at ::timestamptz end- first_detected_at ::timestamptz))/case metric when'triage'then 3600.0 else 86400.0 end value from latest),
 event_totals as(select date_trunc(bucket,e.at at time zone zone)bucket_key,count(*)filter(where kind='opened')opened,count(*)filter(where kind='closed')closed,count(*)filter(where kind='reopened')reopened from events e where metric='activity'and e.at>=greatest(from_date::timestamp at time zone zone,baseline)and e.at<least(now_at,(to_date+1)::timestamp at time zone zone)group by 1),
 duration_totals as(select date_trunc(bucket,d.at at time zone zone)bucket_key,avg(value)filter(where value>=0 and d.at>=baseline)duration_mean,count(*)filter(where value>=0 and d.at>=baseline)sample_count,count(*)filter(where value<0 and d.at>=baseline)excluded_count from durations d where metric in('triage','remediation')and d.at>=from_date::timestamp at time zone zone and d.at<least(now_at,(to_date+1)::timestamp at time zone zone)group by 1),
 coverage_deltas as not materialized(select f.effective_at,f.eligible_delta,f.covered_delta from public.sbom_release_coverage_facts f where metric='sbomCoverage'and f.organization_id=org and f.release_id is not null and(f.product_id=product)and f.sequence<=cm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)and f.effective_at<least(now_at,(to_date+1)::timestamp at time zone zone)and f.eligible_delta is not null and f.covered_delta is not null union all select f.effective_at,(f.payload->>'eligible')::boolean::int-coalesce((prev.payload->>'eligible')::boolean::int,0),((f.payload->>'eligible')::boolean and(f.payload->>'covered')::boolean)::int-coalesce(((prev.payload->>'eligible')::boolean and(prev.payload->>'covered')::boolean)::int,0)from public.sbom_release_coverage_facts f left join public.sbom_release_coverage_facts prev on prev.organization_id=org and prev.sequence=f.previous_sequence where metric='sbomCoverage'and f.organization_id=org and f.release_id is not null and(f.product_id=product)and f.sequence<=cm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)and f.effective_at<least(now_at,(to_date+1)::timestamp at time zone zone)and(f.eligible_delta is null or f.covered_delta is null)and(select probe.sequence from public.sbom_release_coverage_facts probe where metric='sbomCoverage'and probe.organization_id=org and probe.release_id is not null and(probe.product_id=product)and probe.sequence<=cm and pg_visible_in_snapshot(probe.recorded_transaction_id,snap)and probe.effective_at<least(now_at,(to_date+1)::timestamp at time zone zone)and(probe.eligible_delta is null or probe.covered_delta is null) order by probe.product_id,probe.effective_at,probe.sequence limit 1)is not null),
 coverage_totals as(select date_trunc(bucket,effective_at at time zone zone)bucket_key,sum(eligible_delta)eligible_delta,sum(covered_delta)covered_delta from coverage_deltas group by 1),
 reopening_totals as materialized(select b.starts,(select count(*)from public.vulnerability_finding_lifecycle_facts f where metric='activity'and f.organization_id=org and(f.product_id=product)and f.is_reopening=true and f.fact_kind='observation'and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)and f.effective_at>=greatest(b.starts,baseline,from_date::timestamp at time zone zone)and f.effective_at<least(b.ends,now_at,(to_date+1)::timestamp at time zone zone))+coalesce(lt.reopened,0)reopened from boundaries b left join legacy_reopening_totals lt on lt.bucket_key=date_trunc(bucket,b.starts at time zone zone)where metric='activity'),
 bucket_values as(select b.*,
 coalesce(et.opened,0)opened,coalesce(et.closed,0)closed,coalesce(rt.reopened,0)reopened,
 dt.duration_mean,coalesce(dt.sample_count,0)sample_count,coalesce(dt.excluded_count,0)excluded_count,
 (select count(*)from public.sbom_release_coverage_facts f where metric='sbomCoverage'and f.organization_id=org and(f.product_id=product)and f.release_id is not null and f.sequence<=cm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)and f.effective_at>=greatest(b.starts,baseline)and f.effective_at<b.ends)coverage_source_count,
 coalesce((select sum(covered_delta)from coverage_totals ct where ct.bucket_key<=date_trunc(bucket,b.starts at time zone zone)),0)covered,
 coalesce((select sum(eligible_delta)from coverage_totals ct where ct.bucket_key<=date_trunc(bucket,b.starts at time zone zone)),0)eligible,
 (select s.payload from public.technical_file_snapshots s where metric='readiness'and s.organization_id=org and s.product_id=product and s.trend_sequence<=sm and pg_visible_in_snapshot(s.recorded_transaction_id,snap)and s.created_at>=b.starts and s.created_at<b.ends order by s.created_at desc,s.trend_sequence desc limit 1)readiness_payload,
 (select count(*)from public.technical_file_snapshots s where metric='readiness'and s.organization_id=org and s.product_id=product and s.trend_sequence<=sm and pg_visible_in_snapshot(s.recorded_transaction_id,snap)and s.created_at>=b.starts and s.created_at<b.ends)snapshot_count
 from boundaries b left join reopening_totals rt on rt.starts=b.starts left join event_totals et on et.bucket_key=date_trunc(bucket,b.starts at time zone zone)left join duration_totals dt on dt.bucket_key=date_trunc(bucket,b.starts at time zone zone)),
 readiness_values as(select v.*,(select count(*)from jsonb_array_elements(coalesce(v.readiness_payload#>'{technicalFile,sections}','[]'))s where s->>'applicability'='applicable')applicable,
 (select count(*)from jsonb_array_elements(coalesce(v.readiness_payload#>'{technicalFile,sections}','[]'))s join jsonb_array_elements(coalesce(v.readiness_payload#>'{readiness,sections}','[]'))r on r->>'sectionKey'=s->>'key'where s->>'applicability'='applicable'and r->>'status'='complete')complete from bucket_values v)
 select coalesce(jsonb_agg(jsonb_build_object('partial',starts<>calendar_starts or ends<>calendar_ends or date_trunc(bucket,calendar_starts at time zone zone)<>calendar_starts at time zone zone,'start',public.m7_snapshot_timestamp_utc(starts),'end',public.m7_snapshot_timestamp_utc(ends),'opened',case when metric='activity'and starts>=baseline then opened end,'closed',case when metric='activity'and starts>=baseline then closed end,'reopened',case when metric='activity'and starts>=baseline then reopened end,'value',case when metric in('triage','remediation')and ends>baseline then duration_mean when metric='sbomCoverage'and starts>=baseline and eligible>0 then round(100.0*covered/eligible,2)when metric='readiness'and applicable>0 then round(100.0*complete/applicable,2)end,'sampleCount',case when metric in('triage','remediation')then sample_count when metric='readiness'then snapshot_count else 0 end,'excludedCount',case when metric in('triage','remediation')then excluded_count else 0 end,'numerator',case when metric='sbomCoverage'and starts>=baseline then covered when metric='readiness'and readiness_payload is not null then complete end,'denominator',case when metric='sbomCoverage'and starts>=baseline then eligible when metric='readiness'and readiness_payload is not null then applicable end,'sourceCount',case when metric='activity'and starts>=baseline then opened+closed+reopened when metric in('triage','remediation')then sample_count+excluded_count when metric='sbomCoverage'and starts>=baseline then coverage_source_count when metric='readiness'then snapshot_count else 0 end)order by starts),'[]')into points from readiness_values;
 end if;  end if;
 series:=series||jsonb_build_object(metric,jsonb_build_object('state',state,'reason',reason,'unit',unit,'baselineAt',case when metric<>'readiness'then public.m7_snapshot_timestamp_utc(baseline)end,'buckets',points));
 end loop;
 revision:=encode(extensions.digest(jsonb_build_object('series',series,'filters',p_filters,'policyVersion','m14-02-v1')::text,'sha256'),'hex');
 return jsonb_build_object('outcome','found','snapshot',pin,'result',jsonb_build_object('organizationId',org,'filters',p_filters,'policyVersion','m14-02-v1','datasetRevision',revision,'generatedAt',public.m7_snapshot_timestamp_utc(now_at),'baselineAt',public.m7_snapshot_timestamp_utc(baseline),'series',series));
end$function$;
CREATE OR REPLACE FUNCTION public.get_dashboard_trend_sources(p_organization_id uuid, p_actor_user_id uuid, p_filters jsonb, p_snapshot jsonb DEFAULT NULL::jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
 SET plan_cache_mode TO 'force_custom_plan'
 SET jit TO 'off'
AS $function$
declare baseline timestamptz; expected_revision text:=p_filters->>'datasetRevision';access jsonb:=p_filters->'sourceAccess';base_filters jsonb:=p_filters-array['metric','offset','limit','datasetRevision'];dataset jsonb;pin jsonb;metric text:=p_filters->>'metric';product uuid:=(p_filters->>'productId')::uuid;off integer:=coalesce((p_filters->>'offset')::integer,0);lim integer:=coalesce((p_filters->>'limit')::integer,50);rows jsonb;n integer;from_at timestamptz:=(p_filters->>'from')::date::timestamp at time zone(p_filters->>'timezone');to_at timestamptz:=((p_filters->>'to')::date+1)::timestamp at time zone(p_filters->>'timezone');
begin
 if metric not in('activity','triage','remediation','sbomCoverage','readiness')or off<0 or lim not between 1 and 100 then return jsonb_build_object('outcome','invalid_request');end if;
 if expected_revision is not null and p_snapshot is not null then
 -- Revision comes only from the API's authenticated encrypted dataset position.
 -- Authorize source visibility independently before any source rows are read.
 if access->>'products'='false'or not public.m14_actor_can(p_organization_id,p_actor_user_id,'can_view_dashboards')or not public.m14_actor_can(p_organization_id,p_actor_user_id,'can_view_products')then return jsonb_build_object('outcome','not_found');end if;
 if product is not null and not exists(select 1 from public.products where organization_id=p_organization_id and id=product)then return jsonb_build_object('outcome','not_found');end if;
 if (access->>(case when metric in('activity','triage','remediation')then'findings'else metric end))='false'or metric in('activity','triage','remediation')and not public.m14_actor_can(p_organization_id,p_actor_user_id,'can_view_findings')or metric='sbomCoverage'and not public.m14_actor_can(p_organization_id,p_actor_user_id,'can_view_sboms')or metric='readiness'and not public.m14_actor_can(p_organization_id,p_actor_user_id,'can_view_technical_files')then return jsonb_build_object('outcome','forbidden');end if;
 if metric in('triage','remediation','readiness')and product is null then return jsonb_build_object('outcome','forbidden');end if;
 if p_snapshot->>'epoch'is distinct from(select extensions.uuid_generate_v5('4d15a924-d2b2-4cd1-a1b1-ff4c3d81e392'::uuid,payload->>'epoch')::text from public.vulnerability_finding_lifecycle_facts where organization_id=p_organization_id and finding_id is null)then return jsonb_build_object('outcome','conflict');end if;
 if jsonb_typeof(base_filters)<>'object'or (base_filters->>'to')::date<(base_filters->>'from')::date or (base_filters->>'to')::date-(base_filters->>'from')::date>365 or base_filters->>'bucket'not in('day','week','month')or not exists(select 1 from pg_timezone_names where name=base_filters->>'timezone')or (base_filters->>'to')::date>(statement_timestamp()at time zone(base_filters->>'timezone'))::date then return jsonb_build_object('outcome','invalid_request');end if;
 select effective_at into baseline from public.vulnerability_finding_lifecycle_facts where organization_id=p_organization_id and finding_id is null and sequence<=(p_snapshot->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(recorded_transaction_id,(p_snapshot->>'snapshot')::pg_snapshot);
 if metric<>'readiness'and baseline is null then return jsonb_build_object('outcome','forbidden');end if;
 if metric='readiness'and exists(select 1 from public.technical_file_snapshots s where s.organization_id=p_organization_id and s.product_id=product and s.trend_sequence<=(p_snapshot->>'maxSnapshotSequence')::bigint and pg_visible_in_snapshot(s.recorded_transaction_id,(p_snapshot->>'snapshot')::pg_snapshot)and s.created_at>=from_at and s.created_at<least(to_at,(p_snapshot->>'cutoffAt')::timestamptz)and not public.m14_02_snapshot_can(p_organization_id,p_actor_user_id,s.id))then return jsonb_build_object('outcome','forbidden');end if;
 dataset:=jsonb_build_object('snapshot',p_snapshot,'result',jsonb_build_object('datasetRevision',expected_revision,'baselineAt',public.m7_snapshot_timestamp_utc(baseline)));
 else
 dataset:=public.get_dashboard_trends(p_organization_id,p_actor_user_id,base_filters,p_snapshot);if dataset->>'outcome'<>'found'then return dataset;end if;
 if dataset#>>array['result','series',metric,'state']<>'available'then return jsonb_build_object('outcome','forbidden');end if;
 end if;pin:=dataset->'snapshot';to_at:=least(to_at,(pin->>'cutoffAt')::timestamptz);
 if product is null then  with recursive coverage_identities as materialized(select distinct release_id from public.sbom_release_coverage_facts f where metric='sbomCoverage'and from_at>(dataset#>>'{result,baselineAt}')::timestamptz and f.organization_id=p_organization_id and f.release_id is not null and f.sequence<=(pin->>'maxCoverageSequence')::bigint),
 coverage_carried as materialized(select revision.*from coverage_identities i cross join lateral(select f.*from public.sbom_release_coverage_facts f where f.organization_id=p_organization_id and f.release_id=i.release_id and f.sequence<=(pin->>'maxCoverageSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)and f.effective_at<from_at order by f.sequence desc limit 1)revision),
 opening_facts as materialized(select f.*from public.vulnerability_finding_lifecycle_facts f where metric='activity'and f.organization_id=p_organization_id and f.finding_id is not null and f.previous_sequence is null and f.fact_kind='observation'and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)),
 finding_facts as materialized((select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,f.effective_at,f.fact_kind,true is_reopening from public.vulnerability_finding_lifecycle_facts f where metric='activity'and f.fact_kind='observation'and f.organization_id=p_organization_id and f.effective_at>=greatest(from_at,(dataset#>>'{result,baselineAt}')::timestamptz)and f.effective_at<to_at and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot) and f.is_reopening=true order by f.effective_at,('finding-'||f.sequence||'-reopened')limit(off+lim+1))union all (select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,f.effective_at,f.fact_kind,true is_reopening from public.vulnerability_finding_lifecycle_facts f join lateral(select p.sequence from public.vulnerability_finding_lifecycle_facts p where p.organization_id=p_organization_id and p.sequence=f.previous_sequence and p.payload->>'open'='false'and coalesce(p.payload->>'superseded','false')='false'limit 1)previous_state on true where metric='activity'and f.fact_kind='observation'and f.organization_id=p_organization_id and f.effective_at>=greatest(from_at,(dataset#>>'{result,baselineAt}')::timestamptz)and f.effective_at<to_at and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot) and f.is_reopening is null and f.finding_id is not null and f.previous_sequence is not null and f.payload->>'open'='true'order by f.effective_at,('finding-'||f.sequence||'-reopened')limit(off+lim+1))),
 finding_identities as materialized(select id finding_id from public.vulnerability_findings where metric in('activity','triage','remediation')and organization_id=p_organization_id),
 finding_latest as(select revision.sequence,revision.product_id,revision.finding_id,revision.recorded_at,revision.provenance,revision.effective_at,revision.payload from finding_identities i cross join lateral(select f.*from public.vulnerability_finding_lifecycle_facts f where f.organization_id=p_organization_id and f.finding_id=i.finding_id and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)order by f.sequence desc limit 1)revision),
 finding_sources as(select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,case when metric='triage'then(f.payload->>'triagedAt')::timestamptz when metric='remediation'then(f.payload->>'fixedAt')::timestamptz else f.effective_at end effective_at,case when extract(epoch from(case metric when'triage'then(f.payload->>'triagedAt')::timestamptz else(f.payload->>'fixedAt')::timestamptz end-(f.payload->>'firstDetectedAt')::timestamptz))<0 then 'excluded_negative_'||metric when metric='triage'then'first_triage'when metric='remediation'then'applied_remediation'else'observation'end kind from finding_latest f where metric in('triage','remediation')
 union all select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,(l.payload->>'firstDetectedAt')::timestamptz,'opened'from opening_facts f join finding_latest l using(finding_id)where metric='activity'
 union all select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,f.effective_at,'reopened'from finding_facts f where metric='activity'and f.fact_kind='observation'and f.is_reopening
 union all select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,(e->>'at')::timestamptz,'closed:'||(e->>'key')from finding_latest f cross join lateral jsonb_array_elements(coalesce(f.payload->'closedEpisodes','[]'))e where metric='activity' ),
 all_sources as(select 'finding-'||f.sequence||'-'||f.kind id,f.product_id,f.finding_id::text source_id,'finding'::text source_type,f.kind,f.effective_at,f.recorded_at,f.provenance,'/findings?productId='||f.product_id||'&findingId='||f.finding_id href from finding_sources f where f.effective_at>=greatest(from_at,(dataset#>>'{result,baselineAt}')::timestamptz)and f.effective_at<to_at
 union all select 'coverage-carried-'||f.sequence,f.product_id,f.release_id::text,'release','carried_coverage_context',f.effective_at,f.recorded_at,f.provenance,'/products/'||f.product_id from coverage_carried f
 union all select 'coverage-'||f.sequence,f.product_id,f.release_id::text,'release','coverage_observation',f.effective_at,f.recorded_at,f.provenance,'/products/'||f.product_id from public.sbom_release_coverage_facts f where metric='sbomCoverage'and f.organization_id=p_organization_id and f.release_id is not null and f.sequence<=(pin->>'maxCoverageSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)and f.effective_at>=greatest(from_at,(dataset#>>'{result,baselineAt}')::timestamptz)and f.effective_at<to_at
 union all select 'snapshot-'||s.id,s.product_id,s.id::text,'technical_file_snapshot','readiness_at_snapshot',s.created_at,s.created_at,'immutable_snapshot:'||s.payload_sha256,'/products/'||s.product_id||'/technical-file#snapshot-'||s.id from public.technical_file_snapshots s where metric='readiness'and s.organization_id=p_organization_id and s.product_id=product and s.trend_sequence<=(pin->>'maxSnapshotSequence')::bigint and pg_visible_in_snapshot(s.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)and s.created_at>=from_at and s.created_at<to_at),
 page as(select *from all_sources order by effective_at,id offset off limit(lim+1)),
 numbered as(select *,row_number()over(order by effective_at,id)ord from page)
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'productId',product_id,'sourceId',source_id,'sourceType',source_type,'factKind',kind,'effectiveAt',public.m7_snapshot_timestamp_utc(effective_at),'recordedAt',public.m7_snapshot_timestamp_utc(recorded_at),'provenance',provenance,'href',href)order by ord)filter(where ord<=lim),'[]'),count(*)into rows,n from numbered;
 else  with recursive coverage_identities as materialized(select distinct release_id from public.sbom_release_coverage_facts f where metric='sbomCoverage'and from_at>(dataset#>>'{result,baselineAt}')::timestamptz and f.organization_id=p_organization_id and f.release_id is not null and(f.product_id=product)and f.sequence<=(pin->>'maxCoverageSequence')::bigint),
 coverage_carried as materialized(select revision.*from coverage_identities i cross join lateral(select f.*from public.sbom_release_coverage_facts f where f.organization_id=p_organization_id and f.release_id=i.release_id and(f.product_id=product)and f.sequence<=(pin->>'maxCoverageSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)and f.effective_at<from_at order by f.sequence desc limit 1)revision),
 opening_facts as materialized(select f.*from public.vulnerability_finding_lifecycle_facts f where metric='activity'and f.organization_id=p_organization_id and f.finding_id is not null and f.previous_sequence is null and f.fact_kind='observation'and(f.product_id=product)and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)),
 finding_facts as materialized((select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,f.effective_at,f.fact_kind,true is_reopening from public.vulnerability_finding_lifecycle_facts f where metric='activity'and f.fact_kind='observation'and f.organization_id=p_organization_id and(f.product_id=product)and f.effective_at>=greatest(from_at,(dataset#>>'{result,baselineAt}')::timestamptz)and f.effective_at<to_at and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot) and f.is_reopening=true order by f.effective_at,('finding-'||f.sequence||'-reopened')limit(off+lim+1))union all (select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,f.effective_at,f.fact_kind,true is_reopening from public.vulnerability_finding_lifecycle_facts f join lateral(select p.sequence from public.vulnerability_finding_lifecycle_facts p where p.organization_id=p_organization_id and p.sequence=f.previous_sequence and p.payload->>'open'='false'and coalesce(p.payload->>'superseded','false')='false'limit 1)previous_state on true where metric='activity'and f.fact_kind='observation'and f.organization_id=p_organization_id and(f.product_id=product)and f.effective_at>=greatest(from_at,(dataset#>>'{result,baselineAt}')::timestamptz)and f.effective_at<to_at and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot) and f.is_reopening is null and f.finding_id is not null and f.previous_sequence is not null and f.payload->>'open'='true'order by f.effective_at,('finding-'||f.sequence||'-reopened')limit(off+lim+1))),
 finding_identities as materialized((select f.finding_id from public.vulnerability_finding_lifecycle_facts f where metric in('activity','triage','remediation')and f.organization_id=p_organization_id and f.finding_id is not null and(f.product_id=product)and f.sequence<=(pin->>'maxFindingSequence')::bigint order by f.finding_id limit 1)
 union all select next_id.finding_id from finding_identities prior cross join lateral(select f.finding_id from public.vulnerability_finding_lifecycle_facts f where f.organization_id=p_organization_id and f.finding_id>prior.finding_id and(f.product_id=product)and f.sequence<=(pin->>'maxFindingSequence')::bigint order by f.finding_id limit 1)next_id),
 finding_latest as(select revision.sequence,revision.product_id,revision.finding_id,revision.recorded_at,revision.provenance,revision.effective_at,revision.payload from finding_identities i cross join lateral(select f.*from public.vulnerability_finding_lifecycle_facts f where f.organization_id=p_organization_id and f.finding_id=i.finding_id and(f.product_id=product)and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)order by f.sequence desc limit 1)revision),
 finding_sources as(select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,case when metric='triage'then(f.payload->>'triagedAt')::timestamptz when metric='remediation'then(f.payload->>'fixedAt')::timestamptz else f.effective_at end effective_at,case when extract(epoch from(case metric when'triage'then(f.payload->>'triagedAt')::timestamptz else(f.payload->>'fixedAt')::timestamptz end-(f.payload->>'firstDetectedAt')::timestamptz))<0 then 'excluded_negative_'||metric when metric='triage'then'first_triage'when metric='remediation'then'applied_remediation'else'observation'end kind from finding_latest f where metric in('triage','remediation')
 union all select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,(l.payload->>'firstDetectedAt')::timestamptz,'opened'from opening_facts f join finding_latest l using(finding_id)where metric='activity'
 union all select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,f.effective_at,'reopened'from finding_facts f where metric='activity'and f.fact_kind='observation'and f.is_reopening
 union all select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,(e->>'at')::timestamptz,'closed:'||(e->>'key')from finding_latest f cross join lateral jsonb_array_elements(coalesce(f.payload->'closedEpisodes','[]'))e where metric='activity' ),
 all_sources as(select 'finding-'||f.sequence||'-'||f.kind id,f.product_id,f.finding_id::text source_id,'finding'::text source_type,f.kind,f.effective_at,f.recorded_at,f.provenance,'/findings?productId='||f.product_id||'&findingId='||f.finding_id href from finding_sources f where f.effective_at>=greatest(from_at,(dataset#>>'{result,baselineAt}')::timestamptz)and f.effective_at<to_at
 union all select 'coverage-carried-'||f.sequence,f.product_id,f.release_id::text,'release','carried_coverage_context',f.effective_at,f.recorded_at,f.provenance,'/products/'||f.product_id from coverage_carried f
 union all select 'coverage-'||f.sequence,f.product_id,f.release_id::text,'release','coverage_observation',f.effective_at,f.recorded_at,f.provenance,'/products/'||f.product_id from public.sbom_release_coverage_facts f where metric='sbomCoverage'and f.organization_id=p_organization_id and f.release_id is not null and(f.product_id=product)and f.sequence<=(pin->>'maxCoverageSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)and f.effective_at>=greatest(from_at,(dataset#>>'{result,baselineAt}')::timestamptz)and f.effective_at<to_at
 union all select 'snapshot-'||s.id,s.product_id,s.id::text,'technical_file_snapshot','readiness_at_snapshot',s.created_at,s.created_at,'immutable_snapshot:'||s.payload_sha256,'/products/'||s.product_id||'/technical-file#snapshot-'||s.id from public.technical_file_snapshots s where metric='readiness'and s.organization_id=p_organization_id and s.product_id=product and s.trend_sequence<=(pin->>'maxSnapshotSequence')::bigint and pg_visible_in_snapshot(s.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)and s.created_at>=from_at and s.created_at<to_at),
 page as(select *from all_sources order by effective_at,id offset off limit(lim+1)),
 numbered as(select *,row_number()over(order by effective_at,id)ord from page)
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'productId',product_id,'sourceId',source_id,'sourceType',source_type,'factKind',kind,'effectiveAt',public.m7_snapshot_timestamp_utc(effective_at),'recordedAt',public.m7_snapshot_timestamp_utc(recorded_at),'provenance',provenance,'href',href)order by ord)filter(where ord<=lim),'[]'),count(*)into rows,n from numbered;
 end if;  return jsonb_build_object('outcome','found','snapshot',pin,'result',jsonb_build_object('items',rows,'nextOffset',case when n>lim then off+lim end,'datasetRevision',dataset#>>'{result,datasetRevision}'));
end$function$;

notify pgrst,'reload schema';
