-- Classify individual source observations in their authoritative transaction.
-- Null metadata retains the legacy immutable-payload path; no facts are updated.
alter table public.vulnerability_finding_lifecycle_facts add column is_reopening boolean;
alter table public.sbom_release_coverage_facts add column eligible_delta smallint check(eligible_delta between -1 and 1),add column covered_delta smallint check(covered_delta between -1 and 1);
create index m5_trend_reopening_typed_product on public.vulnerability_finding_lifecycle_facts(organization_id,product_id,effective_at,sequence)include(finding_id,recorded_transaction_id,fact_kind)where is_reopening=true;
create index m5_trend_reopening_typed_org on public.vulnerability_finding_lifecycle_facts(organization_id,effective_at,sequence)include(product_id,finding_id,recorded_transaction_id,fact_kind)where is_reopening=true;
create index m5_trend_reopening_legacy_product on public.vulnerability_finding_lifecycle_facts(organization_id,product_id,effective_at,sequence)include(finding_id,previous_sequence,recorded_transaction_id,fact_kind)where is_reopening is null and finding_id is not null and previous_sequence is not null and payload->>'open'='true';
create index m3_trend_delta_product on public.sbom_release_coverage_facts(organization_id,product_id,effective_at,sequence)include(eligible_delta,covered_delta,recorded_transaction_id)where release_id is not null and eligible_delta is not null and covered_delta is not null;
create index m3_trend_delta_org on public.sbom_release_coverage_facts(organization_id,effective_at,sequence)include(product_id,eligible_delta,covered_delta,recorded_transaction_id)where release_id is not null and eligible_delta is not null and covered_delta is not null;
create index m3_trend_legacy_product on public.sbom_release_coverage_facts(organization_id,product_id,effective_at,sequence)include(previous_sequence,recorded_transaction_id)where release_id is not null and(eligible_delta is null or covered_delta is null);
do $migration$
declare definition text;changed text;query_start integer;query_end integer;body text;org_body text;product_body text;
begin
 definition:=pg_get_functiondef('public.m14_02_capture_finding(uuid,uuid,boolean)'::regprocedure);changed:=definition;
 if position($anchor$finding_id,fact_kind,previous_sequence,payload,provenance)values$anchor$in changed)=0 then raise exception 'M14-02 typed source anchor missing';end if;
 changed:=replace(changed,$anchor$finding_id,fact_kind,previous_sequence,payload,provenance)values$anchor$,$replacement$finding_id,fact_kind,previous_sequence,payload,provenance,is_reopening)values$replacement$);
 if position($anchor$case when p_baseline then 'deployment_baseline'else 'source_transaction'end);$anchor$in changed)=0 then raise exception 'M14-02 typed source anchor missing';end if;
 changed:=replace(changed,$anchor$case when p_baseline then 'deployment_baseline'else 'source_transaction'end);$anchor$,$replacement$case when p_baseline then 'deployment_baseline'else 'source_transaction'end,not p_baseline and coalesce(prev.payload->>'open'='false'and coalesce(prev.payload->>'superseded','false')='false'and new_open,false));$replacement$);
 execute changed;
 definition:=pg_get_functiondef('public.m14_02_capture_release(uuid,uuid,boolean)'::regprocedure);changed:=definition;
 if position($anchor$fact_kind,previous_sequence,payload,provenance)values$anchor$in changed)=0 then raise exception 'M14-02 typed source anchor missing';end if;
 changed:=replace(changed,$anchor$fact_kind,previous_sequence,payload,provenance)values$anchor$,$replacement$fact_kind,previous_sequence,payload,provenance,eligible_delta,covered_delta)values$replacement$);
 if position($anchor$case when p_baseline then 'deployment_baseline'else 'source_transaction'end);$anchor$in changed)=0 then raise exception 'M14-02 typed source anchor missing';end if;
 changed:=replace(changed,$anchor$case when p_baseline then 'deployment_baseline'else 'source_transaction'end);$anchor$,$replacement$case when p_baseline then 'deployment_baseline'else 'source_transaction'end,eligible::int-coalesce((prev.payload->>'eligible')::boolean::int,0),(eligible and jsonb_array_length(lineage)>0)::int-coalesce(((prev.payload->>'eligible')::boolean and(prev.payload->>'covered')::boolean)::int,0));$replacement$);
 execute changed;
 definition:=pg_get_functiondef('public.get_dashboard_trends(uuid,uuid,jsonb,jsonb)'::regprocedure);changed:=definition;
 if position($anchor$facts as materialized(select f.*,prev.payload previous from public.vulnerability_finding_lifecycle_facts f join public.vulnerability_finding_lifecycle_facts prev on prev.organization_id=org and prev.sequence=f.previous_sequence where metric='activity'and f.organization_id=org and f.finding_id is not null and f.previous_sequence is not null and f.payload->>'open'='true'and(product is null or f.product_id=product)and f.effective_at>=greatest(from_date::timestamp at time zone zone,baseline)and f.effective_at<least((to_date+1)::timestamp at time zone zone,now_at)and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap))$anchor$in changed)=0 then raise exception 'M14-02 typed source anchor missing';end if;
 changed:=replace(changed,$anchor$facts as materialized(select f.*,prev.payload previous from public.vulnerability_finding_lifecycle_facts f join public.vulnerability_finding_lifecycle_facts prev on prev.organization_id=org and prev.sequence=f.previous_sequence where metric='activity'and f.organization_id=org and f.finding_id is not null and f.previous_sequence is not null and f.payload->>'open'='true'and(product is null or f.product_id=product)and f.effective_at>=greatest(from_date::timestamp at time zone zone,baseline)and f.effective_at<least((to_date+1)::timestamp at time zone zone,now_at)and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap))$anchor$,$replacement$facts as materialized(select f.finding_id,f.fact_kind,f.effective_at,true is_reopening from public.vulnerability_finding_lifecycle_facts f where metric='activity'and f.organization_id=org and(product is null or f.product_id=product)and f.effective_at>=greatest(from_date::timestamp at time zone zone,baseline)and f.effective_at<least((to_date+1)::timestamp at time zone zone,now_at)and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap) and f.is_reopening=true union all select f.finding_id,f.fact_kind,f.effective_at,prev.payload->>'open'='false'and coalesce(prev.payload->>'superseded','false')='false'and f.payload->>'open'='true'from public.vulnerability_finding_lifecycle_facts f join public.vulnerability_finding_lifecycle_facts prev on prev.organization_id=org and prev.sequence=f.previous_sequence where metric='activity'and f.organization_id=org and(product is null or f.product_id=product)and f.effective_at>=greatest(from_date::timestamp at time zone zone,baseline)and f.effective_at<least((to_date+1)::timestamp at time zone zone,now_at)and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap) and f.is_reopening is null and f.finding_id is not null and f.previous_sequence is not null and f.payload->>'open'='true')$replacement$);
 if position($anchor$where fact_kind='observation'and previous->>'open'='false'and coalesce(previous->>'superseded','false')='false'and payload->>'open'='true'$anchor$in changed)=0 then raise exception 'M14-02 typed source anchor missing';end if;
 changed:=replace(changed,$anchor$where fact_kind='observation'and previous->>'open'='false'and coalesce(previous->>'superseded','false')='false'and payload->>'open'='true'$anchor$,$replacement$where fact_kind='observation'and is_reopening$replacement$);
 if position($anchor$coverage_deltas as materialized(select f.effective_at,(f.payload->>'eligible')::boolean::int-coalesce((prev.payload->>'eligible')::boolean::int,0)eligible_delta,((f.payload->>'eligible')::boolean and(f.payload->>'covered')::boolean)::int-coalesce(((prev.payload->>'eligible')::boolean and(prev.payload->>'covered')::boolean)::int,0)covered_delta from public.sbom_release_coverage_facts f left join public.sbom_release_coverage_facts prev on prev.organization_id=org and prev.sequence=f.previous_sequence where metric='sbomCoverage'and f.organization_id=org and f.release_id is not null and(product is null or f.product_id=product)and f.sequence<=cm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)and f.effective_at<now_at)$anchor$in changed)=0 then raise exception 'M14-02 typed source anchor missing';end if;
 changed:=replace(changed,$anchor$coverage_deltas as materialized(select f.effective_at,(f.payload->>'eligible')::boolean::int-coalesce((prev.payload->>'eligible')::boolean::int,0)eligible_delta,((f.payload->>'eligible')::boolean and(f.payload->>'covered')::boolean)::int-coalesce(((prev.payload->>'eligible')::boolean and(prev.payload->>'covered')::boolean)::int,0)covered_delta from public.sbom_release_coverage_facts f left join public.sbom_release_coverage_facts prev on prev.organization_id=org and prev.sequence=f.previous_sequence where metric='sbomCoverage'and f.organization_id=org and f.release_id is not null and(product is null or f.product_id=product)and f.sequence<=cm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)and f.effective_at<now_at)$anchor$,$replacement$coverage_deltas as materialized(select f.effective_at,f.eligible_delta,f.covered_delta from public.sbom_release_coverage_facts f where metric='sbomCoverage'and f.organization_id=org and f.release_id is not null and(product is null or f.product_id=product)and f.sequence<=cm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)and f.effective_at<now_at and f.eligible_delta is not null and f.covered_delta is not null union all select f.effective_at,(f.payload->>'eligible')::boolean::int-coalesce((prev.payload->>'eligible')::boolean::int,0),((f.payload->>'eligible')::boolean and(f.payload->>'covered')::boolean)::int-coalesce(((prev.payload->>'eligible')::boolean and(prev.payload->>'covered')::boolean)::int,0)from public.sbom_release_coverage_facts f left join public.sbom_release_coverage_facts prev on prev.organization_id=org and prev.sequence=f.previous_sequence where metric='sbomCoverage'and f.organization_id=org and f.release_id is not null and(product is null or f.product_id=product)and f.sequence<=cm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)and f.effective_at<now_at and(f.eligible_delta is null or f.covered_delta is null))$replacement$);
 query_start:=position(' with recursive calendar_boundaries as'in changed);query_end:=position(' end if;'in substring(changed from query_start))+query_start-1;
 if query_start=0 or query_end<query_start then raise exception 'M14-02 metric query branch anchor missing';end if;
 body:=substring(changed from query_start for query_end-query_start);
 org_body:=replace(replace(body,'and(product is null or f.product_id=product)',''),'and(product is null or product_id=product)','');
 product_body:=replace(replace(body,'(product is null or f.product_id=product)','(f.product_id=product)'),'(product is null or product_id=product)','(product_id=product)');
 changed:=substring(changed from 1 for query_start-1)||' if product is null then '||org_body||' else '||product_body||' end if; '||substring(changed from query_end);
 execute changed;
end $migration$;
notify pgrst,'reload schema';
