-- Append closure episode revisions; preserve pinned partial calendar bounds.
create or replace function public.m14_02_capture_finding(p_org uuid,p_finding uuid,p_baseline boolean default false) returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare f public.vulnerability_findings; r public.product_releases; a public.vulnerability_finding_assessments; prev public.vulnerability_finding_lifecycle_facts; data jsonb; triage timestamptz; fixed timestamptz; fixed_assessments jsonb;episodes jsonb;new_open boolean;resolved_at timestamptz;
begin
 perform pg_advisory_xact_lock(hashtextextended('m14-finding:'||p_org||':'||p_finding,0));
 select *into f from public.vulnerability_findings where organization_id=p_org and id=p_finding; if not found then return;end if;
 select *into r from public.product_releases where organization_id=p_org and id=f.release_id;
 select *into a from public.vulnerability_finding_assessments where organization_id=p_org and id=public.m5_bulk_effective_assessment_id(p_org,p_finding);
 select min(x.submitted_at)into triage from public.vulnerability_finding_assessments x left join public.vulnerability_finding_assessment_bulk_operation_targets t on t.organization_id=p_org and t.id=x.bulk_operation_target_id where x.organization_id=p_org and x.finding_id=p_finding and x.submitted_by is not null ;
 select min(case when x.approval_required then x.decided_at else x.submitted_at end),coalesce(jsonb_agg(jsonb_build_object('assessmentId',x.id,'revision',x.revision,'effectiveAt',case when x.approval_required then x.decided_at else x.submitted_at end)order by x.revision),'[]')into fixed,fixed_assessments from public.vulnerability_finding_assessments x left join public.vulnerability_finding_assessment_bulk_operation_targets t on t.organization_id=p_org and t.id=x.bulk_operation_target_id where x.organization_id=p_org and x.finding_id=p_finding and x.vex_status='fixed'and x.approval_state in ('approved','approval_not_required')and coalesce(t.state,'')<>'undone';
 select *into prev from public.vulnerability_finding_lifecycle_facts where organization_id=p_org and finding_id=p_finding order by sequence desc limit 1;
 new_open:=public.m5_finding_is_open(p_org,p_finding);
 episodes:=coalesce(prev.payload->'closedEpisodes','[]');
 -- Historical source timestamps are corrected by assessment identity, never by current finding status.
 select coalesce(jsonb_agg(e||case when aa.id is not null then jsonb_build_object('at',case when aa.approval_required then aa.decided_at else aa.submitted_at end)else '{}'::jsonb end order by ord),'[]')into episodes
 from jsonb_array_elements(episodes)with ordinality v(e,ord)left join public.vulnerability_finding_assessments aa on aa.organization_id=p_org and aa.id=(e->>'assessmentId')::uuid and aa.vex_status in('fixed','not_affected')and aa.approval_state in('approved','approval_not_required');
 resolved_at:=coalesce(f.closed_at,case when a.vex_status in('fixed','not_affected')and a.approval_state in('approved','approval_not_required')then case when a.approval_required then a.decided_at else a.submitted_at end end,transaction_timestamp());
 if prev.payload->>'open'='true'and not new_open and f.superseded_at is null then
 episodes:=episodes||jsonb_build_array(jsonb_build_object('key',gen_random_uuid(),'at',resolved_at,'assessmentId',case when f.closed_at is null then a.id end,'sourceClosedAt',f.closed_at));
 elsif prev.payload->>'open'='false'and not new_open and f.closed_at is not null and jsonb_array_length(episodes)>0 then
 episodes:=jsonb_set(episodes,array[(jsonb_array_length(episodes)-1)::text],episodes->(jsonb_array_length(episodes)-1)||jsonb_build_object('at',f.closed_at,'sourceClosedAt',f.closed_at));
 end if;
 data:=jsonb_build_object('closedEpisodes',episodes,'open',new_open,'superseded',f.superseded_at is not null,'firstDetectedAt',f.first_detected_at,'triagedAt',triage,'fixedAt',fixed,'validFixedAssessments',fixed_assessments,'assessmentId',a.id,'assessmentRevision',a.revision,'closedAt',f.closed_at,'reevaluationState',f.reevaluation_state,'sourceVersionId',f.source_record_version_id);

 if prev.payload=data then return;end if;
 insert into public.vulnerability_finding_lifecycle_facts(organization_id,product_id,release_id,finding_id,fact_kind,previous_sequence,payload,provenance)values(p_org,r.product_id,f.release_id,f.id,case when p_baseline then 'baseline'else 'observation'end,prev.sequence,data,case when p_baseline then 'deployment_baseline'else 'source_transaction'end);
end$$;
create or replace function public.get_dashboard_trends(p_organization_id uuid,p_actor_user_id uuid,p_filters jsonb,p_snapshot jsonb default null)returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$
declare org uuid:=p_organization_id;actor uuid:=p_actor_user_id;product uuid:=(p_filters->>'productId')::uuid;from_date date:=(p_filters->>'from')::date;to_date date:=(p_filters->>'to')::date;zone text:=p_filters->>'timezone';bucket text:=p_filters->>'bucket';pin jsonb;baseline timestamptz;snap pg_snapshot;fm bigint;cm bigint;sm bigint;metric text;series jsonb:='{}'::jsonb;points jsonb;state text;reason text;unit text;revision text;access jsonb:=p_filters->'sourceAccess';now_at timestamptz:=statement_timestamp();
begin
 p_filters:=p_filters-'sourceAccess';
 if access->>'products'='false'or not public.m14_actor_can(org,actor,'can_view_dashboards')or not public.m14_actor_can(org,actor,'can_view_products')then return jsonb_build_object('outcome','not_found');end if;
 if product is not null and not exists(select 1 from public.products where organization_id=org and id=product)then return jsonb_build_object('outcome','not_found');end if;
 if from_date is null or to_date is null or to_date<from_date or to_date-from_date>365 or bucket not in ('day','week','month')or not exists(select 1 from pg_timezone_names where name=zone)then return jsonb_build_object('outcome','invalid_request');end if;
 if to_date>(now_at at time zone zone)::date then return jsonb_build_object('outcome','invalid_request');end if;
 if p_snapshot is null then
 pin:=jsonb_build_object('cutoffAt',public.m7_snapshot_timestamp_utc(now_at),'snapshot',pg_current_snapshot()::text,'maxFindingSequence',coalesce((select max(sequence)from public.vulnerability_finding_lifecycle_facts where organization_id=org),0)::text,'maxCoverageSequence',coalesce((select max(sequence)from public.sbom_release_coverage_facts where organization_id=org),0)::text,'maxSnapshotSequence',coalesce((select max(trend_sequence)from public.technical_file_snapshots where organization_id=org),0)::text,'epoch',(select payload->>'epoch'from public.vulnerability_finding_lifecycle_facts where organization_id=org and finding_id is null));
 else pin:=p_snapshot;if pin->>'epoch' is distinct from(select payload->>'epoch'from public.vulnerability_finding_lifecycle_facts where organization_id=org and finding_id is null)then return jsonb_build_object('outcome','conflict');end if;end if;
 now_at:=(pin->>'cutoffAt')::timestamptz;
 snap:=(pin->>'snapshot')::pg_snapshot;fm:=(pin->>'maxFindingSequence')::bigint;cm:=(pin->>'maxCoverageSequence')::bigint;sm:=(pin->>'maxSnapshotSequence')::bigint;
 select effective_at into baseline from public.vulnerability_finding_lifecycle_facts where organization_id=org and finding_id is null and sequence<=fm and pg_visible_in_snapshot(recorded_transaction_id,snap);

 foreach metric in array array['activity','triage','remediation','sbomCoverage','readiness']loop
 state:='available';reason:=null;unit:=case metric when'activity'then'count'when'triage'then'hours'when'remediation'then'days'else'percent'end;
 if (access->>(case when metric in('activity','triage','remediation')then'findings'else metric end))='false'or metric in ('activity','triage','remediation')and not public.m14_actor_can(org,actor,'can_view_findings')or metric='sbomCoverage'and not public.m14_actor_can(org,actor,'can_view_sboms')or metric='readiness'and not public.m14_actor_can(org,actor,'can_view_technical_files')then state:='restricted';reason:='source_permission_required';
 elsif metric in ('triage','remediation','readiness')and product is null then state:='unavailable';reason:='select_product';
 elsif metric<>'readiness'and baseline is null then state:='unavailable';reason:='history_unavailable';
 elsif metric='readiness'and exists(select 1 from public.technical_file_snapshots s where metric='readiness'and s.organization_id=org and s.product_id=product and s.trend_sequence<=sm and pg_visible_in_snapshot(s.recorded_transaction_id,snap)and s.created_at>=from_date::timestamp at time zone zone and s.created_at<(to_date+1)::timestamp at time zone zone and not public.m14_02_snapshot_can(org,actor,s.id))then state:='restricted';reason:='snapshot_source_permission_required';end if;
 if state<>'available'then points:='[]';else
 with calendar_boundaries as(select greatest(from_date::timestamp,d)::timestamp at time zone zone calendar_starts,least((to_date+1)::timestamp,d+case bucket when'day'then interval'1 day'when'week'then interval'1 week'else interval'1 month'end)::timestamp at time zone zone calendar_ends from generate_series(date_trunc(bucket,from_date::timestamp),to_date::timestamp,case bucket when'day'then interval'1 day'when'week'then interval'1 week'else interval'1 month'end)d),
 boundaries as(select case when metric in('activity','sbomCoverage')and calendar_ends>baseline then greatest(calendar_starts,baseline)else calendar_starts end starts,least(calendar_ends,now_at)ends,calendar_starts,calendar_ends from calendar_boundaries where calendar_starts<now_at),
 facts as materialized(select f.*,prev.payload previous from public.vulnerability_finding_lifecycle_facts f left join public.vulnerability_finding_lifecycle_facts prev on prev.organization_id=org and prev.sequence=f.previous_sequence where metric in('activity','triage','remediation')and f.organization_id=org and f.finding_id is not null and(product is null or f.product_id=product)and f.sequence<=fm and pg_visible_in_snapshot(f.recorded_transaction_id,snap)),
 latest as(select distinct on(finding_id)*from facts order by finding_id,sequence desc),
 events as(select f.finding_id,'opened'kind,(l.payload->>'firstDetectedAt')::timestamptz at from facts f join latest l using(finding_id)where f.previous_sequence is null and f.fact_kind='observation'
 union all select l.finding_id,'closed',(e->>'at')::timestamptz from latest l cross join lateral jsonb_array_elements(coalesce(l.payload->'closedEpisodes','[]'))e
 union all select finding_id,'reopened',effective_at from facts where fact_kind='observation'and previous->>'open'='false'and payload->>'open'='true'),
 durations as(select finding_id,case metric when'triage'then(payload->>'triagedAt')::timestamptz else(payload->>'fixedAt')::timestamptz end at,extract(epoch from(case metric when'triage'then(payload->>'triagedAt')::timestamptz else(payload->>'fixedAt')::timestamptz end-(payload->>'firstDetectedAt')::timestamptz))/case metric when'triage'then 3600.0 else 86400.0 end value from latest),
 bucket_values as(select b.*,
 (select count(*)from events e where e.at>=b.starts and e.at<b.ends and kind='opened')opened,
 (select count(*)from events e where e.at>=b.starts and e.at<b.ends and kind='closed')closed,
 (select count(*)from events e where e.at>=b.starts and e.at<b.ends and kind='reopened')reopened,
 (select avg(value)from durations d where d.at>=b.starts and d.at<b.ends and d.at>=baseline and value>=0)duration_mean,
 (select count(*)from durations d where d.at>=b.starts and d.at<b.ends and d.at>=baseline and value>=0)sample_count,
 (select count(*)from durations d where d.at>=b.starts and d.at<b.ends and value<0)excluded_count,
 (select count(*)filter(where (x.payload->>'covered')::boolean)from(select distinct on(release_id)payload from public.sbom_release_coverage_facts where metric='sbomCoverage'and organization_id=org and release_id is not null and(product is null or product_id=product)and sequence<=cm and pg_visible_in_snapshot(recorded_transaction_id,snap)and effective_at<b.ends order by release_id,sequence desc)x where(x.payload->>'eligible')::boolean)covered,
 (select count(*)from(select distinct on(release_id)payload from public.sbom_release_coverage_facts where metric='sbomCoverage'and organization_id=org and release_id is not null and(product is null or product_id=product)and sequence<=cm and pg_visible_in_snapshot(recorded_transaction_id,snap)and effective_at<b.ends order by release_id,sequence desc)x where(x.payload->>'eligible')::boolean)eligible,
 (select s.payload from public.technical_file_snapshots s where metric='readiness'and s.organization_id=org and s.product_id=product and s.trend_sequence<=sm and pg_visible_in_snapshot(s.recorded_transaction_id,snap)and s.created_at>=b.starts and s.created_at<b.ends order by s.created_at desc,s.trend_sequence desc limit 1)readiness_payload,
 (select count(*)from public.technical_file_snapshots s where metric='readiness'and s.organization_id=org and s.product_id=product and s.trend_sequence<=sm and pg_visible_in_snapshot(s.recorded_transaction_id,snap)and s.created_at>=b.starts and s.created_at<b.ends)snapshot_count
 from boundaries b),
 readiness_values as(select v.*,(select count(*)from jsonb_array_elements(coalesce(v.readiness_payload#>'{technicalFile,sections}','[]'))s where s->>'applicability'='applicable')applicable,
 (select count(*)from jsonb_array_elements(coalesce(v.readiness_payload#>'{technicalFile,sections}','[]'))s join jsonb_array_elements(coalesce(v.readiness_payload#>'{readiness,sections}','[]'))r on r->>'sectionKey'=s->>'key'where s->>'applicability'='applicable'and r->>'status'='complete')complete from bucket_values v)
 select coalesce(jsonb_agg(jsonb_build_object('partial',starts<>calendar_starts or ends<>calendar_ends or date_trunc(bucket,calendar_starts at time zone zone)<>calendar_starts at time zone zone,'start',public.m7_snapshot_timestamp_utc(starts),'end',public.m7_snapshot_timestamp_utc(ends),'opened',case when metric='activity'and starts>=baseline then opened end,'closed',case when metric='activity'and starts>=baseline then closed end,'reopened',case when metric='activity'and starts>=baseline then reopened end,'value',case when metric in('triage','remediation')and ends>baseline then duration_mean when metric='sbomCoverage'and starts>=baseline and eligible>0 then round(100.0*covered/eligible,2)when metric='readiness'and applicable>0 then round(100.0*complete/applicable,2)end,'sampleCount',case when metric in('triage','remediation')then sample_count when metric='readiness'then snapshot_count else 0 end,'excludedCount',case when metric in('triage','remediation')then excluded_count else 0 end,'numerator',case when metric='sbomCoverage'and starts>=baseline then covered when metric='readiness'and readiness_payload is not null then complete end,'denominator',case when metric='sbomCoverage'and starts>=baseline then eligible when metric='readiness'and readiness_payload is not null then applicable end,'sourceCount',case when metric='activity'and starts>=baseline then opened+closed+reopened when metric in('triage','remediation')then sample_count+excluded_count when metric='sbomCoverage'and starts>=baseline then eligible when metric='readiness'then snapshot_count else 0 end)order by starts),'[]')into points from readiness_values;
 end if;
 series:=series||jsonb_build_object(metric,jsonb_build_object('state',state,'reason',reason,'unit',unit,'baselineAt',case when metric<>'readiness'then public.m7_snapshot_timestamp_utc(baseline)end,'buckets',points));
 end loop;
 revision:=encode(extensions.digest(jsonb_build_object('series',series,'filters',p_filters,'policyVersion','m14-02-v1')::text,'sha256'),'hex');
 return jsonb_build_object('outcome','found','snapshot',pin,'result',jsonb_build_object('organizationId',org,'filters',p_filters,'policyVersion','m14-02-v1','datasetRevision',revision,'generatedAt',public.m7_snapshot_timestamp_utc(now_at),'baselineAt',public.m7_snapshot_timestamp_utc(baseline),'series',series));
end$$;
create or replace function public.get_dashboard_trend_sources(p_organization_id uuid,p_actor_user_id uuid,p_filters jsonb,p_snapshot jsonb default null)returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$
declare base_filters jsonb:=p_filters-array['metric','offset','limit'];dataset jsonb;pin jsonb;metric text:=p_filters->>'metric';product uuid:=(p_filters->>'productId')::uuid;off integer:=coalesce((p_filters->>'offset')::integer,0);lim integer:=coalesce((p_filters->>'limit')::integer,50);rows jsonb;n integer;from_at timestamptz:=(p_filters->>'from')::date::timestamp at time zone(p_filters->>'timezone');to_at timestamptz:=((p_filters->>'to')::date+1)::timestamp at time zone(p_filters->>'timezone');
begin
 if metric not in('activity','triage','remediation','sbomCoverage','readiness')or off<0 or lim not between 1 and 100 then return jsonb_build_object('outcome','invalid_request');end if;
 dataset:=public.get_dashboard_trends(p_organization_id,p_actor_user_id,base_filters,p_snapshot);if dataset->>'outcome'<>'found'then return dataset;end if;
 if dataset#>>array['result','series',metric,'state']<>'available'then return jsonb_build_object('outcome','forbidden');end if;pin:=dataset->'snapshot';to_at:=least(to_at,(pin->>'cutoffAt')::timestamptz);
 with finding_facts as materialized(select f.*,p.payload previous from public.vulnerability_finding_lifecycle_facts f left join public.vulnerability_finding_lifecycle_facts p on p.organization_id=p_organization_id and p.sequence=f.previous_sequence where f.organization_id=p_organization_id and f.finding_id is not null and(product is null or f.product_id=product)and f.sequence<=(pin->>'maxFindingSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)),
 finding_latest as(select distinct on(finding_id)*from finding_facts order by finding_id,sequence desc),
 finding_sources as(select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,case when metric='triage'then(f.payload->>'triagedAt')::timestamptz when metric='remediation'then(f.payload->>'fixedAt')::timestamptz else f.effective_at end effective_at,case when metric='triage'then'first_triage'when metric='remediation'then'applied_remediation'else'observation'end kind from finding_latest f where metric in('triage','remediation')and extract(epoch from(case metric when'triage'then(f.payload->>'triagedAt')::timestamptz else(f.payload->>'fixedAt')::timestamptz end-(f.payload->>'firstDetectedAt')::timestamptz))>=0
 union all select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,(l.payload->>'firstDetectedAt')::timestamptz,'opened'from finding_facts f join finding_latest l using(finding_id)where metric='activity'and f.fact_kind='observation'and f.previous_sequence is null
 union all select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,f.effective_at,'reopened'from finding_facts f where metric='activity'and f.fact_kind='observation'and f.previous->>'open'='false'and f.payload->>'open'='true'
 union all select f.sequence,f.product_id,f.finding_id,f.recorded_at,f.provenance,(e->>'at')::timestamptz,'closed:'||(e->>'key')from finding_latest f cross join lateral jsonb_array_elements(coalesce(f.payload->'closedEpisodes','[]'))e where metric='activity' ),
 all_sources as(select 'finding-'||f.sequence||'-'||f.kind id,f.product_id,f.finding_id::text source_id,'finding'::text source_type,f.kind,f.effective_at,f.recorded_at,f.provenance,'/findings?productId='||f.product_id href from finding_sources f where f.effective_at>=greatest(from_at,(dataset#>>'{result,baselineAt}')::timestamptz)and f.effective_at<to_at
 union all select 'coverage-'||f.sequence,f.product_id,f.release_id::text,'release','coverage_observation',f.effective_at,f.recorded_at,f.provenance,'/products/'||f.product_id from public.sbom_release_coverage_facts f where metric='sbomCoverage'and f.organization_id=p_organization_id and f.release_id is not null and(product is null or f.product_id=product)and f.sequence<=(pin->>'maxCoverageSequence')::bigint and pg_visible_in_snapshot(f.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)and f.effective_at<to_at
 union all select 'snapshot-'||s.id,s.product_id,s.id::text,'technical_file_snapshot','readiness_at_snapshot',s.created_at,s.created_at,'immutable_snapshot:'||s.payload_sha256,'/products/'||s.product_id||'/technical-file'from public.technical_file_snapshots s where metric='readiness'and s.organization_id=p_organization_id and s.product_id=product and s.trend_sequence<=(pin->>'maxSnapshotSequence')::bigint and pg_visible_in_snapshot(s.recorded_transaction_id,(pin->>'snapshot')::pg_snapshot)and s.created_at>=from_at and s.created_at<to_at),
 page as(select *from all_sources order by effective_at,id offset off limit(lim+1)),
 numbered as(select *,row_number()over(order by effective_at,id)ord from page)
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'productId',product_id,'sourceId',source_id,'sourceType',source_type,'factKind',kind,'effectiveAt',public.m7_snapshot_timestamp_utc(effective_at),'recordedAt',public.m7_snapshot_timestamp_utc(recorded_at),'provenance',provenance,'href',href)order by ord)filter(where ord<=lim),'[]'),count(*)into rows,n from numbered;
 return jsonb_build_object('outcome','found','snapshot',pin,'result',jsonb_build_object('items',rows,'nextOffset',case when n>lim then off+lim end,'datasetRevision',dataset#>>'{result,datasetRevision}'));
end$$;
notify pgrst,'reload schema';
