/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["IdentityController_current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obligations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ObligationController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obligations/{id}/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ObligationController_stages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obligations/from-finding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ObligationController_fromFinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obligations/{id}/anchors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ObligationController_anchor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obligations/tick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ObligationController_tick"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrgController_memberships"];
        put?: never;
        post: operations["OrgController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisations/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrgController_current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductController_list"];
        put?: never;
        post: operations["ProductController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductController_get"];
        put?: never;
        post?: never;
        delete: operations["ProductController_archive"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProductController_transition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SbomController_list"];
        put?: never;
        post: operations["SbomController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/releases/{id}/sbom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SbomController_ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TriageController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/false-positive-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TriageController_rates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TriageController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/{id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TriageController_transition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/{id}/vex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TriageController_vex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/{id}/false-positive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TriageController_falsePositive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EvidenceController_list"];
        put?: never;
        post: operations["EvidenceController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EvidenceController_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AnalyticsController_dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Organisation: {
            /** Format: uuid */
            id: string;
            legalName: string;
            countryMainEstablishment: string;
            coordinatingCsirt: string | null;
            onboardingState: unknown;
        };
        MembershipList: {
            /** Format: uuid */
            organisationId: string;
            legalName: string;
            roleKey: string;
            roleName: string;
        }[];
        Principal: {
            /** Format: uuid */
            organisationId: string;
            roleKey: string;
            permissions: string[];
            mfaSatisfied: boolean;
        };
        CreatedResource: {
            /** Format: uuid */
            id: string;
        };
        Product: {
            /** Format: uuid */
            id: string;
            name: string;
            internalCode: string;
            /** @enum {string} */
            productType: "hardware_with_software" | "standalone_software" | "component" | "remote_data_processing";
            /** @enum {string} */
            lifecycleState: "development" | "placed_on_market" | "in_support" | "end_of_support" | "withdrawn";
            /** Format: date-time */
            placedOnMarketAt: string | null;
            version: number;
        };
        Release: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            productId: string;
            versionLabel: string;
            /** @enum {string} */
            lifecycleState: "development" | "placed_on_market" | "in_support" | "end_of_support" | "withdrawn";
            sbomCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        SbomIngest: {
            ingest: {
                /** Format: uuid */
                sbomDocumentId: string;
                /** @enum {string} */
                validationStatus: "valid" | "valid_with_warnings" | "invalid";
                componentCount: number;
                deduplicated: boolean;
            };
            match: {
                findingsCreated: number;
                kevFindings: number;
            };
        };
        Finding: {
            /** Format: uuid */
            id: string;
            advisoryId: string;
            /** @enum {string} */
            matchMethod: "purl_range" | "cpe_match" | "manual";
            matchConfidence: number;
            cvssBase: number | null;
            kevListed: boolean;
            /** @enum {string} */
            vexStatus: "not_assessed" | "under_investigation" | "affected" | "not_affected" | "fixed";
            /** @enum {string|null} */
            vexJustification: "component_not_present" | "vulnerable_code_not_present" | "vulnerable_code_not_in_execute_path" | "vulnerable_code_cannot_be_controlled_by_adversary" | "inline_mitigations_already_exist" | null;
            /** @enum {string} */
            state: "open" | "in_triage" | "awaiting_approval" | "closed" | "suppressed" | "reopened";
            lowConfidence: boolean;
            /** @enum {string|null} */
            falsePositiveReason: "wrong_version_range" | "wrong_package" | "cpe_too_broad" | "advisory_withdrawn" | "bad_sbom_data" | "other" | null;
            version: number;
        };
        FindingPage: {
            items: {
                /** Format: uuid */
                id: string;
                advisoryId: string;
                /** @enum {string} */
                matchMethod: "purl_range" | "cpe_match" | "manual";
                matchConfidence: number;
                cvssBase: number | null;
                kevListed: boolean;
                /** @enum {string} */
                vexStatus: "not_assessed" | "under_investigation" | "affected" | "not_affected" | "fixed";
                /** @enum {string|null} */
                vexJustification: "component_not_present" | "vulnerable_code_not_present" | "vulnerable_code_not_in_execute_path" | "vulnerable_code_cannot_be_controlled_by_adversary" | "inline_mitigations_already_exist" | null;
                /** @enum {string} */
                state: "open" | "in_triage" | "awaiting_approval" | "closed" | "suppressed" | "reopened";
                lowConfidence: boolean;
                /** @enum {string|null} */
                falsePositiveReason: "wrong_version_range" | "wrong_package" | "cpe_too_broad" | "advisory_withdrawn" | "bad_sbom_data" | "other" | null;
                version: number;
            }[];
            nextCursor: string | null;
            hasMore: boolean;
        };
        FalsePositiveRate: {
            /** @enum {string} */
            dimension: "method" | "ecosystem" | "feed";
            key: string;
            total: number;
            falsePositives: number;
            rate: number;
        };
        Obligation: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            obligationType: "actively_exploited_vulnerability" | "severe_incident";
            /** @enum {string} */
            state: "draft" | "active" | "submitted_partial" | "complete" | "cancelled";
            /** Format: date-time */
            awarenessAt: string;
            /** Format: uuid */
            findingId: string | null;
            /** Format: uuid */
            productReleaseId: string | null;
            /** @enum {string|null} */
            nextStage: "early_warning" | "notification" | "final_report" | null;
            /** Format: date-time */
            nextDueAt: string | null;
            overdue: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        ObligationStage: {
            /** @enum {string} */
            stage: "early_warning" | "notification" | "final_report";
            /** @enum {string} */
            anchorEvent: "awareness" | "remediation_available" | "notification_submitted";
            /** Format: date-time */
            dueAt: string | null;
            /** @enum {string} */
            state: "pending_anchor" | "running" | "submitted" | "overdue" | "not_required";
        };
        ObligationTick: {
            stagesEvaluated: number;
            notifications: {
                /** Format: uuid */
                obligationId: string;
                /** Format: uuid */
                findingId: string | null;
                stage: string;
                /** @enum {string} */
                kind: "threshold" | "overdue";
                threshold: number;
                /** Format: date-time */
                dueAt: string;
            }[];
        };
        Evidence: {
            /** Format: uuid */
            id: string;
            title: string;
            classification: string;
            /** Format: uuid */
            productId: string | null;
            contentHash: string;
            sizeBytes: number;
            /** @enum {string} */
            tamperState: "unverified" | "intact" | "tampered";
            /** Format: date-time */
            uploadedAt: string;
        };
        Dashboard: {
            findingsBySeverity: {
                critical: number;
                high: number;
                medium: number;
                low: number;
                unknown: number;
            };
            kevOpenCount: number;
            activeObligations: {
                /** Format: uuid */
                obligationId: string;
                obligationType: string;
                /** Format: date-time */
                nextDueAt: string | null;
                nextStage: string | null;
                overdue: boolean;
            }[];
            sbomCoverage: {
                products: number;
                releases: number;
                releasesWithSbom: number;
            };
            ingestionHealth: {
                valid: number;
                validWithWarnings: number;
                invalid: number;
                /** Format: date-time */
                lastIngestAt: string | null;
            };
            /** Format: date-time */
            generatedAt: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        ProblemDetails: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            correlationId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    IdentityController_current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Principal"];
                };
            };
        };
    };
    ObligationController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Obligation"][];
                };
            };
        };
    };
    ObligationController_stages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObligationStage"][];
                };
            };
        };
    };
    ObligationController_fromFinding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    findingId: string;
                    /** @enum {string} */
                    obligationType?: "actively_exploited_vulnerability" | "severe_incident";
                    /** Format: date-time */
                    awarenessAt?: string;
                    awarenessBasis?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Obligation"];
                };
            };
        };
    };
    ObligationController_anchor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    anchor: "awareness" | "remediation_available" | "notification_submitted";
                    /** Format: date-time */
                    at: string;
                    reason?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObligationStage"][];
                };
            };
        };
    };
    ObligationController_tick: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObligationTick"];
                };
            };
        };
    };
    OrgController_memberships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipList"];
                };
            };
        };
    };
    OrgController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    legalName: string;
                    countryMainEstablishment: string;
                    registeredAddress?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedResource"];
                };
            };
        };
    };
    OrgController_current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organisation"];
                };
            };
        };
    };
    ProductController_list: {
        parameters: {
            query?: {
                search?: string;
                lifecycleState?: "development" | "placed_on_market" | "in_support" | "end_of_support" | "withdrawn";
                includeArchived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
        };
    };
    ProductController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    internalCode: string;
                    /** @enum {string} */
                    productType?: "hardware_with_software" | "standalone_software" | "component" | "remote_data_processing";
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    ProductController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    ProductController_archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    ProductController_transition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    to: "development" | "placed_on_market" | "in_support" | "end_of_support" | "withdrawn";
                    /** Format: date-time */
                    placedOnMarketAt?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    SbomController_list: {
        parameters: {
            query?: {
                productId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Release"][];
                };
            };
        };
    };
    SbomController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    productId: string;
                    versionLabel: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Release"];
                };
            };
        };
    };
    SbomController_ingest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    document: string;
                    source?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SbomIngest"];
                };
            };
        };
    };
    TriageController_list: {
        parameters: {
            query?: {
                state?: "open" | "in_triage" | "awaiting_approval" | "closed" | "suppressed" | "reopened";
                kevOnly?: boolean;
                minCvss?: number;
                productReleaseId?: string;
                limit?: number;
                minConfidence?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingPage"];
                };
            };
        };
    };
    TriageController_rates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FalsePositiveRate"][];
                };
            };
        };
    };
    TriageController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
        };
    };
    TriageController_transition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    to: "open" | "in_triage" | "awaiting_approval" | "closed" | "suppressed" | "reopened";
                    reason?: string;
                    /** Format: date-time */
                    suppressionExpiresAt?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
        };
    };
    TriageController_vex: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "not_assessed" | "under_investigation" | "affected" | "not_affected" | "fixed";
                    /** @enum {string} */
                    justification?: "component_not_present" | "vulnerable_code_not_present" | "vulnerable_code_not_in_execute_path" | "vulnerable_code_cannot_be_controlled_by_adversary" | "inline_mitigations_already_exist";
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
        };
    };
    TriageController_falsePositive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    reason: "wrong_version_range" | "wrong_package" | "cpe_too_broad" | "advisory_withdrawn" | "bad_sbom_data" | "other";
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
        };
    };
    EvidenceController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"][];
                };
            };
        };
    };
    EvidenceController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    classification: string;
                    /** Format: uuid */
                    productId?: string;
                    /** Format: date-time */
                    validFrom?: string;
                    /** Format: date-time */
                    validUntil?: string;
                    content: string;
                    contentType?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"];
                };
            };
        };
    };
    EvidenceController_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"];
                };
            };
        };
    };
    AnalyticsController_dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
}
