import { describe, expect, it } from "vitest";

import config from "../../docusaurus.config";
import sidebars from "../../sidebars";

describe("documentation configuration", () => {
  it("keeps the deployed site identity and strict broken-link policy", () => {
    expect(config.title).toBe("CRA Docs");
    expect(config.baseUrl).toBe("/");
    expect(config.onBrokenLinks).toBe("throw");
  });

  it("keeps the docs sidebar discoverable", () => {
    expect(sidebars.tutorialSidebar).toEqual([
      { type: "autogenerated", dirName: "." },
    ]);
  });

  it("registers the Tailwind PostCSS integration", () => {
    expect(config.plugins).toHaveLength(1);
    expect(config.plugins?.[0]).toBeTypeOf("function");
  });
});
