import { setupWorker } from "msw/browser";
import { handlers } from "./handlers";

/**
 * Browser-side MSW worker.
 *
 * NOTE on `public/mockServiceWorker.js`: it is generated by `msw init public`
 * and says not to edit it, but its leading blanket `/* eslint-disable *\/` is
 * reported by this repo's config as an unused directive and fails `lint`. It
 * has been removed; the file lints clean on its own. If MSW is upgraded and
 * the worker is regenerated, drop that first line again.
 */
export const worker = setupWorker(...handlers);
